### ISSUE TITLE
1.x 分支版本释放

### ISSUE THREAD

**Issue by kenWu-github** [spring-cloud-incubator/spring-cloud-alibaba#1]
同标题，1.x 分支释放版本有计划什么时间发布呢

**Comment by flystar32** [comment]
你好，感谢关注。项目目前处于孵化阶段，所以离 RELEASE 版本还有一段距离，目前我们正在集成 Nacos 的 spring cloud starter，您可以先本地 mvn install 进行使用。

**Comment by DoZX** [comment]
### 我要把所有遇到的的问题看一遍并且理解，我很看好这个项目，加油(ง •̀_•́)ง

### I want to see all the problems again and understand, I am very bullish on this project, refueling (ง •̀_•́)ง
