### ISSUE TITLE
局部乱码(RestTemplate中文乱码)

### ISSUE THREAD

**Issue by jiaofanting** [spring-cloud-incubator/spring-cloud-alibaba#100]
在`sentinel-core-example`这个examples中，`TestController`中的`/template`请求调用会出现乱码，即在服务中重定向`http://www.taobao.com/test`时会出现乱码。

原因：`RestTemplate` 默认使用 `StringHttpMessageConverter` 来统一对String进行编码和转换，而该类中默认编码格式是：`DEFAULT_CHARSET = StandardCharsets.ISO_8859_1;` 而不是utf-8格式。建议对`Restemplate`做一些修改，或者添加自定义的`StringHttpMessageConverter`。

**Comment by flystar32** [comment]
嗯，是的，RestTemplate 在调用时候需要指定编码，不适合这种场景。

对于这类请求，触发限流时不适合做重定向，适合返回一个 对应格式的 错误信息

**Comment by fangjian0423** [comment]
不应该对 `RestTemplate` 做一些修改。因为 `RestTemplate` 的构造是用户自身决定的，添加自定义的 `HttpMessageConverter` 反而会破坏用户自身管理的 `HttpMessageConverter` 顺序。 `Sentinel` 这边只是给 `RestTemplate` 新增了一个拦截器。

所以把这个过程交给用户处理更加合理。
