### ISSUE TITLE
springcloud Finchley.RELEASE+springboot2.1.0.RELEASE nacos服务注册不生效

### ISSUE THREAD

**Issue by ShawHero** [spring-cloud-incubator/spring-cloud-alibaba#102]
代码如下：
[https://github.com/ShawHero/issue-nacos](url)

**Comment by pbting** [comment]
按照你的说法，我们跑了一下Demo，发现是可以注册上去的。麻烦请帖下你pom文件的引用和代码，看下是怎么写的？

**Comment by darkness463** [comment]
我这边昨天试的时候也遇到了这个问题，spring boot用2.1.0.RELEASE会注册不上，用2.0.6.RELEASE就正常了。

**Comment by flystar32** [comment]
update spring cloud version to Greenwich.BUILD-SNAPSHOT will works , more detail refer to https://github.com/spring-cloud/spring-cloud-commons/issues/446

**Comment by adminzhao** [comment]
应该是SpringBoot 2.1的锅 , Spring Cloud Config 配合Spring Boot 2.1 使用也有很多问题

**Comment by ShawHero** [comment]
谢谢大家的解答，是Spring Boot 2.1.0 本身与 Finchley不兼容，目前将spring boot版本降到2.0.6版本已经解决
