### ISSUE TITLE
热点参数限流没用

### ISSUE THREAD

**Issue by tonggangjin** [spring-cloud-incubator/spring-cloud-alibaba#111]
我在spring cloud 项目中添加了
```
<dependency>
			<groupId>com.alibaba.csp</groupId>
			<artifactId>sentinel-parameter-flow-control</artifactId>
			<version>1.3.0-GA</version>
		</dependency>
```
也通过ParamFlowRuleManager.getRules();拿到热点规则了，如下：
```
[
  {
    "resource": "/client/api/flag/findPage",
    "limitApp": "default",
    "grade": 1,
    "paramIdx": 0,
    "count": 1,
    "paramFlowItemList": []
  },
  {
    "resource": "/client/api/flag/findPage",
    "limitApp": "default",
    "grade": 1,
    "paramIdx": 1,
    "count": 1,
    "paramFlowItemList": []
  }
]
```
但是就是没有起作用

其它限流方式正常，我引入
```
<dependency>
			<groupId>org.springframework.cloud</groupId>
			<artifactId>spring-cloud-starter-alibaba-sentinel</artifactId>
		</dependency>
```
但是没有发现 sentinel-parameter-flow-control 是暂时没有集成的原因吗

**Comment by fangjian0423** [comment]
starter中暂时还没有集成`sentinel-parameter-flow-control` 。

可以先手动添加依赖：

`
<dependency>
    <groupId>com.alibaba.csp</groupId>
    <artifactId>sentinel-parameter-flow-control</artifactId>
    <version>1.3.0-GA</version>
</dependency>
`

不起作用的话能否提供下最少的代码块来看下使用方式。

**Comment by tonggangjin** [comment]
@ @fangjian0423 
我已经添加了
```
<dependency>
    <groupId>com.alibaba.csp</groupId>
    <artifactId>sentinel-parameter-flow-control</artifactId>
    <version>1.3.0-GA</version>
</dependency>
```
但是没有作用，当然我没有作任何其它的配置，不过控制台，已经没有提醒需要引入sentinel-parameter-flow-control，并且可以进行相关配置了。

**Comment by fangjian0423** [comment]
没有作用怀疑用法不对，能否放下代码片段看下你的使用方式。

这是Sentinel官方的使用方式以及demo：

https://github.com/alibaba/Sentinel/wiki/%E7%83%AD%E7%82%B9%E5%8F%82%E6%95%B0%E9%99%90%E6%B5%81

https://github.com/alibaba/Sentinel/tree/master/sentinel-demo/sentinel-demo-parameter-flow-control

**Comment by tonggangjin** [comment]
@fangjian0423 
我只是把依赖放进工程了，我以为可以像spring-cloud-starter-alibaba-sentinel 一样，引入工程，做一下简单配置即可生效，因为没有看到 sentinel-parameter-flow-control 需要配置什么，所以就没有配置，但是在没有引入sentinel-parameter-flow-control 依赖之前，控制台选择 **热点规则** 会提示， 请客服端引入sentinel-parameter-flow-control再使用（大概意思，不是原话），引入sentinel-parameter-flow-control 之后，控制台就能配置了，并且我在客服端添加了一个接口，返回数据就是 `ParamFlowRuleManager.getRules()` 这段代码的返回值，每次在控制台添加了热点规则，然后调用这个接口也能拿到添加的规则，不过规则实际就是没有起效。

**Comment by fangjian0423** [comment]
@tonggangjin 我知道你的意思。你有2个问题：

1. (已解决)starter不支持热点参数规则，所以控制台提示无法加热点规则。这部分加上依赖即可
2. (未解决)加上规则时候，调用 `ParamFlowRuleManager.getRules()` 会返回规则数据，但是规则实际上没有起效。这点**我想让你贴下你的使用代码**，这样才能知道为什么会不起效。 所以需要你贴下代码

**Comment by tonggangjin** [comment]
@tonggangjin 下面项目中使用代码
[https://github.com/tonggangjin/sentinel_test.git](url)

**Comment by fangjian0423** [comment]
@tonggangjin 你好。 你发的这个demo没有任何关于sentinel处理的代码，所以不会生效。

目前热点参数只支持原生的 `SphU` 方式进行限流，暂不支持 `@SentinelResource` 注解。

添加热点规则(或者在sentinel dashboard中配置热点规则)：

```
// 添加规则
ParamFlowRule rule = new ParamFlowRule("test")
    .setParamIdx(0)
    .setCount(1);
// 针对 int 类型的参数 "2"，单独设置限流 QPS 阈值为 3，而不是全局的阈值 1.
ParamFlowItem item = new ParamFlowItem().setObject(String.valueOf(2))
    .setClassType(int.class.getName())
    .setCount(3);

rule.setParamFlowItemList(Collections.singletonList(item));
ParamFlowRuleManager.loadRules(Collections.singletonList(rule));
```

然后在业务代码中进行限流操作：

```
Entry entry = null;
try {
    entry = SphU.entry("resource", EntryType.IN, 1, 2);
    // Add pass for parameter.
} catch (BlockException e1) {
    // block.incrementAndGet();
} catch (Exception e2) {
    // biz exceptionk
} finally {
    // total.incrementAndGet();
    if (entry != null) {
        entry.exit();
    }
}
```

**Comment by tonggangjin** [comment]
谢谢

**Comment by fangjian0423** [comment]
Hi tonggangjin

`ParamFlowRule` will be supported in next version. #115
