### ISSUE TITLE
sentinel-core-example  apollo 不起效

### ISSUE THREAD

**Issue by xubihui** [spring-cloud-incubator/spring-cloud-alibaba#121]
sentinel-core-example  中切换apollo  数据源不起效    1.x分支    读不到数据源  示例如下 

spring.cloud.sentinel.datasource.type=apollo
spring.cloud.sentinel.datasource.namespaceName=application
spring.cloud.sentinel.datasource.flowRulesKey=flowRules
spring.cloud.sentinel.datasource.defaultFlowRuleValue=[]
spring.cloud.sentinel.datasource.converter=myParser

**Comment by fangjian0423** [comment]
@xubihui 你好。

请贴一下报错信息，和你的maven依赖。

**Comment by xubihui** [comment]
￼
![image](https://user-images.githubusercontent.com/12937530/48964195-463cca00-efdd-11e8-919e-b5ca056c2142.png)

![image](https://user-images.githubusercontent.com/12937530/48964197-5b195d80-efdd-11e8-8c1e-26639bc218dd.png)

**Comment by fangjian0423** [comment]
@xubihui 这个是sentinel-datasource模块里提供的apollo，scope是provided，需要在你的example的pom里再添加这个sentinel apollo依赖。

```
<dependency>
    <groupId>com.alibaba.csp</groupId>
    <artifactId>sentinel-datasource-apollo</artifactId>
</dependency>

```
