### ISSUE TITLE
Nacos Config 中如何获取指定 namepsace 的配置

### ISSUE THREAD

**Issue by dante7qx** [spring-cloud-incubator/spring-cloud-alibaba#125]
我的配置如下：
spring:
  application:
      name: nacos-config-provider
  cloud: 
     nacos:
         config: 
             server-addr: 127.0.0.1:8848
             namespace: spiritdev
             group: Spirit
             file-extension: yaml

在 Nacos 中，我创建了命名空间 spiritdev，并在spiritdev 命名空间下创建了配置：
data Id: nacos-config-provider-prod.yaml
groud: Spirit

应用启动后，无法读取到配置

**Comment by pbting** [comment]
> 我的配置如下：
> spring:
> application:
> name: nacos-config-provider
> cloud:
> nacos:
> config:
> server-addr: 127.0.0.1:8848
> namespace: spiritdev
> group: Spirit
> file-extension: yaml
> 
> 在 Nacos 中，我创建了命名空间 spiritdev，并在spiritdev 命名空间下创建了配置：
> data Id: nacos-config-provider-prod.yaml
> groud: Spirit
> 
> 应用启动后，无法读取到配置

那个 namespace的值填的是namespace 的id。在 Nacos的控制台上可以看到。

这里确实比较容易出错，我们会在文档里继续完善这块。

**Comment by dante7qx** [comment]
> > 我的配置如下：
> > spring:
> > application:
> > name: nacos-config-provider
> > cloud:
> > nacos:
> > config:
> > server-addr: 127.0.0.1:8848
> > namespace: spiritdev
> > group: Spirit
> > file-extension: yaml
> > 在 Nacos 中，我创建了命名空间 spiritdev，并在spiritdev 命名空间下创建了配置：
> > data Id: nacos-config-provider-prod.yaml
> > groud: Spirit
> > 应用启动后，无法读取到配置
> 
> 那个 namespace的值填的是namespace 的id。在 Nacos的控制台上可以看到。
> 
> 这里确实比较容易出错，我们会在文档里继续完善这块。

OK，谢谢
