### ISSUE TITLE
sentinel-dubbo-adapter 自定义实现DubboFallback接口 还要手动调用registry

### ISSUE THREAD

**Issue by Houlintao1** [spring-cloud-incubator/spring-cloud-alibaba#130]
sentinel-dubbo-adapter 自定义实现DubboFallback接口 还要手动调用registry，不支持自动注入，注册

**Comment by fangjian0423** [comment]
It will be supported in next version.

**Comment by fangjian0423** [comment]
Hi @Houlintao1 .

`DubboFallbackRegistry` has two `DubboFallback` fields:  `providerFallback` and `consumerFallback`. 

We can not decide `providerFallback` or `consumerFallback` to be setted in `DubboFallbackRegistry` if you define a `DubboFallback` in `ApplicationContext`.

So it can not be supported.
