### ISSUE TITLE
sentinel 动态控制

### ISSUE THREAD

**Issue by ytx1988320** [spring-cloud-incubator/spring-cloud-alibaba#132]
/**
	 * configurations about datasource, like 'nacos', 'apollo', 'file', 'zookeeper'
	 */
	private Map<String, DataSourcePropertiesConfiguration> datasource = new TreeMap<>(
			String.CASE_INSENSITIVE_ORDER);

这个怎么在配置文件配置呢

**Comment by fangjian0423** [comment]
Hi

You could see #91 this issue.

The configurations about multi datasources like this:

```
spring.cloud.sentinel.datasource.ds1.file.file=classpath: flowrule.json
spring.cloud.sentinel.datasource.ds1.file.data-type=json

spring.cloud.sentinel.datasource.ds2.file.file=classpath: degraderule.xml
spring.cloud.sentinel.datasource.ds2.file.data-type=xml

spring.cloud.sentinel.datasource.ds3.nacos.server-addr=localhost:8848
spring.cloud.sentinel.datasource.ds3.nacos.dataId=sentinel
spring.cloud.sentinel.datasource.ds3.nacos.groupId=DEFAULT_GROUP
spring.cloud.sentinel.datasource.ds3.nacos.data-type=json
```

**Comment by ytx1988320** [comment]
那控制台需要自己引入datasource的包，然后自己再打包哦

**Comment by fangjian0423** [comment]
Yes.

You should import datasource dependency if you want to use `Nacos`, `Apollo` or `Zookeeper` DataSource.

Nacos:

```xml
<dependency>
    <groupId>com.alibaba.csp</groupId>
    <artifactId>sentinel-datasource-nacos</artifactId>
</dependency>

```

Apollo:

```xml
<dependency>
    <groupId>com.alibaba.csp</groupId>
    <artifactId>sentinel-datasource-apollo</artifactId>
</dependency>

```

Zookeeper:

```xml
<dependency>
    <groupId>com.alibaba.csp</groupId>
    <artifactId>sentinel-datasource-zookeeper</artifactId>
</dependency>

```

But you do not need to import any dependencies if you use `File` DataSource.

**Comment by ytx1988320** [comment]
我在控制台 
 @PostConstruct
    public void init() {
        ReadableDataSource<String, List<FlowRule>> flowRuleDataSource = new ZookeeperDataSource<>("192.168.33.102:2181", "/DEFAULT_GROUP/sentinel", source -> JSON.parseObject(source, new TypeReference<List<FlowRule>>() {}));
        FlowRuleManager.register2Property(flowRuleDataSource.getProperty());
    }
这样做的，zookeeper连接上了，注册了目录，我配置了限流规则，客户端也能够限流，但是zookeeper的目录里面没有规则，客户端重启规则又没了，我还需要做什么吗？

**Comment by fangjian0423** [comment]
只要保证zk中的数据不丢，格式正确。

客户端重启后还是能读取到对应的配置的。

**Comment by ytx1988320** [comment]
控制台的注册zookeeper方式对吗，我配置了规则，没有写入到zookeeper里面,

**Comment by fangjian0423** [comment]
控制台注册规则，无法写入到zk中，需要自行进行改造，可以参考：https://github.com/alibaba/Sentinel/wiki/在生产环境中使用-Sentinel-控制台

数据在zk中的话是可以推送到客户端的，修改后也会推送。

**Comment by ytx1988320** [comment]
这样啊，后面会加入这样的功能吗？

**Comment by fangjian0423** [comment]
可以关注 wiki 或 官方消息。
