### ISSUE TITLE
解析配置文件注释中文编码错误

### ISSUE THREAD

**Issue by xiekong** [spring-cloud-incubator/spring-cloud-alibaba#133]
![1543575085 1](https://user-images.githubusercontent.com/16237228/49285316-15273280-f4d2-11e8-8a3c-458add0d77d8.jpg)

在IDEA里面运行没有问题，但是打包运行解析配置中心的配置的时候只要注释里面有中文就会报错

**Comment by flystar32** [comment]
请问您能提供一个最小可复现的 demo 吗？ 我在本机的结果是运行正常的？

![配置截图](https://cdn.nlark.com/lark/0/2018/png/54319/1543892767578-120fb2f9-edb3-4a60-a25a-911aa111f754.png)

![运行截图](https://cdn.nlark.com/lark/0/2018/png/54319/1543892761970-6460a57b-b770-4ba5-aebd-acb0cc512646.png)

can you provide a Minimal, Complete, and Verifiable example？

**Comment by xiekong** [comment]
您好，我在IDEA里面跑也是正常的，出现问题的场景是，我把工程打jar包，运行的时候会出现解析配置编码错误，运行环境是window10
  

 

 ------------------ 原始邮件 ------------------
  发件人: "xiaojing"<notifications@github.com>;
 发送时间: 2018年12月4日(星期二) 中午11:07
 收件人: "spring-cloud-incubator/spring-cloud-alibaba"<spring-cloud-alibaba@noreply.github.com>;
 抄送: "谢空"<345833303@qq.com>; "Author"<author@noreply.github.com>; 
 主题: Re: [spring-cloud-incubator/spring-cloud-alibaba] 解析配置文件注释中文编码错误 (#133)

 

 
请问您能提供一个最小可复现的 demo 吗？ 我在本机的结果是运行正常的？
 

 

 
can you provide a Minimal, Complete, and Verifiable example？

**Comment by flystar32** [comment]
you may add a issue to nacos, maybe there's some bug window environment.

**Comment by Lyeluo** [comment]
@xiekong 您好 我也遇见了相同的问题，不过我的配置文件里是有中文配置的，打包后在window和linux环境都会报这个错，您找到解决办法了吗

**Comment by xiekong** [comment]
您好，我没有解决，直接把中文注释给删掉了




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"liujianyu"<notifications@github.com&gt;;
发送时间:&nbsp;2019年11月12日(星期二) 上午9:48
收件人:&nbsp;"alibaba/spring-cloud-alibaba"<spring-cloud-alibaba@noreply.github.com&gt;;
抄送:&nbsp;"谢空"<345833303@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [alibaba/spring-cloud-alibaba] 解析配置文件注释中文编码错误 (#133)




@xiekong 您好 我也遇见了相同的问题，不过我的配置文件里是有中文配置的，打包后在window和linux环境都会报这个错，您找到解决办法了吗

**Comment by Lyeluo** [comment]
@xiekong 哦哦，可能是nacos配置中心不支持中文吧。。谢谢你

**Comment by fangjian0423** [comment]
related #1055

**Comment by ZaneGeng** [comment]
在linux下可以使用中文Nacos配置，windows下不成，在IDEA中都可以
