### ISSUE TITLE
配置缓存本地提升可用性在 k8s 中的替换方案

### ISSUE THREAD

**Issue by fudali113** [spring-cloud-incubator/spring-cloud-alibaba#144]
我不确定目前 nacos config server 会不会在拉取到配置文件后缓存在某一个主机目录下来提高配置中心的可用性？但是在 apollo 中是由这样子的处理的，我认为这样子也确实可以让我们的配置服务可用性更高，不会因为 config server 挂掉后我们只能祈求我们的应用不会因为处理能力或者 bug 导致重启；

但是这种情况在 kubernetes 里面貌似会有一些问题；因为容器死掉目录也就不再了；我能想到的一个办法就是依赖外部储存统一挂载到某个目录，但是这回引入其他的依赖，有没有更好的解决办法呢？

**Comment by flystar32** [comment]
支持的，nacos 在阿里巴巴内部的版本早就实现了这个功能，缓存文件保存在 ~/nacos/config/fixed-{ip}:{port}_nacos/snapshot/{GroupId}/{dataId} 中

**Comment by fudali113** [comment]
> 支持的，nacos 在阿里巴巴内部的版本早就实现了这个功能，缓存文件保存在 ~/nacos/config/fixed-{ip}:{port}_nacos/snapshot/{GroupId}/{dataId} 中

那你们在 k8s 里面是怎么做的呢？就是引入外部储存挂载指定目录？  @flystar32

**Comment by flystar32** [comment]
查看 kubernetes 的文档，https://kubernetes.io/docs/concepts/storage/persistent-volumes/

**Comment by fudali113** [comment]
> 查看 kubernetes 的文档，https://kubernetes.io/docs/concepts/storage/persistent-volumes/
