### ISSUE TITLE
RocketMq Binder 如何适配成Ons Binder

### ISSUE THREAD

**Issue by xiejiashuai** [spring-cloud-incubator/spring-cloud-alibaba#145]
有很多应用方用的是基于RocketMq的阿里云商业版Ons，对于这个Binder是否予以支持下？

**Comment by fangjian0423** [comment]
We have plan to do this in alicloud module because is it a commercial component.

We are very welcome that you can do it by yourself based on RocketMQ Binder.

**Comment by flystar32** [comment]
all these will be down in rocketmq client. just update rocketmq client version to support this feature.
