### ISSUE TITLE
这个 SEPRATOR 单词是不是拼写错了 应该是 SEPARATOR ?

### ISSUE THREAD

**Issue by 502647092** [spring-cloud-incubator/spring-cloud-alibaba#147]
https://github.com/spring-cloud-incubator/spring-cloud-alibaba/blob/de0059359f50c3922f01dd1e2b70897d714c5a93/spring-cloud-alibaba-nacos-config/src/main/java/org/springframework/cloud/alibaba/nacos/client/NacosPropertySourceLocator.java#L44

**Comment by xiaolongzuo** [comment]
Fixed.
