### ISSUE TITLE
Sentinel FeignClient using fallbackFactory throws Exception

### ISSUE THREAD

**Issue by fangjian0423** [spring-cloud-incubator/spring-cloud-alibaba#151]
error detail:

Incompatible fallbackFactory instance. Fallback/fallbackFactory of type MyFallbackFactory is not assignable to EchoService for feign client service-provider

**Comment by Alleninggx** [comment]
Substitute `feign.hystrix.FallbackFactory`  for `org.springframework.cloud.openfeign.FallbackFactory`

I mentioned an [ISSUS](https://github.com/alibaba/spring-cloud-alibaba/issues/2518), which may have something to do with it.
