### ISSUE TITLE
Spring boot应用外置tomcat启动，无法注册到nacos上

### ISSUE THREAD

**Issue by sin668** [spring-cloud-incubator/spring-cloud-alibaba#154]
Spring boot应用打war包（已经做了额外配置的了）放到外置tomcat上启动，没有办法注册到nacos上面，但可以成功注册到eureka。

**Comment by flystar32** [comment]
可以先参考使用这种方式运行起来


```
@Configuration
public class MyNacosLifecycle implements ApplicationContextAware {

    @Autowired(required = false)
    private NacosAutoServiceRegistration registration;

    @Autowired
    private Environment environment;

    @Override
    public void setApplicationContext(ApplicationContext context) throws BeansException {
        if (registration != null) {
            String port = environment.getProperty("server.port");
            registration.setPort(Integer.parseInt(port));
            registration.start();
        }
    }
}
```

**Comment by sin668** [comment]
好的，可以运行起来，接下来发布到测试环境看看调用是否正常。

**Comment by sin668** [comment]
目前只能以上面临时的方法跑起来，升级nacos到0.7版本，去掉这个依然无法注册到nacos。

**Comment by wenwh** [comment]
> 目前只能以上面临时的方法跑起来，升级nacos到0.7版本，去掉这个依然�无法注册到nacos。

请问目前最新版解决了吗？配置项server.port要保证和tomca的端口一致才有用的，感觉不是个办法啊。

**Comment by SamaDream** [comment]
> Spring boot 应用打war包（已经可以额外配置了）启用外置tomcat上启动，没有办法注册到nacos上面，但可以成功注册到eureka。

您好，请问是否能够提供打成war包的源码下，这边idea springboot 启动正常，外置tomcat启动报NoSuchBeanDefinitionException: No qualifying bean of type 'com.alibaba.nacos.naming.core.ServiceManager' available: expected at least 1 bean which qualifies as autowire candidate. Dependency annotations: {@org.springframework.beans.factory.annotation.Autowired(required=true)}
