### ISSUE TITLE
nacos-config中NacosPropertySourceLocator疑问

### ISSUE THREAD

**Issue by wmj765** [spring-cloud-incubator/spring-cloud-alibaba#163]
为什么nacos-config程序启动时会调用两次NacosPropertySourceLocator中locate方法，并且两次的返回结果一样
![image](https://user-images.githubusercontent.com/19549289/49860249-6d482800-fe34-11e8-9340-77592a5df509.png)

**Comment by flystar32** [comment]
spring cloud nacos config 在启动的时候，NacosPropertySourceLocator 的 locate 方法会被调用，从 Nacos Server 端去获取配置信息，这就是你看到的第一次调用。

spring cloud nacos config 为成功获取到数据的 dataid 添加了 listener 监听，当数据发送变更时会实时进行 notify。从而触发 spring 的 context refresher event，进而在这个 context refresh 的过程中，NacosPropertySourceLocator 的 locate 方法会被调用。

Nacos 本身有一个逻辑，在为一个 dataId 添加监听时，必然触发一次 notify 动作。所以这里就会出现第二次调用。

Nacos 设计成在添加监听时必然触发notify的逻辑，是因为之前的业务经验反馈，有很多人喜欢不进行 get，而是 直接 添加 listener 来实现自己的业务逻辑，所以 Nacos 就设计成在添加监听的时候，立即触发一次 notify。

综上，就会出现获取两次的情况，

**Comment by wmj765** [comment]
got it!!
