### ISSUE TITLE
Does Sentinel support gateway?

### ISSUE THREAD

**Issue by qq12157138** [spring-cloud-incubator/spring-cloud-alibaba#166]
我们一般做限流都是在网关层面做改造，我不是很明白Sentinel是代替了网关还是怎么样。他配置的url是否能配置网关（zuul、gateway）的url地址。因为所有流量第一入口肯定从网关进来。

**Comment by fangjian0423** [comment]
[Sentinel](https://github.com/alibaba/Sentinel/wiki) is a library that takes "flow" as the breakthrough point, and covers multiple fields including flow control, concurrency, circuit breaking, and load protection to protect service stability.

It will integration with gateway framework like Zuul, Spring Cloud Gateway.

spring-cloud-alibaba-sentinel-zuul module will be added in this issue https://github.com/spring-cloud-incubator/spring-cloud-alibaba/issues/58 , but it depend on https://github.com/alibaba/Sentinel/pull/188 .

We will start to integration with Spring Cloud Gateway when Sentinel support Spring WebFlux.

**Comment by gaoyaqiu** [comment]
现在 spring-cloud-alibaba-sentinel还不支持Spring Cloud Gateway吗？

**Comment by fangjian0423** [comment]
Sentinel integrate with Spring Cloud Gateway see https://github.com/spring-cloud-incubator/spring-cloud-alibaba/issues/393 .
