### ISSUE TITLE
Nacos Config是否支持Spring Cloud Gateway的动态加载路由？

### ISSUE THREAD

**Issue by noah-wung** [spring-cloud-incubator/spring-cloud-alibaba#167]
在将spring-cloud-starter-alibaba-nacos-config（0.2.0.RELEASE）集成到Spring Cloud Gateway的服务器项目上时，配置的路由信息没有动态加载到，是不支持动态加载Spring Cloud Gateway的路由配置吗？

**Comment by flystar32** [comment]
spring cloud nacos config  的原理是 将配置信息注入到 spring 的 environment 中，并在配置更新时自动触发 context refresh 事件，从而达到将 environment 环境中的配置变更为最新的目的。

你提到的 spring cloud gateway 动态路由属于更高一层的实现，通常来说带有 @RefreshScop 和 @ConfigurationProperties 注解的对象会自动刷新。

如果要实现动态路由，建议监听 RefreshEvent 来实现

**Comment by noah-wung** [comment]
> spring cloud nacos config 的原理是 将配置信息注入到 spring 的 environment 中，并在配置更新时自动触发 context refresh 事件，从而达到将 environment 环境中的配置变更为最新的目标。
> 
> 通常来说带有 @RefreshScop 和 @ConfigurationProperties 注解的对象会自动刷新，你提到的 spring cloud gateway 动态路由属于更高一层的实现，建议监听 RefreshEvent 来实现

我这两天重新调试了一下，直接使用spring-cloud-starter-alibaba-nacos-config（0.2.0.RELEASE）就可以实现动态加载nacos dashboard发布的路由配置。我翻了一下spring cloud   @@gateway的源码，`RouteRefreshListener`这个类已经监听了`ApplicationEvent`事件，在`onApplicationEvent()`方法中就对相关类型的事件做了判断：
```java
	public void onApplicationEvent(ApplicationEvent event) {
		if (event instanceof ContextRefreshedEvent
				|| event instanceof RefreshScopeRefreshedEvent
				|| event instanceof InstanceRegisteredEvent) {
			reset();
		}
		else if (event instanceof ParentHeartbeatEvent) {
			ParentHeartbeatEvent e = (ParentHeartbeatEvent) event;
			resetIfNeeded(e.getValue());
		}
		else if (event instanceof HeartbeatEvent) {
			HeartbeatEvent e = (HeartbeatEvent) event;
			resetIfNeeded(e.getValue());
		}
	}
```
其中`reset()`方法publish了路由更新的事件：
```java
	private void reset() {
		this.publisher.publishEvent(new RefreshRoutesEvent(this));
	}
```
应该不用自己去做监听 `RefreshEvent` 的实现

**Comment by flystar32** [comment]
@noah-wung  赞，原来它已经自动适配了

**Comment by windmeup** [comment]
spring-cloud-dependencies:Finchley.RELEASE
spring-cloud-alibaba-dependencies:0.2.1.RELEASE
spring-boot-dependencies:2.0.7.RELEASE
发现没有实现动态路由,相关资料有许进的文章.
希望可以核实一下
