### ISSUE TITLE
Sentinel 控制台接入失败

### ISSUE THREAD

**Issue by JunjianS** [spring-cloud-incubator/spring-cloud-alibaba#205]
启动控制台后，实时监控数据显示一些 js，json，html，没有应用的信息，怎么才算接入成功 ？请指教

详细信息如下：
引入了以下包

                <dependency>
                        <groupId>com.alibaba.csp</groupId>
                        <artifactId>sentinel-core</artifactId>
                        <version>1.4.0</version>
                </dependency>

		<dependency>
			<groupId>com.alibaba.csp</groupId>
			<artifactId>sentinel-transport-simple-http</artifactId>
			<version>1.4.0</version>
		</dependency>
		<dependency>
			<groupId>com.alibaba.csp</groupId>
			<artifactId>sentinel-annotation-aspectj</artifactId>
			<version>1.4.0</version>
		</dependency>

使用了注解

![image](https://user-images.githubusercontent.com/7474234/50268469-e57ea100-0465-11e9-99e2-3a8c4ca1187a.png)

定义了以下类

![image](https://user-images.githubusercontent.com/7474234/50268491-fb8c6180-0465-11e9-8126-1591ee633ab8.png)

应用启动加入以下参数
-Djava.net.preferIPv4Stack=true
-Dcsp.sentinel.api.port=8719
-Dcsp.sentinel.dashboard.server=localhost:8090
-Dproject.name=eureka-sentinel-producer

控制台启动命令如下

java -Dserver.port=8090 -Dcsp.sentinel.dashboard.server=localhost:8090 -Dproject.name=eureka-sentinel-producer  -jar sentinel-dashboard-1.4.0.jar

**Comment by fangjian0423** [comment]
这是原生的 Sentinel 接入方式，可以参考  https://github.com/spring-cloud-incubator/spring-cloud-alibaba/tree/master/spring-cloud-alibaba-examples/sentinel-example/sentinel-core-example 这个例子接入。

**Comment by JunjianS** [comment]
@fangjian0423 
神速回复，非常感谢
用了starter但控制台还是没有看到应用的资源，只有一堆js，html之类的，说是默认为所有的 HTTP 服务提供了限流埋点，所以没有再加注解@SentinelResource定义资源，配置详情如下
![image](https://user-images.githubusercontent.com/7474234/50270674-54abc380-046d-11e9-954d-240e950306e4.png)

yml文件
![image](https://user-images.githubusercontent.com/7474234/50270903-077c2180-046e-11e9-85bf-63632395b413.png)

控制台启动脚本
![image](https://user-images.githubusercontent.com/7474234/50270954-2c709480-046e-11e9-963a-7d9f2ca187da.png)

控制台效果
![image](https://user-images.githubusercontent.com/7474234/50270651-42318a00-046d-11e9-9196-8bb3c1282e82.png)

**Comment by fangjian0423** [comment]
@JunjianS 

为所有的 HTTP 服务提供了限流埋点是因为有了一个 `CommonFilter`。

你可以访问应用中任意暴露的一个 url，多访问几次，这样 dashboard 中会有对应的数据，比如 example 里就有 `TestController` 中暴露了 `/hello` 和 `/test` 接口，访问后就会有数据。

**Comment by fangjian0423** [comment]
比如这个 `/test` 路径，默认的资源名就是 `/test`

```java
@RequestMapping(value = "/test", method = RequestMethod.GET)
public String test1() {
    return "Hello test";
}
```

再比如这个 `/hello` 路径，默认的资源名就是 `/test`，`hello` 也是一个资源名，因为使用了 `@SentinelResource` 注解，两个资源名都会生效。

```java
@RequestMapping(value = "/hello", method = RequestMethod.GET)
@SentinelResource("hello")
public String hello() {
    return "Hello hello";
}
```

**Comment by JunjianS** [comment]
@fangjian0423 
访问好多次了，控制台还是没有，只有一些js. json之类的，
![image](https://user-images.githubusercontent.com/7474234/50274289-d30d6300-0477-11e9-813a-abc037f772f9.png)

 starter我引用的是否正确？ 我看 Sentinel Starter也没有引进其他jar包，只有一个starter本身的包，sentinel的其他包不需要了吗？
![image](https://user-images.githubusercontent.com/7474234/50274151-73af5300-0477-11e9-83dc-cae1e2cb262a.png)

**Comment by fangjian0423** [comment]
看 dashboard 里已经有应用名了，应该是接入成功了，可以参考 https://github.com/alibaba/Sentinel/wiki/FAQ#q-sentinel-%E6%8E%A7%E5%88%B6%E5%8F%B0%E6%B2%A1%E6%9C%89%E6%98%BE%E7%A4%BA%E6%88%91%E7%9A%84%E5%BA%94%E7%94%A8%E6%88%96%E8%80%85%E6%B2%A1%E6%9C%89%E7%9B%91%E6%8E%A7%E5%B1%95%E7%A4%BA%E5%A6%82%E4%BD%95%E6%8E%92%E6%9F%A5  再排查一下。

**Comment by fangjian0423** [comment]
@JunjianS 

看下应用启动日志，是否有 Sentinel Starter 相关关键字，有的话说明接入成功了。 如果 dashboard 还是没有数据，可以参考上面的 wiki 排查一下。

starter 仅引入了 `spring-cloud-alibaba-sentinel` 这个模块，该模块下有 Sentinel 相关的依赖。

如果还是没有解决，My DingDing code is coderjim, you can add me.

**Comment by xiaolongyuan** [comment]
@JunjianS 你看看那你注册的机器IP 是不是被一些虚拟网络适配器 如 Docker 和 VM

**Comment by xiaolongyuan** [comment]
目前 springboot的配置 还没有客户端IP这个配置   你使用-D指定下

**Comment by xiaolongyuan** [comment]
https://github.com/alibaba/Sentinel/issues/314
https://github.com/alibaba/Sentinel/issues/246

`-Dcsp.sentinel.heartbeat.client.ip=xxxxx`

**Comment by JunjianS** [comment]
是我本地maven的问题，导致starter引入的包没有正常引入，非常感谢 @fangjian0423 的帮助

**Comment by xzmg951** [comment]
添加这个依赖试试
<dependency>
			<groupId>com.alibaba.cloud</groupId>
			<artifactId>spring-cloud-starter-alibaba-sentinel</artifactId>
			<version>2.1.0.RELEASE</version>
		</dependency>
