### ISSUE TITLE
How to get exception instance in fallback of @FeignClient

### ISSUE THREAD

**Issue by wzlee** [spring-cloud-incubator/spring-cloud-alibaba#210]
In fallback, i want to do relevant logical processing or print logs based on exception instances. e. g. ,if entinel's BlockException, i don't expect to fall back directly, but to be handled by blockhandler.

**Comment by fangjian0423** [comment]
It is not support to get Exception instance in Feign with Sentinel and we will design how to do it next version.

**Comment by fangjian0423** [comment]
You can using `fallbackFactory` property in `FeignClient` annotation.

It is a `feign.hystrix.FallbackFactory` instance, you can get throwable cause in `FallbackFactory`.

**Comment by logan2013** [comment]
how is the progress? Can i use sentinel fallback feature and feign.hystrix.FallbackFactory together now?
