### ISSUE TITLE
spring-cloud-starter-alibaba-sentinel 中动态数据源配置不加载ReadableDataSource

### ISSUE THREAD

**Issue by DengLVL** [spring-cloud-incubator/spring-cloud-alibaba#213]
spring-boot 2.1.1.RELEASE
spring-cloud-starter-alibaba-sentinel  0.2.0.RELEASE
动态数据源配置，不会加载ReadableDataSource
@EventListener(classes = ApplicationStartedEvent.class)
//spring-boot2.1以上版本中未执行
public void appStartedListener(ApplicationStartedEvent event) throws Exception {
	//
}

**Comment by fangjian0423** [comment]
Release train Spring Boot compatibility：

| Release Train | Boot Version|
| ------ | ------ |
| Greenwich | 2.1.x |
| Finchley|  2.0.x|
| Edgware | 1.5.x|
| Dalston | 1.5.x|

Spring Boot 2.1.1.RELEASE is using Spring Cloud Greenwich. Maybe you should using Greenwich this version.
