### ISSUE TITLE
What's the difference between spring-cloud-alibaba and spring-cloud-alicloud?

### ISSUE THREAD

**Issue by dongeforever** [spring-cloud-incubator/spring-cloud-alibaba#214]
Is their any top level design on such two projects?

**Comment by xiaolongzuo** [comment]
Sping-Cloud-Alibaba includes open source components, and Sping-Cloud-Alicloud includes commercial components.

**Comment by dongeforever** [comment]
@xiaolongzuo That makes sense. Thanks!

**Comment by xiaolongzuo** [comment]
resolved
