### ISSUE TITLE
运行nacos-config-example报错

### ISSUE THREAD

**Issue by jsjchai** [spring-cloud-incubator/spring-cloud-alibaba#216]
本地运行[nacos-config-example](https://github.com/spring-cloud-incubator/spring-cloud-alibaba/tree/master/spring-cloud-alibaba-examples/nacos-example/nacos-config-example)这个demo报错
nacos
![image](https://user-images.githubusercontent.com/13389058/50404143-8a3f0c80-07df-11e9-95e7-77720a2afacb.png)
异常信息
![image](https://user-images.githubusercontent.com/13389058/50404119-43511700-07df-11e9-9f97-3c241d0fbd6e.png)

**Comment by flystar32** [comment]
Nacos Server 服务端已经有比较大的变更，新版本的 Client 连接老的 Server 会存在一些问题，建议使用最新版本的 Nacos Server。

**Comment by flystar32** [comment]
建议通过控制台去配置数据，看截图感觉有可能数据配置的不对

你也可以看看 ~/nacos/config/fixed-{ip}:{port}_nacos/snapshot/{GroupId}/{dataId} 这个文件里面的内容对不对

**Comment by jsjchai** [comment]
> 建议通过控制台去配置数据，看截图感觉有可能数据配置的不对
> 
> 你也可以看看 ~/nacos/config/fixed-{ip}:{port}_nacos/snapshot/{GroupId}/{dataId} 这个文件里面的内容对不对
生成的配置文件是对的，是我把bootstrap.properties改成了bootstrap.yml导致报的错

**Comment by xiaolongzuo** [comment]
> > 嗯？ 按道理说这个不应该影响， properties 和 yml 都是支持的
> 
> nacos service端配置的文件类型是properties ，客户端配置的是yml

这样肯定是不行的。客户端如果配置的是yml格式，那服务端的文件名（或者说DATAID）应该是 xxx.yml
