### ISSUE TITLE
shared-dataids时会按照profile的粒度来加载吗？

### ISSUE THREAD

**Issue by bomee** [spring-cloud-incubator/spring-cloud-alibaba#218]
https://github.com/spring-cloud-incubator/spring-cloud-alibaba/wiki/Nacos-config#%E6%94%AF%E6%8C%81%E8%87%AA%E5%AE%9A%E4%B9%89%E6%89%A9%E5%B1%95%E7%9A%84-data-id-%E9%85%8D%E7%BD%AE文档中有一个点我未get到，就是使用shared-dataids时会按照profile的粒度来加载吗？

spring.cloud.nacos.config.shared-dataids=bootstrap-common.properties,all-common.properties
spring.profiles.active=test
会按照bootstrap-common-test.properties,all-common-test.properties进行加载吗？

**Comment by bomee** [comment]
目前能想到的解决方案是按namespace来创建相同的配置集，通过启动参数来动态改变namespace做环境的区分

**Comment by pbting** [comment]
> [https://github.com/spring-cloud-incubator/spring-cloud-alibaba/wiki/Nacos-config#%E6%94%AF%E6%8C%81%E8%87%AA%E5%AE%9A%E4%B9%89%E6%89%A9%E5%B1%95%E7%9A%84-data-id-%E9%85%8D%E7%BD%AE文档中有一个点我未get到，就是使用shared-dataids时会按照profile的粒度来加载吗？](https://github.com/spring-cloud-incubator/spring-cloud-alibaba/wiki/Nacos-config#%E6%94%AF%E6%8C%81%E8%87%AA%E5%AE%9A%E4%B9%89%E6%89%A9%E5%B1%95%E7%9A%84-data-id-%E9%85%8D%E7%BD%AE%E6%96%87%E6%A1%A3%E4%B8%AD%E6%9C%89%E4%B8%80%E4%B8%AA%E7%82%B9%E6%88%91%E6%9C%AAget%E5%88%B0%EF%BC%8C%E5%B0%B1%E6%98%AF%E4%BD%BF%E7%94%A8shared-dataids%E6%97%B6%E4%BC%9A%E6%8C%89%E7%85%A7profile%E7%9A%84%E7%B2%92%E5%BA%A6%E6%9D%A5%E5%8A%A0%E8%BD%BD%E5%90%97%EF%BC%9F)
> 
> spring.cloud.nacos.config.shared-dataids=bootstrap-common.properties,all-common.properties
> spring.profiles.active=test
> 会按照bootstrap-common-test.properties,all-common-test.properties进行加载吗？

不会的。通过这个${spring.cloud.nacos.config.shared-dataids} 变量配置的dataid，不会附加任何其他的信息，配置了是啥就加在啥...

**Comment by bomee** [comment]
got

**Comment by jeffmacn** [comment]
如果指定了namespace、group，如何配置shared-dataids？

**Comment by bomee** [comment]
> 如果指定了namespace、group，如何配置shared-dataids？
> 如果不指定namespace，group，shared-dataids取的是pulic，DEFAULT_GROUP

2.0.0.RELEASE 版本可按照这个配置
``` properties
spring.cloud.nacos.config. namespace=XX
spring.cloud.nacos.config. group=XX
spring.cloud.nacos.config. sharedDataids=XX
```
