### ISSUE TITLE
[Feature] 服务发现:Nacos上下线功能无作用

### ISSUE THREAD

**Issue by powerttt** [spring-cloud-incubator/spring-cloud-alibaba#220]
spring-cloud-alibaba>spring-cloud-alibaba-examples>nacos-example  演示项目中nacos服务发现演示项目，在nacos中对服务进行下线、上线功能无任何反应

**Comment by powerttt** [comment]
version:  0.2.1.BUILD-SNAPSHOT

**Comment by flystar32** [comment]
使用 0.2.1.RELEASE 版本

**Comment by powerttt** [comment]
已解决，抱歉，回复的有点晚
