### ISSUE TITLE
希望整合类似swagger的功能

### ISSUE THREAD

**Issue by yuanhongxiang** [spring-cloud-incubator/spring-cloud-alibaba#221]
在开发过程中，我们需要对接口进行测试和开发联调，是否可以参考swagger和springboot集成进行整合，这样可以通过服务注册在nacos后，通过nacos的应用名能查看到该应用提供了哪些服务，并可对相关的api进行测试。同时可以将所有的api导出成word，形成开发接口api文档。

补充：可以参考swagger，该方式很有效

**Comment by flystar32** [comment]
直接使用 Swagger 不行吗？我理解是可以的
