### ISSUE TITLE
Process won't exit after invoke /shutdown endpoint when import sentinel-starter

### ISSUE THREAD

**Issue by xiaolongyuan** [spring-cloud-incubator/spring-cloud-alibaba#222]

**Comment by fangjian0423** [comment]
Sentinel-Starter includes `sentinel-transport-simple-http` module and this module using SPI to trigger `SimpleHttpCommandCenter`.

`SimpleHttpCommandCenter` create a `ServerSocket` and Sentinel Dashboard connect with it.

Endpoint `/shutdown` only close `ApplicationContext` and it will shutdown Servlet Container, but the `ServerSocket` created in `SimpleHttpCommandCenter` is also alive. So the process will not exit.

**Comment by fangjian0423** [comment]
relation with https://github.com/alibaba/Sentinel/issues/345

**Comment by fangjian0423** [comment]
Hi @xiaolongyuan 

After you close `ApplicationContext `, you should invoke `CommandCenterProvider#getCommandCenter` to get `CommandCenter`, then invoke `CommandCenter#stop` to stop the connection of application and sentinel dashboard.
