### ISSUE TITLE
How to change the log directory in Spring Cloud Alibaba Sentinel?

### ISSUE THREAD

**Issue by xbcRaisins** [spring-cloud-incubator/spring-cloud-alibaba#223]
springboot 在 classpath:/ ~.properties 下配置 csp.sentinel.log.dir 没有用，文档上面也没有说明springcloud 中日志路径应该怎样配置？

**Comment by fangjian0423** [comment]
The property key is `spring.cloud.sentinel.log.dir`

You can find it in https://github.com/spring-cloud-incubator/spring-cloud-alibaba/wiki/Sentinel#more

**Comment by fangjian0423** [comment]
Hi @xbcRaisins 

`spring.cloud.sentinel.log.dir` is supported in 0.2.1.RELEASE or 0.1.1.RELEASE.

**Comment by jameszhangmin** [comment]
So how to cusimize the setinel log director without spring-cloud-alibaba but sentinel-core ? My project bases on springboot
