### ISSUE TITLE
@SentinelRestTemplate won't add interceptor when RestTemplate annotated by @Bean annotation and construct in @Configuration class

### ISSUE THREAD

**Issue by jsjchai** [spring-cloud-incubator/spring-cloud-alibaba#227]
RestTemplate配置
![image](https://user-images.githubusercontent.com/13389058/50545843-17f37f80-0c58-11e9-9513-410d1952e791.png)
调用接口（"http://test-provider/test"是一个不存在的地址）
![image](https://user-images.githubusercontent.com/13389058/50545880-85071500-0c58-11e9-9dd2-e85431472ad8.png)
debug 后发现restTemplate对象中没有SentinelProtectInterceptor过滤器
![image](https://user-images.githubusercontent.com/13389058/50545893-e7f8ac00-0c58-11e9-98e4-fa69dadedbae.png)
![image](https://user-images.githubusercontent.com/13389058/50545902-19717780-0c59-11e9-8746-de47023bf29a.png)

spring cloud aliliba version  0.2.1.RELEASE
spring cloud version  Finchley.RELEASE

**Comment by fangjian0423** [comment]
Hi, which spring boot version are you using?

Spring Cloud Finchley is compatibility with 2.0.X

**Comment by zhendong590** [comment]
please show flowrule.json's content

**Comment by jsjchai** [comment]
> compatibility

spring boot version 2.0.6.RELEASE
![image](https://user-images.githubusercontent.com/13389058/50547843-69623580-0c7d-11e9-8f6a-c0c7b58a6641.png)

**Comment by jsjchai** [comment]
> how flowrule.json's content

没有配置限流规则，配置了一个不存在url

**Comment by zhendong590** [comment]
> > how flowrule.json's content
> 
> 没有配置限流规则，配置了一个不存在url

You can have a try 

step1: add sentinel settings in application.properties

```properties
spring.cloud.sentinel.datasource.ds1.file.file=classpath: flowrule.json
spring.cloud.sentinel.datasource.ds1.file.data-type=json
spring.cloud.sentinel.datasource.ds1.file.rule-type=flow
```
step 2: add flowrule.json

```json
[
 {
    "resource": "http://test-provider/test",
    "controlBehavior": 0,
    "count": 0,
    "grade": 1,
    "limitApp": "default",
    "strategy": 0
  }
]
```
step3:curl localhost:{server.port}/testException

**Comment by fangjian0423** [comment]
Hi @jsjchai .

Maybe you can see this example: https://github.com/spring-cloud-incubator/spring-cloud-alibaba/tree/master/spring-cloud-alibaba-examples/sentinel-example/sentinel-core-example

`restTemplate` have `SentinelProtectInterceptor`,  you can try to debug to verify it.

I think maybe you write wrong logic somewhere.

**Comment by jsjchai** [comment]
> SentinelBeanPostProcessor

![image](https://user-images.githubusercontent.com/13389058/50548483-44bf8b00-0c88-11e9-90a9-4f17926cebee.png)

我获取到的beanDefinition.getSource()是 org.springframework.core.type.classreading.MethodMetadataReadingVisitor

**Comment by jsjchai** [comment]
好像是我使用@Configuration这个注解  restTemplate 自动转化成 MethodMetadataReadingVisitor而不是StandardMethodMetadata，放到@SpringBootApplication这个注解下注入就是StandardMethodMetadata

**Comment by fangjian0423** [comment]
> 我在类上面添加了@configuration这个注解， 注入 的restTemplate 自动转化成 MethodMetadataReadingVisitor而不是StandardMethodMetadata，放到@SpringBootApplication这个注解下注入就是StandardMethodMetadata

A bean annotated by `@SpringBootApplication` scan by `AnnotatedBeanDefinitionReader`.

`AnnotatedBeanDefinitionReader` build `AnnotatedGenericBeanDefinition` when register bean.

`AnnotatedGenericBeanDefinition` using `StandardAnnotationMetadata` to assign to its property `metadata` in constructor.

This is an entrance bean of Spring Boot Application.

A bean annotated by `@Configuration` will register in `ConfigurationClassParser` and this parser will using `ClassPathBeanDefinitionScanner` to scan components with `@ComponentScans` or `@ComponentScan` annotation. 

Spring using `SimpleMetadataReader` to get  `annotationMetadata`  in `ClassPathBeanDefinitionScanner#doScan`. This `annotationMetadata` is `AnnotationMetadataReadingVisitor`.

SimpleMetadataReader is `MetadataReader` implementation based on an ASM `org.springframework.asm.ClassReader`.

**Comment by lele126** [comment]
@jsjchai 请问这个解决了没
