### ISSUE TITLE
bug,在spring cloud alibaba 中随便写一个Get 请求的RestController,然后用postman模拟调用报错

### ISSUE THREAD

**Issue by yikangfeng** [spring-cloud-incubator/spring-cloud-alibaba#229]
bug,在spring cloud alibaba 中随便写一个GET请求的RestController,然后用postman 模拟调用，在header 中添加 Accept=text/plain, text/plain, text/plain, text/plain, text/plain, text/plain, text/plain, text/plain, text/plain, text/plain, text/plain, text/plain, text/plain, text/plain, text/plain, text/plain, text/plain, text/plain, text/plain, text/plain, text/plain, text/plain, text/plain, text/plain, text/plain, text/plain, text/plain, text/plain, text/plain, text/plain, text/plain, text/plain, text/plain, text/plain, text/plain, text/plain, text/plain, text/plain, text/plain, text/plain, text/plain, text/plain, text/plain, text/plain, text/plain, text/plain, text/plain, application/json, application/*+json, */*, */*, */*, */*, */*, */*, */*, */*, */*, */*, */*, */*, */*, */*, */*, */*, */*, */*, */*, */*, */*, */*, */*, */*, */*, */*, */*, */*, */*, */*, */*, */*, */*, */*, */*, */*, */*, */*, */*, */*, */*, */*, */*, */*, */*, */*, */*  
直接报504错误。
请麻烦尽快修正，谢谢。

**Comment by pbting** [comment]
> bug,在spring cloud alibaba 中随便写一个GET请求的RestController,然后用postman 模拟调用，在header 中添加 Accept=text/plain, text/plain, text/plain, text/plain, text/plain, text/plain, text/plain, text/plain, text/plain, text/plain, text/plain, text/plain, text/plain, text/plain, text/plain, text/plain, text/plain, text/plain, text/plain, text/plain, text/plain, text/plain, text/plain, text/plain, text/plain, text/plain, text/plain, text/plain, text/plain, text/plain, text/plain, text/plain, text/plain, text/plain, text/plain, text/plain, text/plain, text/plain, text/plain, text/plain, text/plain, text/plain, text/plain, text/plain, text/plain, text/plain, text/plain, application/json, application/*+json, _/_, _/_, _/_, _/_, _/_, _/_, _/_, _/_, _/_, _/_, _/_, _/_, _/_, _/_, _/_, _/_, _/_, _/_, _/_, _/_, _/_, _/_, _/_, _/_, _/_, _/_, _/_, _/_, _/_, _/_, _/_, _/_, _/_, _/_, _/_, _/_, _/_, _/_, _/_, _/_, _/_, _/_, _/_, _/_, _/_, _/_, _/_
> 直接报504错误。
> 请麻烦尽快修正，谢谢。
有两点不太明确的地方：
1、你这个有某个特殊的场景要支持这么做吗？
2、另外从哪里可以看出是 Spring Cloud Alibaba 抛出来的 bug ？如果不用 Spring Cloud Alibaba,这个问题没有复现吗？

**Comment by KimZing** [comment]
> bug,在spring cloud alibaba 中随便写一个GET请求的RestController,然后用postman 模拟调用，在header 中添加 Accept=text/plain, text/plain, text/plain, text/plain, text/plain, text/plain, text/plain, text/plain, text/plain, text/plain, text/plain, text/plain, text/plain, text/plain, text/plain, text/plain, text/plain, text/plain, text/plain, text/plain, text/plain, text/plain, text/plain, text/plain, text/plain, text/plain, text/plain, text/plain, text/plain, text/plain, text/plain, text/plain, text/plain, text/plain, text/plain, text/plain, text/plain, text/plain, text/plain, text/plain, text/plain, text/plain, text/plain, text/plain, text/plain, text/plain, text/plain, application/json, application/*+json, _/_, _/_, _/_, _/_, _/_, _/_, _/_, _/_, _/_, _/_, _/_, _/_, _/_, _/_, _/_, _/_, _/_, _/_, _/_, _/_, _/_, _/_, _/_, _/_, _/_, _/_, _/_, _/_, _/_, _/_, _/_, _/_, _/_, _/_, _/_, _/_, _/_, _/_, _/_, _/_, _/_, _/_, _/_, _/_, _/_, _/_, _/_
> 直接报504错误。
> 请麻烦尽快修正，谢谢。
如果你能说明你是在什么场景下，为什么要这样做，这样做报的具体错误，可能别人会更好的回答你这个问题

**Comment by yikangfeng** [comment]
就是我们写的一个服务，内部有个fireman 的东西掉了下，就发现了这个错误。应该说是 不经意发现的。还望大神指导下，谢谢。

**Comment by yikangfeng** [comment]
> > bug,在spring cloud alibaba 中随便写一个GET请求的RestController,然后用postman 模拟调用，在header 中添加 Accept=text/plain, text/plain, text/plain, text/plain, text/plain, text/plain, text/plain, text/plain, text/plain, text/plain, text/plain, text/plain, text/plain, text/plain, text/plain, text/plain, text/plain, text/plain, text/plain, text/plain, text/plain, text/plain, text/plain, text/plain, text/plain, text/plain, text/plain, text/plain, text/plain, text/plain, text/plain, text/plain, text/plain, text/plain, text/plain, text/plain, text/plain, text/plain, text/plain, text/plain, text/plain, text/plain, text/plain, text/plain, text/plain, text/plain, text/plain, application/json, application/*+json, _/_, _/_, _/_, _/_, _/_, _/_, _/_, _/_, _/_, _/_, _/_, _/_, _/_, _/_, _/_, _/_, _/_, _/_, _/_, _/_, _/_, _/_, _/_, _/_, _/_, _/_, _/_, _/_, _/_, _/_, _/_, _/_, _/_, _/_, _/_, _/_, _/_, _/_, _/_, _/_, _/_, _/_, _/_, _/_, _/_, _/_, _/_
> > 直接报504错误。
> > 请麻烦尽快修正，谢谢。
> > 如果你能说明你是在什么场景下，为什么要这样做，这样做报的具体错误，可能别人会更好的回答你这个问题

就是我们内部写的一个服务，平时内部有个fireman 的东西在正常调用，就发现了这个错误。应该说是 不经意发现的。还望大神指导下，谢谢。

**Comment by pbting** [comment]
> > > bug,在spring cloud alibaba 中随便写一个GET请求的RestController,然后用postman 模拟调用，在header 中添加 Accept=text/plain, text/plain, text/plain, text/plain, text/plain, text/plain, text/plain, text/plain, text/plain, text/plain, text/plain, text/plain, text/plain, text/plain, text/plain, text/plain, text/plain, text/plain, text/plain, text/plain, text/plain, text/plain, text/plain, text/plain, text/plain, text/plain, text/plain, text/plain, text/plain, text/plain, text/plain, text/plain, text/plain, text/plain, text/plain, text/plain, text/plain, text/plain, text/plain, text/plain, text/plain, text/plain, text/plain, text/plain, text/plain, text/plain, text/plain, application/json, application/*+json, _/_, _/_, _/_, _/_, _/_, _/_, _/_, _/_, _/_, _/_, _/_, _/_, _/_, _/_, _/_, _/_, _/_, _/_, _/_, _/_, _/_, _/_, _/_, _/_, _/_, _/_, _/_, _/_, _/_, _/_, _/_, _/_, _/_, _/_, _/_, _/_, _/_, _/_, _/_, _/_, _/_, _/_, _/_, _/_, _/_, _/_, _/_
> > > 直接报504错误。
> > > 请麻烦尽快修正，谢谢。
> > > 如果你能说明你是在什么场景下，为什么要这样做，这样做报的具体错误，可能别人会更好的回答你这个问题
> 
> 就是我们内部写的一个服务，平时内部有个fireman 的东西在正常调用，就发现了这个错误。应该说是 不经意发现的。还望大神指导下，谢谢。

首先我理解这是 Http 协议层面上导致的一个错误。按照您提供的Http Accept 的内容 ，我们写了一个测试，提示的异常信息是：
```java
Resolved [org.springframework.web.HttpMediaTypeNotAcceptableException: Could not parse 'Accept' header [text/plain, text/plain, text/plain, text/plain, text/plain, text/plain, text/plain, text/plain, text/plain, text/plain, text/plain, text/plain, text/plain, text/plain, text/plain, text/plain, text/plain, text/plain, text/plain, text/plain, text/plain, text/plain, text/plain, text/plain, text/plain, text/plain, text/plain, text/plain, text/plain, text/plain, text/plain, text/plain, text/plain, text/plain, text/plain, text/plain, text/plain, text/plain, text/plain, text/plain, text/plain, text/plain, text/plain, text/plain, text/plain, text/plain, text/plain, application/json, application/*+json, /, /, /, /, /, /, /, /, /, /, /, /, /, /, /, /, /, /, /, /, /, /, /, /, /, /, /, /, /, /, /, /, /, /, /, /, /, /, /, /, /, /, /, /, /, /, /]: 
Invalid mime type "/": does not contain subtype after '/']
2019-01-04 10:00:08.999  WARN [sc-migrate-eureka-consumer,ba0cdcfaddfe7383,ba0cdcfaddfe7383,false] 25475 --- [io-40051-exec-5] .w.s.m.s.DefaultHandlerExceptionResolver :
```
所以这个跟是否是使用Spring Cloud Alibaba 后服务调用异常是没有关系的。

另外，根据您提供的这个Http Accpet的内容信息，看上去也是一个不正常的Accept,如果你们非要避免这种不规则的Accept,那你们就应该增加一个类似Filter 的东西，对 Header 中内容的合法性做一个正确性校验。

**Comment by yikangfeng** [comment]
> > > > bug,在spring cloud alibaba 中随便写一个GET请求的RestController,然后用postman 模拟调用，在header 中添加 Accept=text/plain, text/plain, text/plain, text/plain, text/plain, text/plain, text/plain, text/plain, text/plain, text/plain, text/plain, text/plain, text/plain, text/plain, text/plain, text/plain, text/plain, text/plain, text/plain, text/plain, text/plain, text/plain, text/plain, text/plain, text/plain, text/plain, text/plain, text/plain, text/plain, text/plain, text/plain, text/plain, text/plain, text/plain, text/plain, text/plain, text/plain, text/plain, text/plain, text/plain, text/plain, text/plain, text/plain, text/plain, text/plain, text/plain, text/plain, application/json, application/*+json, _/_, _/_, _/_, _/_, _/_, _/_, _/_, _/_, _/_, _/_, _/_, _/_, _/_, _/_, _/_, _/_, _/_, _/_, _/_, _/_, _/_, _/_, _/_, _/_, _/_, _/_, _/_, _/_, _/_, _/_, _/_, _/_, _/_, _/_, _/_, _/_, _/_, _/_, _/_, _/_, _/_, _/_, _/_, _/_, _/_, _/_, _/_
> > > > 直接报504错误。
> > > > 请麻烦尽快修正，谢谢。
> > > > 如果你能说明你是在什么场景下，为什么要这样做，这样做报的具体错误，可能别人会更好的回答你这个问题
> > 
> > 
> > 就是我们内部写的一个服务，平时内部有个fireman 的东西在正常调用，就发现了这个错误。应该说是 不经意发现的。还望大神指导下，谢谢。
> 
> 首先我理解这是 Http 协议层面上导致的一个错误。按照您提供的Http Accept 的内容 ，我们写了一个测试，提示的异常信息是：
> 
> ```java
> Resolved [org.springframework.web.HttpMediaTypeNotAcceptableException: Could not parse 'Accept' header [text/plain, text/plain, text/plain, text/plain, text/plain, text/plain, text/plain, text/plain, text/plain, text/plain, text/plain, text/plain, text/plain, text/plain, text/plain, text/plain, text/plain, text/plain, text/plain, text/plain, text/plain, text/plain, text/plain, text/plain, text/plain, text/plain, text/plain, text/plain, text/plain, text/plain, text/plain, text/plain, text/plain, text/plain, text/plain, text/plain, text/plain, text/plain, text/plain, text/plain, text/plain, text/plain, text/plain, text/plain, text/plain, text/plain, text/plain, application/json, application/*+json, /, /, /, /, /, /, /, /, /, /, /, /, /, /, /, /, /, /, /, /, /, /, /, /, /, /, /, /, /, /, /, /, /, /, /, /, /, /, /, /, /, /, /, /, /, /, /]: 
> Invalid mime type "/": does not contain subtype after '/']
> 2019-01-04 10:00:08.999  WARN [sc-migrate-eureka-consumer,ba0cdcfaddfe7383,ba0cdcfaddfe7383,false] 25475 --- [io-40051-exec-5] .w.s.m.s.DefaultHandlerExceptionResolver :
> ```
> 
> 所以这个跟是否是使用Spring Cloud Alibaba 后服务调用异常是没有关系的。
> 
> 另外，根据您提供的这个Http Accpet的内容信息，看上去也是一个不正常的Accept,如果你们非要避免这种不规则的Accept,那你们就应该增加一个类似Filter 的东西，对 Header 中内容的合法性做一个正确性校验。

感谢回复。我用postman 调用报错堆栈信息如下：
![image](https://user-images.githubusercontent.com/6268253/50735089-e80e2400-11e3-11e9-9f55-54558eab40da.png)

**Comment by yikangfeng** [comment]
> > > > > bug,在spring cloud alibaba 中随便写一个GET请求的RestController,然后用postman 模拟调用，在header 中添加 Accept=text/plain, text/plain, text/plain, text/plain, text/plain, text/plain, text/plain, text/plain, text/plain, text/plain, text/plain, text/plain, text/plain, text/plain, text/plain, text/plain, text/plain, text/plain, text/plain, text/plain, text/plain, text/plain, text/plain, text/plain, text/plain, text/plain, text/plain, text/plain, text/plain, text/plain, text/plain, text/plain, text/plain, text/plain, text/plain, text/plain, text/plain, text/plain, text/plain, text/plain, text/plain, text/plain, text/plain, text/plain, text/plain, text/plain, text/plain, application/json, application/*+json, _/_, _/_, _/_, _/_, _/_, _/_, _/_, _/_, _/_, _/_, _/_, _/_, _/_, _/_, _/_, _/_, _/_, _/_, _/_, _/_, _/_, _/_, _/_, _/_, _/_, _/_, _/_, _/_, _/_, _/_, _/_, _/_, _/_, _/_, _/_, _/_, _/_, _/_, _/_, _/_, _/_, _/_, _/_, _/_, _/_, _/_, _/_
> > > > > 直接报504错误。
> > > > > 请麻烦尽快修正，谢谢。
> > > > > 如果你能说明你是在什么场景下，为什么要这样做，这样做报的具体错误，可能别人会更好的回答你这个问题
> > > 
> > > 
> > > 就是我们内部写的一个服务，平时内部有个fireman 的东西在正常调用，就发现了这个错误。应该说是 不经意发现的。还望大神指导下，谢谢。
> > 
> > 
> > 首先我理解这是 Http 协议层面上导致的一个错误。按照您提供的Http Accept 的内容 ，我们写了一个测试，提示的异常信息是：
> > ```java
> > Resolved [org.springframework.web.HttpMediaTypeNotAcceptableException: Could not parse 'Accept' header [text/plain, text/plain, text/plain, text/plain, text/plain, text/plain, text/plain, text/plain, text/plain, text/plain, text/plain, text/plain, text/plain, text/plain, text/plain, text/plain, text/plain, text/plain, text/plain, text/plain, text/plain, text/plain, text/plain, text/plain, text/plain, text/plain, text/plain, text/plain, text/plain, text/plain, text/plain, text/plain, text/plain, text/plain, text/plain, text/plain, text/plain, text/plain, text/plain, text/plain, text/plain, text/plain, text/plain, text/plain, text/plain, text/plain, text/plain, application/json, application/*+json, /, /, /, /, /, /, /, /, /, /, /, /, /, /, /, /, /, /, /, /, /, /, /, /, /, /, /, /, /, /, /, /, /, /, /, /, /, /, /, /, /, /, /, /, /, /, /]: 
> > Invalid mime type "/": does not contain subtype after '/']
> > 2019-01-04 10:00:08.999  WARN [sc-migrate-eureka-consumer,ba0cdcfaddfe7383,ba0cdcfaddfe7383,false] 25475 --- [io-40051-exec-5] .w.s.m.s.DefaultHandlerExceptionResolver :
> > ```
> > 
> > 
> > 所以这个跟是否是使用Spring Cloud Alibaba 后服务调用异常是没有关系的。
> > 另外，根据您提供的这个Http Accpet的内容信息，看上去也是一个不正常的Accept,如果你们非要避免这种不规则的Accept,那你们就应该增加一个类似Filter 的东西，对 Header 中内容的合法性做一个正确性校验。

postman 调用设置如下：
![image](https://user-images.githubusercontent.com/6268253/50735122-4dfaab80-11e4-11e9-8c3d-e764fa1ee825.png)

Java 端就简单写了个RestController 如下：
![image](https://user-images.githubusercontent.com/6268253/50735135-6bc81080-11e4-11e9-8694-656c04079484.png)

然后用postman 调用后报错如下：
> 感谢回复。我用postman 调用报错堆栈信息如下：
> ![image](https://user-images.githubusercontent.com/6268253/50735089-e80e2400-11e3-11e9-9f55-54558eab40da.png)
