### ISSUE TITLE
配置项无法自动刷新

### ISSUE THREAD

**Issue by zhangchuanben** [spring-cloud-incubator/spring-cloud-alibaba#240]
我按照wiki尝试了一下nacos config但是配置项没有刷新。
我的操作步骤如下：

1. 先创创建好配置项，然后通过一个rest接口试了一下，配置项是可以获取的

2.然后我修改了一个配置项的值，重新刷新rest接口，配置项没有改变，起初我以为是因为我通过nacos客户端修改造成的，我又用api做了一下修改：
` curl -X POST "http://127.0.0.1:8848/nacos/v1/cs/configs?dataId=microservice-ali-nacos-config.properties&group=DEFAULT_GROUP&content=user.id=1%0Auser.name=james%0Auser.age=17"
`重新加载rest接口发现配置项仍没更新，首先声明我的controller有加@RefreshScope注解
代码如下：
`
@SpringBootApplication
@EnableDiscoveryClient
public class SpringCloudNacosConfig {
    public static void main(String[] args) {
        ConfigurableApplicationContext context = SpringApplication.run(SpringCloudNacosConfig.class, args);
        ConfigurableEnvironment env = context.getEnvironment();
        System.out.println(env.getProperty("user.name"));
        System.out.println(env.getProperty("user.age"));
    }

    @RestController
    @RefreshScope
    class EchoController {
        @Value("${user.name}")
        String userName;

        @Value("${user.age}")
        int age;
        @RequestMapping(value = "/echo/{string}", method = RequestMethod.GET)
        public String echo(@PathVariable String string) {
            return string + ";user.name="+userName+";user.age="+age;
        }
    }

}
`
bootstrap.properties配置项如下：
`spring.cloud.nacos.config.server-addr=127.0.0.1:8848
spring.cloud.nacos.discovery.server-addr=127.0.0.1:8848
spring.application.name=microservice-ali-nacos-config`

application.properties配置如下：
`server.port=18084
management.endpoints.web.exposure.include=*
spring.cloud.nacos.config.file-extension=properties
spring.cloud.nacos.config.group=DEFAULT_GROUP
`

maven 依赖的阿里版本
`<dependency>
                <groupId>org.springframework.cloud</groupId>
                <artifactId>spring-cloud-alibaba-dependencies</artifactId>
                <version>0.2.1.RELEASE</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>`
cloud版本：
`Finchley.SR2`
boot版本：
2.1.1.RELEASE
请问这是一个bug呢？还是我的操作有问题？

**Comment by fangjian0423** [comment]
Spring Boot 2.1.X 本身与 Finchley不兼容，使用 Greenwich 即可解决。

参考：https://github.com/spring-cloud-incubator/spring-cloud-alibaba/issues/105

**Comment by zhangchuanben** [comment]
thanks,确实是spring版本的问题，我将boot的版本改为了2.0.7.RELEASE，cloud版本保持Finchley.SR2也是可用的。

**Comment by juncheno** [comment]
<parent>
     <groupId>org.springframework.cloud</groupId>
        <artifactId>spring-cloud-build</artifactId>
        <version>2.1.2.RELEASE</version>
        <relativePath/>
       
    
</parent>

**Comment by littlechaser** [comment]
试试

**Comment by littlechaser** [comment]
试试能不能解决
https://gitee.com/the-best-riven/spring-value-auto-refresh-spring-cloud-starter
