### ISSUE TITLE
发现了nacos banner的一个bug，修改端口banner显示错误

### ISSUE THREAD

**Issue by zhangchuanben** [spring-cloud-incubator/spring-cloud-alibaba#241]
当我把端口修改为8849时，发现启动时banner仍然显示8848
查看了nacos-core下的banner.txt文件
`

         ,--.
       ,--.'|
   ,--,:  : |                                           Nacos 0.7.0
,`--.'`|  ' :                       ,---.               Running in ${nacos.mode} mode
|   :  :  | |                      '   ,'\   .--.--.    Port: 8848
:   |   \ | :  ,--.--.     ,---.  /   /   | /  /    '   Pid: ${pid}
|   : '  '; | /       \   /     \.   ; ,. :|  :  /`./   Console: http://${nacos.local.ip}:8848/nacos/index.html
'   ' ;.    ;.--.  .-. | /    / ''   | |: :|  :  ;_
|   | | \   | \__\/: . ..    ' / '   | .; : \  \    `.      https://nacos.io
'   : |  ; .' ," .--.; |'   ; :__|   :    |  `----.   \
|   | '`--'  /  /  ,.  |'   | '.'|\   \  /  /  /`--'  /
'   : |     ;  :   .'   \   :    : `----'  '--'.     /
;   |.'     |  ,     .-./\   \  /            `--'---'
'---'        `--`---'     `----'

`
这里把端口写死了，应该用占位符动态获取

**Comment by flystar32** [comment]
收到 ，已经在这里反馈 https://github.com/alibaba/nacos/issues/577

**Comment by zhangchuanben** [comment]
谢谢，下次我会用英文反馈的

**Comment by flystar32** [comment]
👍，那就直接在 Nacos 仓库跟踪这个 issue，这边这个我先关闭了
