### ISSUE TITLE
管理的aliyun-java-sdk-core版本较低，导致阿里短信服务发送失败

### ISSUE THREAD

**Issue by ly641921791** [spring-cloud-incubator/spring-cloud-alibaba#246]
0.2.0 released定义的依赖管理中，aliyun-java-sdk-core版本为4.0.1，这个版本阿里的短信服务发不通，官网文档的Demo中，目前使用的版本是4.0.6，测试可用。

----- Translated by Google

0.2.0 released definition of dependency management, aliyun-java-sdk-core version is 4.0.1, this version of Ali's SMS service does not work, the official website document Demo, the current version is 4.0.6, the test is available.

**Comment by pbting** [comment]
> 0.2.0 released定义的依赖管理中，aliyun-java-sdk-core版本为4.0.1，这个版本阿里的短信服务发不通，官网文档的Demo中，目前使用的版本是4.0.6，测试可用。
> 
> ----- Translated by Google
> 
> 0.2.0 released definition of dependency management, aliyun-java-sdk-core version is 4.0.1, this version of Ali's SMS service does not work, the official website document Demo, the current version is 4.0.6, the test is available.

这个确实是有不兼容的问题，我们也发现了，正在开发的 sms starter 会解决这个问题。
