### ISSUE TITLE
使用0.2.1的nacos-discovery报错问题

### ISSUE THREAD

**Issue by zhengjf1988** [spring-cloud-incubator/spring-cloud-alibaba#247]
![image](https://user-images.githubusercontent.com/16054422/50808142-2ae11080-1338-11e9-9dce-f8533130bd1f.png)
最开始报这个错误，后来调查一下发现是和spring cloud版本冲突。
经过指导，在pom文件中配置了

        <dependency>
            <groupId>org.springframework.cloud</groupId>
            <artifactId>spring-cloud-alibaba-dependencies</artifactId>
            <version>0.2.1.RELEASE</version>
            <type>pom</type>
            <scope>import</scope>
        </dependency>

打开看了一下指向的spring-cloud最终版本是2.0.4.RELEASE
然后就Ok了

**Comment by flystar32** [comment]
你指的是 spring-cloud-build 的版本是 2.0.4.RLEASE 吗？
关于版本的问题，可以查看这个  https://github.com/spring-cloud-incubator/spring-cloud-alibaba/wiki/%E7%89%88%E6%9C%AC%E8%AF%B4%E6%98%8E
