### ISSUE TITLE
把配置移到nacos后启动服务的时候只扫描了部分bean

### ISSUE THREAD

**Issue by yilichun12** [spring-cloud-incubator/spring-cloud-alibaba#249]
把配置移到nacos后启动服务的时候只扫描了部分bean，不知道是怎么回事
<dependency>
            <groupId>org.springframework.cloud</groupId>
            <artifactId>spring-cloud-starter-alibaba-nacos-config</artifactId>
            <version>0.1.1.RELEASE</version>
        </dependency>

**Comment by yilichun12** [comment]
![image](https://user-images.githubusercontent.com/9932124/50884600-49bdd080-1426-11e9-9800-98b5eade96cc.png)
发现是应用扫描了三次，最后一次为nacos的扫描替换了之前的ApplicationContext，导致ApplicationContext不存在之前扫描的内容

**Comment by flystar32** [comment]
Nacos config 的工作原理是在添加监听之后会立即 publis 一个 refresh event 事件。

但是从 spring 的角度来看， refresh event 事件 只对 @RefreshScope 和 @ConfigurationProperties 这两个注解的类有效。

所以不大确定这里的，只扫描了部分Bean 具体指的是什么现象，可以详细描述复现步骤或者提供最小复现包吗？
