### ISSUE TITLE
再问下nacos服务之间拉取配置的时候是否有加密

### ISSUE THREAD

**Issue by yilichun12** [spring-cloud-incubator/spring-cloud-alibaba#253]
再问下nacos服务之间拉取配置的时候是否有加密，就是服务读取配置的时候是否有加密

**Comment by flystar32** [comment]
现在的版本目前还没有相关配置，可以给 nacos 项目提一个 issue

----------------------
the latest version of  Nacos hasn't support this feature, you can add a issue to https://github.com/alibaba/Nacos

**Comment by yilichun12** [comment]
ok
