### ISSUE TITLE
No retry consumption, no matter whether you set up broker control or client control : rocketmq

### ISSUE THREAD

**Issue by XCXCXCXCX** [spring-cloud-incubator/spring-cloud-alibaba#256]
When used according to the content of the document, the test found that there is no automatic retry. Do I need to implement the retry part of the client on the client side? Or is it only for transactional messages, not automatically retrying?

@StreamListener("input")
public void receiveTransactionalMsg(Message message) {
RocketMQMessageHeaderAccessor headerAccessor = new RocketMQMessageHeaderAccessor(message);
Acknowledgement acknowledgement = headerAccessor.getAcknowledgement(message);

//my logic
if(success){
acknowledgement.setConsumeConcurrentlyStatus(ConsumeConcurrentlyStatus.RECONSUME_LATER);
}else{
acknowledgement.setConsumeConcurrentlyStatus(ConsumeConcurrentlyStatus.CONSUME_SUCCESS);
}

}

**Comment by XCXCXCXCX** [comment]
No, this is my application.properties

`spring.cloud.stream.default-binder=rocketmq

spring.cloud.stream.bindings.output.destination=TransactionTopic2
spring.cloud.stream.bindings.output.content-type=application/json
spring.cloud.stream.rocketmq.bindings.output.producer.transactional=true
spring.cloud.stream.rocketmq.bindings.output.producer.executer=com.spring.cloud.alibaba.rocketmq.example.service.impl.transaction.LocalTransferTransactionExecuter
spring.cloud.stream.rocketmq.bindings.output.producer.transaction-check-listener=com.spring.cloud.alibaba.rocketmq.example.service.impl.transaction.TransferTransactionCheckListener
`
`RocketMQConsumerProperties` says that
`
      /**
	 * if orderly is true, using {@link MessageListenerOrderly} else if orderly if false,
	 * using {@link MessageListenerConcurrently}
	 */
	private Boolean orderly = false;
`

so I think I use the  {@link MessageListenerConcurrently}, but I don't know why it didn't take effect.

**Comment by fangjian0423** [comment]
@XCXCXCXCX Please make sure broker and Name Server are healthy. It works well in my local machine.

**Comment by fangjian0423** [comment]
@XCXCXCXCX 

RocketMQ Binder just release first version. It is a little simple and maybe exists some small bugs. 

We will support more features in the future and integration with rocketmq-spring-boot.

Very pleasure to receive your issue.
