### ISSUE TITLE
support dataIds to ACM 

### ISSUE THREAD

**Issue by fudali113** [spring-cloud-incubator/spring-cloud-alibaba#271]
Do we have this plan?

**Comment by pbting** [comment]
> Do we have this plan?

Can you give a more detailed explanation?

**Comment by fudali113** [comment]
> > Do we have this plan?
> 
> Can you give a more detailed explanation?

can i use nacos-config-starter in aliyun ACM ?

**Comment by flystar32** [comment]
yes, The support has already done, Refer to this https://help.aliyun.com/document_detail/94708.html .
