### ISSUE TITLE
UnsupportedOperationException:null for Spring Cloud Sentienl for Spring Cloud Edgware

### ISSUE THREAD

**Issue by HaojunRen** [spring-cloud-incubator/spring-cloud-alibaba#272]
When I add @SentinelRestTemplate for a method, it will be failed for throwing out UnsupportedOperationException:null. BUT it works fine in Spring Cloud Finchley

**Comment by HaojunRen** [comment]
@Bean
    @LoadBalanced
    @SentinelRestTemplate(blockHandler = "handleException", blockHandlerClass = MySentinelExceptionHandler.class)
    public RestTemplate restTemplate() {
        RestTemplate restTemplate = new RestTemplate();
        return restTemplate;
    }

**Comment by HaojunRen** [comment]
public class MySentinelExceptionHandler {
    private static final Logger LOG = LoggerFactory.getLogger(MySentinelExceptionHandler.class);

    public static void handleException(BlockException e) {
        LOG.error("Sentinel exception causes", e);
    }
}

**Comment by fangjian0423** [comment]
I will handle it tomorrow!

**Comment by fangjian0423** [comment]
It works well, either in [nacos-consumer-example](https://github.com/spring-cloud-incubator/spring-cloud-alibaba/tree/1.x/spring-cloud-alibaba-examples/nacos-example/nacos-discovery-example/nacos-discovery-consumer-example) or [sentinel-core-example](https://github.com/spring-cloud-incubator/spring-cloud-alibaba/tree/1.x/spring-cloud-alibaba-examples/sentinel-example/sentinel-core-example).

Could you provide some more detail information?

**Comment by HaojunRen** [comment]
My problem, close it
