### ISSUE TITLE
Spring Cloud Gateway + nacos-discovery 如何配置uri路由到指定的微服务

### ISSUE THREAD

**Issue by artsn** [spring-cloud-incubator/spring-cloud-alibaba#274]
运行环境：
springboot：2.0.7.RELEASE
springcloud：Finchley.SR2
spring-cloud-alibaba：0.2.1.RELEASE

- id: oss-server
        uri: http://192.168.2.211:7070
        predicates:
        - Path=/api/oss/**
        filters:
        - StripPrefix=1
网关配置参数uri为 http:请求地址值时   程序能够正常的注册到nacos-server，并能够正常从配置中心加载配置信息。
当uri为  lb://demo-service  注册中心的某个服务名时，程序出错：
io.netty.handler.ssl.NotSslRecordException: not an SSL/TLS record: 485454502f312e3120343030200d0a5472616e736665722d456e636f64696e673a206368756e6b65640d0a4.......

请指教一下，如何配置路由的目标为注册中心的某个微服务

**Comment by fangjian0423** [comment]
Hi @artsn .

@pig4cloud  create an example about [nacos spring cloud gateway example](https://github.com/spring-cloud-incubator/spring-cloud-alibaba/tree/master/spring-cloud-alibaba-examples/nacos-example/nacos-gateway-example)
