### ISSUE TITLE
I used spring-cloud-alibaba-nacos-register, can I CONFIG health-check in client ?

### ISSUE THREAD

**Issue by mosence** [spring-cloud-incubator/spring-cloud-alibaba#283]
I used the HeartbeatEvent (org.springframework.cloud.client.discovery.event.HeartbeatEvent) in Spring Cloud Neflix ,
When I used the spring-cloud-alibaba-nacos-register, it DON'T work!

**Comment by flystar32** [comment]
Not supported this feature yet，maybe we can add it in next version.

**Comment by cjbi** [comment]
在 2019年1月31日，下午4:37，xiaojing <notifications@github.com<mailto:notifications@github.com>> 写道：


Not supported this feature yet，maybe we can add it in next version.

**Comment by mosence** [comment]
Thanks.
