### ISSUE TITLE
nacos 服务实例权重不生效

### ISSUE THREAD

**Issue by xyydcoo** [spring-cloud-incubator/spring-cloud-alibaba#290]
spring cloud version: Finchley.RELEASE
spring boot version:2.0.4.RELEASE
spring-cloud-starter-alibaba-nacos-discovery version: 0.2.1.RELEASE
spring-cloud-starter-alibaba-nacos-config version: 0.2.1.RELEASE
consumer code:
![consumer](https://user-images.githubusercontent.com/29936988/51309272-f92a2100-1a7e-11e9-8cb5-c7e0d1995aae.png)
provider code:
![provider](https://user-images.githubusercontent.com/29936988/51309404-43130700-1a7f-11e9-818a-b32f5ac18370.png)
nacos console:
![nacos](https://user-images.githubusercontent.com/29936988/51309314-1101a500-1a7f-11e9-9db5-404e8433fb5b.png)
log:
![log](https://user-images.githubusercontent.com/29936988/51309330-16f78600-1a7f-11e9-8645-da5289979919.png)

**Comment by fangjian0423** [comment]
Duplicate in https://github.com/alibaba/nacos/issues/522.

You could implement `IRule` to choose right server base on `NacosServer#instance#weight`

We will consider to provider an `IRule` in `spring-cloud-starter-alibaba-nacos-discovery` module next version.
