### ISSUE TITLE
Is the better to enable sentinel with EnableCircuitBreaker?

### ISSUE THREAD

**Issue by mosence** [spring-cloud-incubator/spring-cloud-alibaba#294]
I found spring-cloud-alibaba-sentinel 's spring.factories config 
```
org.springframework.boot.autoconfigure.EnableAutoConfiguration=\
org.springframework.cloud.alibaba.sentinel.SentinelWebAutoConfiguration,\
org.springframework.cloud.alibaba.sentinel.endpoint.SentinelEndpointAutoConfiguration,\
org.springframework.cloud.alibaba.sentinel.custom.SentinelAutoConfiguration,\
org.springframework.cloud.alibaba.sentinel.feign.SentinelFeignAutoConfiguration
```
Is this the better replace "@EnableAutoConfiguration" to "@EnableCircuitBreaker"?

**Comment by fangjian0423** [comment]
Hi @pig4cloud 

`@SpringCloudApplication` can also trigger SentinelAutoConfiguration in `spring.factories`.

Can you write some more details about what problems you encounter?

**Comment by pig4cloud** [comment]
thx @fangjian0423 
As the friend above said @EnableCircuitBreaker support is not particularly good
When I use it @SpringCloudApplication, I am prompted with this error. This demo is very simple
```
java.lang.IllegalStateException: Annotation @EnableCircuitBreaker found, but there are no implementations. Did you forget to include a starter?
```
pom
```
        <dependency>
            <groupId>org.springframework.cloud</groupId>
            <artifactId>spring-cloud-starter-alibaba-nacos-discovery</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.cloud</groupId>
            <artifactId>spring-cloud-starter-alibaba-sentinel</artifactId>
        </dependency>
```
Then I looked at the source code, about the hystrix  configuration need spring.factories EnableCircuitBreaker

![image](https://user-images.githubusercontent.com/12409311/51375563-2f2fd980-1b41-11e9-875c-a4fc10f03d23.png)

**Comment by pig4cloud** [comment]
I am really embarrassed, forget to declare my version.
```
spring cloud Finchley SR2
spring boot 2.1.2 RELEASE
spring-cloud-alibaba-dependencies 0.2.0.RELEASE
```

**Comment by fangjian0423** [comment]
Thank you for your report @pig4cloud.

It is really a problem and this exception throw by `SpringFactoryImportSelector`, but `@EnableCircuitBreaker` annotation doesn't really do anything, it's just an identifier to indicate 
 the auto-configuration classes of `spring.factories`.

I will fix it next version.  

You have a small mistake in your version info.

Spring Cloud Finchley SR2 is incompatible with Spring Boot 2.1.2 RELEASE.  You could see this issue for more details: https://github.com/spring-cloud-incubator/spring-cloud-alibaba/issues/105

**Comment by pig4cloud** [comment]
. I will use spring boot 2.0.8  or  spring cloud greenwich , Can I try greenwich?  
Thank you for your help

**Comment by fangjian0423** [comment]
Spring Cloud Greenwich is not release now. 

Maybe Finchley is better. 

If your project depend on Spring Boot 2.1.X,  you can use Greenwich and Spring Boot 2.1.X. I think it is also ok.

**Comment by pig4cloud** [comment]
Get. I am going to try to fix the problem above, maybe pull request 。 
Going to move bricks first 。 very thx！！

**Comment by fangjian0423** [comment]
Very welcome to create pull request to fix it.
