### ISSUE TITLE
The problem of Nacos Discovery namespace isolation

### ISSUE THREAD

**Issue by zzbbll** [spring-cloud-incubator/spring-cloud-alibaba#295]
nacos-discovery命名空间隔离问题
hello，我看文档里有写spring.cloud.nacos.discovery.namespace 有隔离环境的作用，但是我试了一下没有隔离作用呀  还需要什么配置吗

**Comment by fangjian0423** [comment]
It is supported in nacos-client 0.8.0 version, you could see it in nacos release page https://github.com/alibaba/nacos/releases.

The nacos-client version in Spring Cloud Alibaba Nacos Discovery Starter is 0.6.2 .

We will using 0.8.0 version in starter next version.

**Comment by flystar32** [comment]
I think we ca update nacos client version right now, but still need to wait next release window to release it.
