### ISSUE TITLE
The namespace property of NacosDataSource is not support in Sentinel module

### ISSUE THREAD

**Issue by 18980808191** [spring-cloud-incubator/spring-cloud-alibaba#296]
spring.cloud.sentinel.datasource.ds1.nacos.namespace=ff335849-2ace-4414-9068-e45d02d83f05

配置无效，仍然读取的public的数据。

**Comment by fangjian0423** [comment]
Hi  请问是要使用 Nacos 连接 ACM 拿规则数据吗？

目前 Sentinel Starter 使用 Nacos namespace 还有点问题，下个版本会修复。现在可以使用 Sentinel 原生的 SPI 构造 DataSource。 

https://github.com/alibaba/Sentinel/wiki/%E5%8A%A8%E6%80%81%E8%A7%84%E5%88%99%E6%89%A9%E5%B1%95#%E6%B3%A8%E5%86%8C%E6%95%B0%E6%8D%AE%E6%BA%90

**Comment by 18980808191** [comment]
> Hi 请问是要使用 Nacos 连接 ACM 拿规则数据吗？
> 
> 目前 Sentinel Starter 使用 Nacos namespace 还有点问题，下个版本会修复。不过你可以使用 Sentinel 原生的 SPI 构造 DataSource。
> 
> https://github.com/alibaba/Sentinel/wiki/%E5%8A%A8%E6%80%81%E8%A7%84%E5%88%99%E6%89%A9%E5%B1%95#%E6%B3%A8%E5%86%8C%E6%95%B0%E6%8D%AE%E6%BA%90

想实现从nacos读取sentinel限流规则，读取源代码，发现个问题，NacosDataSourceFactoryBean类中的@Override
	public NacosDataSource getObject() throws Exception {
		if (!StringUtils.isEmpty(System.getProperties()
				.getProperty(SentinelDataSourceConstants.NACOS_DATASOURCE_ENDPOINT))) {
			Properties properties = new Properties();
			properties.setProperty(PropertyKeyConst.ACCESS_KEY, this.accessKey);
			properties.setProperty(PropertyKeyConst.SERVER_ADDR, this.secretKey);
			properties.setProperty(PropertyKeyConst.ENDPOINT, this.endpoint);
			properties.setProperty(PropertyKeyConst.NAMESPACE, this.namespace);
			return new NacosDataSource(properties, groupId, dataId, converter);
		}
		return new NacosDataSource(serverAddr, groupId, dataId, converter);
	}

这个方法中System.getProperties()
				.getProperty(SentinelDataSourceConstants.NACOS_DATASOURCE_ENDPOINT))始终是null,因此无法读取到namespace.
PS：SentinelDataSourceConstants.NACOS_DATASOURCE_ENDPOINT定义的作用是什么呢？

我修改成这样namespace就生效
@Override
	public NacosDataSource getObject() throws Exception {
		Properties properties = new Properties();
		properties.setProperty(PropertyKeyConst.SERVER_ADDR, this.serverAddr);
		if (!StringUtils.isEmpty(this.namespace)) {
			properties.setProperty(PropertyKeyConst.NAMESPACE, this.namespace);
		}
		if (!StringUtils		.isEmpty(System.getProperties().getProperty(SentinelDataSourceConstants.NACOS_DATASOURCE_ENDPOINT))) {
			properties.setProperty(PropertyKeyConst.ACCESS_KEY, this.accessKey);
			properties.setProperty(PropertyKeyConst.SERVER_ADDR, this.secretKey);
			properties.setProperty(PropertyKeyConst.ENDPOINT, this.endpoint);
		}
		return new NacosDataSource(properties, groupId, dataId, converter);
	}

**Comment by fangjian0423** [comment]
@18980808191 

`SentinelDataSourceConstants.NACOS_DATASOURCE_ENDPOINT` 这段逻辑是商业化的逻辑，下个版本会去掉。

去掉之后如果配置了 `serverAddr`，那么会根据 `NacosDataSource(final String serverAddr, final String groupId, final String dataId, Converter<String, T> parser)` 构造数据源。

否则根据 `public NacosDataSource(final Properties properties, final String groupId, final String dataId, Converter<String, T> parser)` 构造数据源。

**Comment by 18980808191** [comment]
@fangjian0423
直接用NacosDataSource(final Properties properties, final String groupId, final String dataId, Converter<String, T> parser) 构造函数构造数据源最好。
应该是判断有namespace配置就用NacosDataSource(final Properties properties, final String groupId, final String dataId, Converter<String, T> parser) 构造函数构造数据源，不能根据serverAddr判断，不然namespace又不生效。
