### ISSUE TITLE
sentinel控制台如何移除机器

### ISSUE THREAD

**Issue by naturalyui** [spring-cloud-incubator/spring-cloud-alibaba#304]
另外：https://github.com/spring-cloud-incubator/spring-cloud-alibaba/blob/master/spring-cloud-alibaba-examples/sentinel-example/sentinel-core-example/readme-zh.md中
![image](https://user-images.githubusercontent.com/26024263/51468973-1fb3c900-1dab-11e9-8b93-c8b69daabc2f.png)
是不是拼错了

**Comment by fangjian0423** [comment]
感谢提出文档上的错误。 

Sentinel 目前不支持控制台移除机器，可以自行进行改造或在 [Sentinel Issue](https://github.com/alibaba/Sentinel/issues) 上提出.

**Comment by naturalyui** [comment]
好的十分感谢
