### ISSUE TITLE
OSS SMS 等阿里云产品集成的疑惑

### ISSUE THREAD

**Issue by cn-src** [spring-cloud-incubator/spring-cloud-alibaba#311]
像 OSS SMS 等阿里云产品，为什么不是提供单独的 spring boot 的集成项目，而是要放到 spring-cloud-alibaba 这个项目中？

目前也没太看出来这些集成与微服务有直接的挂钩，与基本的 spring boot 集成好像也没什么区别。

另起一个 aliyun-spring-boot 项目不是应该更加合理么？毕竟用这些不一定就需要用微服务。

**Comment by flystar32** [comment]
非常好的一个问题！

确实如你所说，阿里云的很多产品，比如 OSS、SMS、SchedulerX，还有即将接入的 VMS。这些都是单纯的 Spring Boot Starter， 和 Spring Cloud 其实没有太大关系。

我们将他们也放在此工程中有两个考虑：

- 维护一个品牌的统一性，所有的阿里云产品在 Spring Boot/Spring Cloud 的集成都在 Spring Cloud Alibaba 这个统一的工程中，Spring Cloud Alibaba 就是阿里云 SDK 在 Spring 生态的统一品牌。
- 我们也参考过一些友商的做法，如 GCP 和 AWS 等，他们的产品中也将一些单纯的 Spring Boot Starter 放在 Spring-Cloud-GCP 和 Spring-Cloud-AWS 中，所以这也算是一个国际惯例。

非常感谢你的提问，我们会在文档中特别说明，这些 starter 在单纯的 Spring Boot 环境也能使用。

阿里云产品在 Spring 生态的集成处于起步阶段，如果你有兴趣，我们非常欢迎您来一起共同建设。
