### ISSUE TITLE
nacos config refresh not work 

### ISSUE THREAD

**Issue by sofior** [spring-cloud-incubator/spring-cloud-alibaba#312]
spring boot version 2.1.2.RELEASE 
spring cloud alibaba version 0.2.1.RELEASE

use spring boot 2.0.6.RELEASE is ok

**Comment by fangjian0423** [comment]
Spring Boot 2.1.X is not incompatible with Spring Cloud Finchley, you could use Spring Cloud Greenwich.

duplicate in #105
