### ISSUE TITLE
chiguateam

### ISSUE THREAD

**Issue by zhoulibo1988** [spring-cloud-incubator/spring-cloud-alibaba#313]
* 组织：吃瓜团队
* 地点：中国深圳
* 联系方式：zhoulibo_vip@163.com
* 组件：Nacos、Sentinel
* 场景：服务发现、配置管理、限流降级
*官网：https://www.chiguateam.com/

**Comment by fangjian0423** [comment]
Thank you for your participation.

I found you have submitted comment in https://github.com/spring-cloud-incubator/spring-cloud-alibaba/issues/301. 

So I close this issue.
