### ISSUE TITLE
Nacos Discovery namespace is not support isolate the data

### ISSUE THREAD

**Issue by xuxiao1987** [spring-cloud-incubator/spring-cloud-alibaba#317]
nacos 版本0.8.0 release
spring-cloud-starter-alibaba-nacos-discovery 版本0.2.1.RELEASE

spring: 
  cloud: 
    nacos:
      discovery: 
        namespace: 5773b681-102f-43e0-809e-b5f952388840
        server-addr: XXXX
      config: 
        namespace: 5773b681-102f-43e0-809e-b5f952388840
        group: DEFAULT_GROUP
        file-extension: properties
        server-addr: XXXX

服务还是注册到了public的namespace？

**Comment by flystar32** [comment]
nacos-client version art still 0.6.2, will support this feature after update to 0.8.
