### ISSUE TITLE
MQ这块文档同步，顺序，延时这些特性写的不是很详细，需要翻看代码才行，希望补充一下

### ISSUE THREAD

**Issue by halower** [spring-cloud-incubator/spring-cloud-alibaba#323]
事务消息Demo的写法貌似过时，需要更新一下
`
public class CustomTransactionListener implements TransactionListener {
    @Override
    public LocalTransactionState executeLocalTransaction(Message msg, Object arg) {
        if ("1".equals(msg.getUserProperty("test"))) {
            System.out.println(new String(msg.getBody()) + " 回滚");
            return LocalTransactionState.ROLLBACK_MESSAGE;
        }
        System.out.println(new String(msg.getBody()) + " 提交");
        return LocalTransactionState.COMMIT_MESSAGE;
    }

    @Override
    public LocalTransactionState checkLocalTransaction(MessageExt msg) {
        System.out.println("事务检查侦听器: " + new String(msg.getBody()));
        return LocalTransactionState.COMMIT_MESSAGE;
    }
}

bindings:
   output2:
     producer:
        transaction-listener: xxx.CustomTransactionListener
`

**Comment by fangjian0423** [comment]
感谢使用 RocketMQ Binder。

Thank you for using RocketMQ Binder。

我们正在整合 [RocketMQ Spring Boot](https://github.com/apache/rocketmq-spring) 到 Binder 中，整合之后文档内容会发生比较大的变化，然后会补充具体的文档。

Now RocketMQ Binder is integration with [RocketMQ Spring Boot](https://github.com/apache/rocketmq-spring). After the integration, the content of the documents will change a lot, and then the specific documentation will be added.
