### ISSUE TITLE
nacos集群数目如何增加

### ISSUE THREAD

**Issue by xuyixun21** [spring-cloud-incubator/spring-cloud-alibaba#332]
我使用nacos时，在同一个ip的不同端口启动了2个相同服务，nacos服务列表中显示该服务为1个集群，2个实例，这没什么问题，如果要构造该服务下有2个或者多个集群，我该如何部署服务

**Comment by xuyixun21** [comment]
我照这个搭了，在同个IP下的不同端口启动了相同服务，实现了该服务下的一个集群下运行多个实例；但要实现一个服务的多个集群，该怎么去部署没弄明白，是要各自定义spring.cloud.nacos.discovery.cluster-name这个属性么？

**Comment by flystar32** [comment]
是的，想要注册到哪个集群去，就配置相应的值。
