### ISSUE TITLE
关于Nacos安全

### ISSUE THREAD

**Issue by eacdy** [spring-cloud-incubator/spring-cloud-alibaba#334]
Nacos 0.8描述，说添加了安全认证（账号密码登录），但就目前来看，这个防君子不防小人。
但是应用注册到Nacos上是不需要填写账号密码的。Nacos是提供HTTP接口让人操作Nacos中的数据的，这意味着，只要构造相应参数，并发送请求，完全可以绕开账号密码登录的机制，去搞Nacos数据。
建议改进。

**Comment by flystar32** [comment]
是的，我们也认为应该在 Nacos Client 到 Nacos Server 端的链路也需要加密，我将这 Issue 转到到 Nacos 项目中。

**Comment by cnhans** [comment]
这个加密机制应该有nacos内部实现即可，在接口上配置不合适。
