### ISSUE TITLE
How to Use Nacos for Gateway loadBalancer

### ISSUE THREAD

**Issue by xuyixun21** [spring-cloud-incubator/spring-cloud-alibaba#336]
springcloud内部服务间的调用通过nacos分配协调以及feign来实现，当外网请求进入服务端的时候，怎么在请求端利用nacos来进行协调分配外界请求的压力，就是请求端怎么通过域名访问能使请求自动分配到nacos的消费端服务的集群上？还是要通过nginx来进行负载均衡分压么，可否绕过nginx实现？

**Comment by flystar32** [comment]
我不大确定是否理解清楚了你的意思，如果没理解错的话，你是想在外部服务调用时候，让外部服务也具备 Nacos 提供的服务发现能力，或许你可以在 Nacos 项目中提一个Issue，我想他们也许有个 DNS-F 可以帮助到你。

**Comment by xuyixun21** [comment]
恩  是的  我就是这个意思
