### ISSUE TITLE
sentinel 与openfeign的注解使用相冲突

### ISSUE THREAD

**Issue by cnhans** [spring-cloud-incubator/spring-cloud-alibaba#341]
我们鼓励使用英文，如果不能直接使用，可以使用翻译软件，您仍旧可以保留中文原文。
We recommend using English. If you are non-native English speaker, you can use the translation software. 

**Which Component**
eg. Nacos Discovery, Sentinel

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**
e.g.  MacOS  、Java8 、 Version 0.2.1.RELEASE

我只要与sentinel搭配使用，然后下面的注解就会失效，
**可以扫描同一个项目内包下面的api**
**无法扫描非项目内的包**
@EnableFeignClients(basePackages = {"net.xxx.**.api"})

        
       <dependency>
            <groupId>org.springframework.cloud</groupId>
            <artifactId>spring-cloud-starter-alibaba-sentinel</artifactId>
        </dependency>

**Comment by cnhans** [comment]
nested exception is java.lang.IllegalStateException: No fallback instance of type class net.blissmall.apiservice.server.api.fallback.EchoServiceFallback found for feign client blissmall-publicservice-provider

**Comment by fangjian0423** [comment]
The error message tells us everything.

Please make sure there is a bean its type is `net.blissmall.apiservice.server.api.fallback.EchoServiceFallback` in spring context and the bean should implement the interface of service `blissmall-publicservice-provider`.

**Comment by cnhans** [comment]
sure 包名相同的情况下，是可以使用的。去除了sentinel，也是正常使用的。

**Comment by fangjian0423** [comment]
Sentinel 跟 Feign 整合的时候并没有对扫描功能做额外处理。

![image](https://user-images.githubusercontent.com/5254035/53215473-c251b700-368b-11e9-91b1-5ab9ef9c9319.png)

![image](https://user-images.githubusercontent.com/5254035/53215501-e57c6680-368b-11e9-8c24-5d35f99e805a.png)

能正常启动，也能正常注入。

**Comment by cnhans** [comment]
已解决，但希望能在框架内部就解决。

**Comment by YangJun1987** [comment]
> 已解决，但希望能在框架内部就解决。

遇到同样的问题，请问如何解决的
