### ISSUE TITLE
use spring-cloud-alibaba-dependencies 0.2.2.BUILD-SNAPSHOT caused project startup failure

### ISSUE THREAD

**Issue by gnehcgnaw** [spring-cloud-incubator/spring-cloud-alibaba#343]
**Which Component**
spring-cloud-alibaba-dependencies 0.2.2.BUILD-SNAPSHOT

**Describe the bug**
use spring-cloud-alibaba-dependencies 0.2.2.BUILD-SNAPSHOT caused project startup failure ,but use spring-cloud-alibaba 0.2.1.RELEASE is no similar problems .

**Screenshots**
![image](https://provider-ser-service.oss-cn-hangzhou.aliyuncs.com/Xnip2019-02-08_20-32-30.png)

**Additional context**
MacOS  、Java8 、 Version 0.2.2.BUILD-SNAPSHOT

**Comment by gnehcgnaw** [comment]
use spring-cloud-alibaba 0.2.1.RELEASE is no similar problems .

**Comment by flystar32** [comment]
can't find any stack trace related to spring-cloud-alibaba, could you please help to provide a demo in github that can reproduce this case?

**Comment by gnehcgnaw** [comment]
https://github.com/gnehcgnaw/demo.git
In fact, it is the simplest demo.

**Comment by 18980808191** [comment]
> https://github.com/gnehcgnaw/demo.git
> In fact, it is the simplest demo.

仍然报错，

org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'org.springframework.context.annotation.internalConfigurationAnnotationProcessor': Initialization of bean failed; nested exception is java.lang.NullPointerException

快发新版本吧。

**Comment by flystar32** [comment]
@gnehcgnaw @18980808191 
Detect that `spring-cloud-alibaba-dependencies` introduce an bom of `dubbo-dependencies-bom` that declare spring_version to 4.3.16 that cause this issue.

**Comment by gnehcgnaw** [comment]
Thank's ,i spent a long time and didn't find the cause of the problem , I have limited ability, I'm really could not contribute .

**Comment by flystar32** [comment]
thank you for your issue, we will fix it soon.
