### ISSUE TITLE
Whether support disabled nacos-config

### ISSUE THREAD

**Issue by l308718280** [spring-cloud-incubator/spring-cloud-alibaba#347]
When running the JUnit test, throw an exception:
![image](https://user-images.githubusercontent.com/29219230/52684615-cee65900-2f81-11e9-806a-c99f7d07a6de.png)

So, I want disabled nacos-config when running the JUnit test

**Comment by flystar32** [comment]
generally get config via nacos config fail won't break application start up, could you provide more information?

**Comment by l308718280** [comment]
> generally get config via nacos config fail won't break application start up, could you provide more information?

When running JUnit，don't want load nacos-config, as cloud config can set：enabled: false

**Comment by mradulpandey** [comment]
Seems like you adding following config in application.yml or application.properties. 

```
spring:
  cloud:
    nacos:
      config:
        server-addr: localhost:8848
```
You should add properties in bootstrap.yml or bootstrap.properties to propertly startart application.

**Comment by flystar32** [comment]
@l308718280  maybe you can try the suggestion @mradulpandey  provided.

**Comment by flystar32** [comment]
will support `spring.cloud.nacos.config.enabled` in next version.

**Comment by l308718280** [comment]
thank you~
