### ISSUE TITLE
spring-cloud-gateway can not start with cloud-nacos-discovery version 0.2.2.BUILD-SNAPSHOT 

### ISSUE THREAD

**Issue by leiruiqi** [spring-cloud-incubator/spring-cloud-alibaba#352]
**Which Component**
Nacos Discovery 0.2.2.BUILD-SNAPSHOT 

**Describe the bug**
spring-cloud-gateway can not startup with cloud-nacos-discovery in version 0.2.2.BUILD-SNAPSHOT 

**Error logs**
No qualifying bean of type 'org.springframework.cloud.alibaba.nacos.NacosDiscoveryProperties' available: expected at least 1 bean which qualifies as autowire candidate

**Additional context**
MacOS  、Java8 、 0.2.2.BUILD-SNAPSHOT

**Comment by leiruiqi** [comment]
There is the example on git .
branch:master
path: spring-cloud-alibaba/spring-cloud-alibaba/spring-cloud-alibaba-examples/nacos-example/nacos-gateway-example/nacos-gateway-discovery-example
try it.

**Comment by SmileTower** [comment]
![image](https://user-images.githubusercontent.com/17945169/52897061-bb99ee80-320a-11e9-8ccb-0d84f9fdf235.png)
NacosDiscoveryProperties bean  from NacosDiscoveryClientAutoConfiguration move  NacosDiscoveryAutoConfiguration

**Comment by flystar32** [comment]
@SmileTower  good suggestion, thank you.
@leiruiqi fixed now.

**Comment by leiruiqi** [comment]
Yes , spring-cloud-gateway can startup with newest Nacos Discovery 0.2.2.BUILD-SNAPSHOT.
But, it not works right，the spring gateway can not discovery any client with nacos.

**Comment by leiruiqi** [comment]
@flystar32 I saw you last commit for spring cloud discovery，it works good with spring-cloud-gateway now . thank you.
