### ISSUE TITLE
org.codehaus.mojo:cobertura-maven-plugin:<unknown>

### ISSUE THREAD

**Issue by pleasecallmeleifeng** [spring-cloud-incubator/spring-cloud-alibaba#369]
In spring-cloud-alibaba project, maven can not import cobertura-maven-plugin , the reason is maven do not know this plugin version.

**Comment by zhendong590** [comment]
I replace plugin on this commit https://github.com/spring-cloud-incubator/spring-cloud-alibaba/commit/87bfb3734a92c65fb1bba231d3fd06a1e4e897f4 ,please use the latest version

**Comment by pleasecallmeleifeng** [comment]
I executed 
`./mvnw -Pspring -Pdocs clean install -U -nsu --batch-mode -Dmaven.test.redirectTestOutputToFile=true -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn`
but problems remain - org.codehaus.mojo:cobertura-maven-plugin:<unknown>

**Comment by pleasecallmeleifeng** [comment]
![image](https://user-images.githubusercontent.com/17005487/53150723-258c0c80-35ec-11e9-83e3-acd0631f4dc8.png)

**Comment by zhendong590** [comment]
i found it ,i will fixed it in next commit

**Comment by pleasecallmeleifeng** [comment]
thanks for you help .
