### ISSUE TITLE
Can't register to Nacos in sca 0.2.1.release

### ISSUE THREAD

**Issue by tanggula1** [spring-cloud-incubator/spring-cloud-alibaba#371]
环境：spirnb boot 2.0.4.RE/2.1.1RE均测试过，  SCA 0.2.1.RE ， NACOS0.8 单机模式
启动应用无异常提示，NACOS控制台无注册服务。
SCA换成0.2.2.BUILD-SNAPSHOT 可以注册，没有任何问题

**Comment by flystar32** [comment]
SCA 0.2.1.RELEASE is not incompatible with Spring Boot 2.1.1.RELEASE.

I just run an example just now,  SCA 0.2.1.RELEASE works well with Spring Boot 2.0.4.RELEASE.

If it still doesn't work in your case, you can provide a Minimal, Complete, and Verifiable example in github.

**Comment by tanggula1** [comment]
I mean: the service cannot be registered to nacos via @EnableDiscoveryClient, not that SCA 0.2.1.RELEASE is not compatible with spirng-boot。
我的意思是：服务无法通过@EnableDiscoveryClient注册到nacos，不是说SCA 0.2.1.RELEASE与spirng-boot 不兼容

**Comment by dengyh2018** [comment]
NACOS0.8 单机模式。
 --- [.naming.updater] com.alibaba.nacos.client.naming          : [] [] [NA] failed to update serviceName: localhost
java.lang.IllegalStateException: failed to req API:/nacos/v1/ns/api/srvIPXT after all servers([127.0.0.1:8848]) tried
请问这是什么问题？

**Comment by yy0** [comment]
https://blog.csdn.net/qq_24842293/article/details/84620066和这个问题应该是一样的。

**Comment by flystar32** [comment]
@tanggula1 could you please help to provide a Minimal, Complete, and Verifiable example ?

**Comment by flystar32** [comment]
@dengyh2018 could you please help to provide a Minimal, Complete, and Verifiable example ? open a new issue is welcome.
