### ISSUE TITLE
Metadata lost

### ISSUE THREAD

**Issue by HaojunRen** [spring-cloud-incubator/spring-cloud-alibaba#38]
That issue will be reproduced in a NEW Nacos Server. At the first time, micro service registers to Nacos Server, sometime some metadata will be lost

**Comment by HaojunRen** [comment]
Fixed in 0.3.0

**Comment by HaojunRen** [comment]
Fixed in 0.3.0

**Comment by HaojunRen** [comment]
It

**Comment by flystar32** [comment]
@HaojunRen  我在这边把这个 issue 关闭了，然后再 Nacos 上建立一条关联的 issue ？
