### ISSUE TITLE
[ Nacos Discvery ] Verify that the service attribute is not empty

### ISSUE THREAD

**Issue by yunzheng1228** [spring-cloud-incubator/spring-cloud-alibaba#391]
nacos discovery not working:

**Which Component**
Nacos Discovery

**Describe the bug**
When the service attribute is not empty, nacos discovery not working.

**Comment by fangjian0423** [comment]
It will log info when serviceId is empty in NacosServiceRegistry#register now.

Maybe throw exception is better.

**Comment by fangjian0423** [comment]
Using warn level log instead of throwing exception.
