### ISSUE TITLE
server failed register in edas

### ISSUE THREAD

**Issue by liangmeiwei** [spring-cloud-incubator/spring-cloud-alibaba#392]
Two situations may cause server register in edas failed
1.springboot version 2.1.X with springcloud version 0.2.1
you should change springboot version to 2.0.X or springcloud version 0.2.2+
2.you forget to configure spring.application.name in application.properties

**Comment by fangjian0423** [comment]
For the 1st Question:

Spring Boot compatibility information.

Release Train | Boot Version
-- | --
Greenwich | 2.1.x
Finchley | 2.0.x
Edgware | 1.5.x
Dalston | 1.5.x

0.2.1.RELEASE is build in Finchley, so you could use Spring Boot 2.0.x

For the 2nd Question:

https://github.com/spring-cloud-incubator/spring-cloud-alibaba/issues/391

**Comment by flystar32** [comment]
when missing spring.application.name , will log 

```
        if (StringUtils.isEmpty(registration.getServiceId())) {
            logger.info("No service to register for nacos client...");
            return;
        }
```
currently the log level is info, will change it to WARN level
