### ISSUE TITLE
Does have a plan to Sentinel integrate with Spring Cloud Gateway

### ISSUE THREAD

**Issue by xuande** [spring-cloud-incubator/spring-cloud-alibaba#393]
If there is no plan in the near future, can you describe the integration idea
> 如果近期没有研发计划,是否可以描述一下集成思路

**Comment by liupengpop** [comment]
Same question

**Comment by fangjian0423** [comment]
Not yet.

Sentinel will integrate Spring Cloud Gateway when sentinel support reactor. 

We can discuss how to integrate in this issue. 

Everyone can share your ideas :blush:.

**Comment by fangjian0423** [comment]
Maybe we can add a filter named `SentinelGatewayFilter` like this:

```
public class SentinelGatewayFilter implements GatewayFilter {
	@Override
	public Mono<Void> filter(ServerWebExchange serverWebExchange,
			GatewayFilterChain gatewayFilterChain) {
		String resource = serverWebExchange.getRequest().getPath().toString();
		Entry entry = null;
		try {
			ContextUtil.enter(resource);
			entry = SphU.entry(resource, EntryType.IN, 1,
					serverWebExchange.getRequest().getQueryParams().values());
			return gatewayFilterChain.filter(serverWebExchange);
		}
		catch (Throwable ex) {
			if (!BlockException.isBlockException(ex)) {
				Tracer.trace(ex);
			}
		}
		finally {
			if (entry != null) {
				entry.exit();
			}
			ContextUtil.exit();
		}
		serverWebExchange.getResponse().setStatusCode(HttpStatus.TOO_MANY_REQUESTS);
		return serverWebExchange.getResponse().setComplete();

	}
}
```

**Comment by qq12157138** [comment]
@fangjian0423 

I don't understand what you mean, how do you do it? This just adds the filter, but the Sentinel Jar package still depends on the servlet.

**Comment by fangjian0423** [comment]
> @fangjian0423
> 
> I don't understand what you mean, how do you do it? This just adds the filter, but the Sentinel Jar package still depends on the servlet.
> 
> Need to be supported in the next version?

This is a easy class, but it could be used for Spring Cloud Gateway.

The better way is to implement `GatewayFilterFactory` and configure something for `SentinelGatewayFilter`.

Sentinel jar includes many modules, including `sentinel-core`, `sentinel-web-servlet`, `sentinel-dashboard`, etc.

`CommonFilter` build in `sentinel-web-servlet` dependency and `SentinelGatewayFilter` don't need it.

SentinelGatewayFilter only need `sentinel-core` and `sentinel-parameter-flow-control` dependency.

**Comment by xuande** [comment]
@fangjian0423 I don't understand how to use this way to implement a Circuit Breaker on the gateway.

**Comment by fangjian0423** [comment]
> @fangjian0423 I don't understand how to use this way to implement a Circuit Breaker on the gateway.

1. You could create a `GatewayFilter` named `SentinelGatewayFilter` and construct a `RouteLocator ` as mentioned above

2. Add `FlowRule` use coding or construct `ReadableDataSource`

```
List<FlowRule> rules = new ArrayList<FlowRule>();
FlowRule rule = new FlowRule();
rule.setResource("/user/list");
rule.setCount(0);
rule.setGrade(RuleConstant.FLOW_GRADE_QPS);
rule.setLimitApp("default");
rules.add(rule);
FlowRuleManager.loadRules(rules);
```

3. visit http://ip:port/user/list to see is it blocked by Sentinel

**Comment by vikenlove** [comment]
@fangjian0423 spring-boot-starter-web is not compatible with spring cloud gateway. so ,when i  use your  code to  create a sentinegatewayfilter ,there is a error ;

`org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'servletRequestListener' defined in class path resource [org/springframework/cloud/alibaba/sentinel/SentinelWebAutoConfiguration.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.springframework.boot.web.servlet.FilterRegistrationBean]: Factory method 'servletRequestListener' threw exception; nested exception is java.lang.NoClassDefFoundError: javax/servlet/Filter`

**Comment by fangjian0423** [comment]
@vikenlove 

Spring Cloud Alibaba Sentinel now is integrates with Spring Web. `SentinelWebAutoConfiguration#servletRequestListener` will build `FilterRegistrationBean` and `FilterRegistrationBean` will build `javax/servlet/Filter`.

But Spring Cloud Gateway based on Spring WebFlux. It is conflict with Spring Web.

So we will add `@ConditionalOnClass(name = "javax.servlet.Filter")` on `SentinelWebAutoConfiguration#servletRequestListener` to resolve it and integrates Sentinel spring webflux in the future.

**Comment by fangjian0423** [comment]
Hi everyone,

Spring Cloud Gateway is not compatible with `org.springframework.boot:spring-boot-starter-web`.

But now Spring Cloud Alibaba Sentinel integrates with `org.springframework.boot:spring-boot-starter-web`.

We will finish it when sentinel support reactive.

**Comment by vikenlove** [comment]
@fangjian0423 i import servelt-api.jar to replace  spring-boot-starter-web

**Comment by fangjian0423** [comment]
> @fangjian0423 i am import servelt-api.jar to replace spring-boot-starter-web

It is works well? You could share how to use `SentinelGatewayFilter` with spring-cloud-alibaba-sentinel.

**Comment by vikenlove** [comment]
@fangjian0423 yes, i has already share it ,[](https://github.com/alibaba/Sentinel/issues/86)

**Comment by sczyh30** [comment]
Hi folks, since 1.5.0 Sentinel has provided reactive integration module for [Reactor](https://github.com/alibaba/Sentinel/tree/master/sentinel-adapter/sentinel-reactor-adapter) and [Spring WebFlux](https://github.com/alibaba/Sentinel/tree/master/sentinel-adapter/sentinel-spring-webflux-adapter). If you're interested in contributing this feature, you can refer to the two modules :)

**Comment by fangjian0423** [comment]
refer https://github.com/alibaba/Sentinel/issues/86
