### ISSUE TITLE
Is there any instructions how to use spring-cloud-alibaba-dubbo?

### ISSUE THREAD

**Issue by litttlefisher** [spring-cloud-incubator/spring-cloud-alibaba#395]
**Which Component**
spring-cloud-alibaba-dubbo

**Describe what problem you have encountered**
我希望能将我的springcloud工程用spring-cloud-alibaba-dubbo来适配dubbo，只不过希望能够提供一份使用说明。
I want to use spring-cloud-alibaba-dubbo to make my project(spring-cloud) to adapt dubbo, but I have no idea how to use it. Please give me some instructions.

**Comment by flystar32** [comment]
@litttlefisher  take a look at here, https://github.com/spring-cloud-incubator/spring-cloud-alibaba/tree/master/spring-cloud-alibaba-examples/spring-cloud-alibaba-dubbo-examples

**Comment by litttlefisher** [comment]
thx.
