### ISSUE TITLE
Does spring-cloud-alibaba-sentinel support cluster flow control? 

### ISSUE THREAD

**Issue by riyueshiwang** [spring-cloud-incubator/spring-cloud-alibaba#397]
我们鼓励使用英文，如果不能直接使用，可以使用翻译软件，您仍旧可以保留中文原文。

**Which Component**
Sentinel

**Describe what problem you have encountered**
Does spring-cloud-alibaba-sentinel support cluster flow control? Is there a demo for reference ?

**Describe what information you have read**
I have read the reference doc of Sentinel

**Comment by fangjian0423** [comment]
Yes. 

0.2.1.RELEASE and 0.1.1.RELEASE add `sentinel-cluster-server-default` & `sentinel-cluster-client-default` dependencies in `spring-cloud-alibaba-sentinel` module.

You could see demo or reference in [Sentinel wiki](https://github.com/alibaba/Sentinel/wiki/%E9%9B%86%E7%BE%A4%E6%B5%81%E6%8E%A7). `spring-cloud-alibaba-sentinel` module do not have some enhancements.

**Comment by riyueshiwang** [comment]
> Yes.
> 
> 0.2.1.RELEASE and 0.1.1.RELEASE add `sentinel-cluster-server-default` & `sentinel-cluster-client-default` dependencies in `spring-cloud-alibaba-sentinel` module.
> 
> You could see demo or reference in [Sentinel wiki](https://github.com/alibaba/Sentinel/wiki/%E9%9B%86%E7%BE%A4%E6%B5%81%E6%8E%A7). `spring-cloud-alibaba-sentinel` module do not have some enhancements.

tks, i will try it.
