### ISSUE TITLE
why i can't find spring-cloud-starter-sentinel's version?

### ISSUE THREAD

**Issue by netboynb** [spring-cloud-incubator/spring-cloud-alibaba#4]
<dependency>
     <groupId>org.springframework.cloud</groupId>
     <artifactId>spring-cloud-starter-sentinel</artifactId>
 </dependency>

the  release  version is ?

**Comment by flystar32** [comment]
spring-cloud-starter-sentinel is still in the initial stage, hasn't publish to maven central repository. you can build it from source code.
