### ISSUE TITLE
java.lang.IllegalStateException: No such extension com.alibaba.dubbo.registry.RegistryFactory by name spring-cloud

### ISSUE THREAD

**Issue by carrot1991** [spring-cloud-incubator/spring-cloud-alibaba#403]
在通过nacos接入dubbo的时候，配置如下，
dubbo.registry.address: spring-cloud://nacos
提示 No such extension com.alibaba.dubbo.registry.RegistryFactory by name spring-cloud

使用0.2.2.SNAPSHOT可以，我发现在0.2.1.RELEASE中并没有这个registry，是不是意味0.2.1.RELEASE还不支持dubbo接入？请问0.2.2.RELEASE什么时候会发布？

**Comment by flystar32** [comment]
yes, `spring-cloud-alibaba-dubbo` is a new module that first release in 0.2.2.RELEASE, it will release in about two weeks.
