### ISSUE TITLE
The activeProfiles of NacosConfigProperties will be override by env active profile

### ISSUE THREAD

**Issue by fangjian0423** [spring-cloud-incubator/spring-cloud-alibaba#404]
**Which Component**

Nacos Config

**Describe what problem you have encountered**

Let's see `NacosConfigProperties#init`:

```
@PostConstruct
public void init() {
    this.activeProfiles = environment.getActiveProfiles();
}
```

Why it will be override by env active profile? 

The activeProfiles of `NacosConfigProperties` is useless.

**Comment by flystar32** [comment]
yes, It's doesn't support to configuration by 'spring.cloud.nacos.config.xxxx', simply get it from `spring.profiles.active`
