### ISSUE TITLE
nacos关闭后，注册在nacos里的服务因为报了deregister错误而挂掉了，有什么办法能保证注册在nacos里的服务继续运行

### ISSUE THREAD

**Issue by xuyixun21** [spring-cloud-incubator/spring-cloud-alibaba#407]
我把nacos关了，注册在nacos里的服务因为报了重新注册deregister报错而挂掉了，有没有什么办法可以去处理服务重连nacos时出现问题报错，保证服务可以继续运行

**Comment by xuyixun21** [comment]
过程:
1、本地启动nacos，然后启动2个服务成功注册到nacos中，没有问题
2、执行nacos的shutdown脚本，关闭nacos后，注册在nacos中的两个服务报了deregister  failed后，服务挂掉了，导致服务接口无法访问

**Comment by flystar32** [comment]
经排查是 Nacos shutdown 脚本的问题，里面的内容 pid=`ps ax | grep -i 'nacos' |grep java | grep -v grep | awk '{print $1}'`  会把所有包含 nacos 关键字的 java 进程都杀掉

**Comment by xuyixun21** [comment]
意思是   用shutdown脚本关闭nacos的时候，注册到nacos的java服务都会被关闭？

**Comment by xuyixun21** [comment]
有什么好办法避免我现在这个问题

**Comment by flystar32** [comment]
这是 Nacos 脚本的问题，详情查看这个 issue https://github.com/alibaba/nacos/issues/874

**Comment by xuyixun21** [comment]
我看了，但里面好像没说解决方案，现在如果我直接kill  nacos进程的话，应该就不会出现服务挂掉的问题吧？

**Comment by flystar32** [comment]
@xuyixun21 可以直接在 Nacos 中对应的 issue 里提一下，这个属于 Nacos 的问题
