### ISSUE TITLE
I want to close Nacos/Discovery when execute tests, it has some exception

### ISSUE THREAD

**Issue by SoyMeng** [spring-cloud-incubator/spring-cloud-alibaba#411]
**Which Component**
Nacos/Discovery

**Describe what problem you have encountered**
Colse Discovery,I try to set config
```
spring.cloud.nacos.discovery = false
```
the results
![tim 20190308103522](https://user-images.githubusercontent.com/6083582/54003676-f1891d80-418d-11e9-8ed1-8723e788f042.png)

Colse Nacos,I try to set config
```
spring.cloud.nacos.config.enabled = false
```
the results
![tim 20190308103445](https://user-images.githubusercontent.com/6083582/54003729-29906080-418e-11e9-9b22-40f6b1aa5ede.png)

**Describe what problem you have encountered**

as a result, it will inject some components of Nacos/Discovery. Now the project structure seems different from the spring boot series. Personal suggestion is to follow the spring boot starter creation specification and create autoconfig packages (to facilitate the introduction of dependencies of control components).

**Comment by flystar32** [comment]
@SoyMeng   I  hava fixed this issue , 0.2.2.BUILD-SNAPSHOT works well.

`spring.cloud.nacos.discovery.enabled = false` and `spring.cloud.nacos.config.enabled = false`
