### ISSUE TITLE
The nacos execution./shutdown.sh script causes all registered services to shutdown

### ISSUE THREAD

**Issue by imxiongying** [spring-cloud-incubator/spring-cloud-alibaba#415]
**Which Component**
Nacos Discovery

**Describe what problem you have encountered**
Use `sh startup.sh -m standalone` start stand-alone nacos, when performing`. / shutdown.sh` when they stop nacos will perform all registration service client to AbstractApplicationContext shutdownHook, lead to all the service is offline. How do I ensure that when nacos fails or manually shuts down, it will not affect all registered services? It was downgraded to that you could not connect to nacos and could not get the latest registration service from nacos.

**Comment by fangjian0423** [comment]
Duplicate in https://github.com/alibaba/nacos/issues/874.

**Comment by flystar32** [comment]
This is a issue of Nacos
