### ISSUE TITLE
Setting false on autoRegister of @EnableDiscoveryClient will throw exception and application failed to start

### ISSUE THREAD

**Issue by fangjian0423** [spring-cloud-incubator/spring-cloud-alibaba#42]
Description:

Field nacosRegistration in org.springframework.cloud.alibaba.nacos.NacosDiscoveryClient required a bean of type 'org.springframework.cloud.alibaba.nacos.registry.NacosRegistration' that could not be found.
	- Bean method 'nacosRegistration' not loaded because @ConditionalOnProperty (spring.cloud.service-registry.auto-registration.enabled) found different value in property 'spring.cloud.service-registry.auto-registration.enabled'

**Comment by flystar32** [comment]
it's cause by a wrong design that Nacos discovery client rely on Nacos registration.
will fixed
