### ISSUE TITLE
spring-boot 2.1.3release版本 动态刷新无法使用

### ISSUE THREAD

**Issue by 91wangmeng** [spring-cloud-incubator/spring-cloud-alibaba#425]
我们鼓励使用英文，如果不能直接使用，可以使用翻译软件，您仍旧可以保留中文原文。
We recommend using English. If you are non-native English speaker, you can use the translation software. 

**Which Component**
spring-cloud-starter-alibaba-nacos-config

**Describe the bug**
无法动态刷新
Unable to refresh dynamically

**To Reproduce**
用最新的springboot版本,配置无法动态刷新
With the latest springboot version, the configuration cannot be dynamically refreshed

在springboot 2.1.3.release版本中,由于`EventListenerMethodProcessor`类中的`processBean()`方法内进行Eventlistener注册时增加了`!isSpringContainerClass(targetType)`判断,过滤掉了`org.springframework.cloud.endpoint.event.RefreshEventListener`类,导致配置文件修改后触发的`RefreshEvent`无法触发刷新操作,从而导致动态刷新功能无法使用

In the springboot 2.1.3.release version, due to the `processBean()` method in the `EventListenerMethodProcessor` class, the Eventlistener is registered with the addition of `!isSpringContainerClass(targetType)`, which is filtered.
      `org.springframework.cloud.endpoint.event.RefreshEventListener` class, which causes the `RefreshEvent` triggered after the configuration file modification cannot trigger the refresh operation, resulting in the dynamic refresh function being unavailable.

**Comment by 91wangmeng** [comment]
我想我应该去nacos项目提

**Comment by luohaoGit** [comment]
我也遇到了，请问如何解决的

**Comment by 91wangmeng** [comment]
> 我也遇到了，请问如何解决的

https://github.com/alibaba/nacos/issues/893#issue-420338685
