### ISSUE TITLE
class path resource cannot be resolved as enhancement in #91

### ISSUE THREAD

**Issue by yzhuomaoy** [spring-cloud-incubator/spring-cloud-alibaba#428]
For the enhancement in #91 , it add the file support. It could be work in local machine with IDE, but it could not be run correct as the json file packaged in jar. So there is exception throw like "Caused by: java.io.FileNotFoundException: class path resource [flowrule.json] cannot be resolved to absolute file path because it does not reside in the file system: jar:file:/E:/work/code/sentinel-demo/target/sentinel-demo.jar!/BOOT-INF/classes!/flowrule.json".

**Comment by fangjian0423** [comment]
Hi @yzhuomaoy 

It is recommended to use Nacos/Apollo/Zookeeper/Redis datasource to store rules.

You could use absolute path when you use File datasource & fat jar.

`FileRefreshableDataSource` use `java.io.File` as constructor args. So we couldn't get File from fat jar.

**Comment by yzhuomaoy** [comment]
> Hi @yzhuomaoy
> 
> It is recommended to use Nacos/Apollo/Zookeeper/Redis datasource to store rules.
> 
> You could use absolute path when you use File datasource & fat jar.
> 
> `FileRefreshableDataSource` use `java.io.File` as constructor args, but we couldn't get File from fat jar.

Hi @fangjian0423 ,
Thank you. I know it is recommend to use Nacos/Apollo/Zookeeper/Redis datasource to store rules, for these one, we could do rules dynamic. I just make some simple test quickly as a sample web application and found this issue and raise it. This issue is not a big deal.

**Comment by fangjian0423** [comment]
Thank you for using Spring Cloud Alibaba 😄

**Comment by qixiaobo** [comment]
So sad to find this~

**Comment by changetest** [comment]
Hi, @fangjian0423  Execuse me, I want to confirm wheather the spring-cloud-alibaba  can support getting File from fat jar in the current version.That means we can't write our properties like this :
spring.cloud.sentinel.datasource.ds1=jar:D:/sentinel.jar!/BOOT-INF/classes/config/sentinel/FlowRule.json
