### ISSUE TITLE
no available server to connect.

### ISSUE THREAD

**Issue by kangxukangxu** [spring-cloud-incubator/spring-cloud-alibaba#429]
2019-03-13 20:38:24.657 ERROR 20560 --- [imeoutChecker_1] com.alibaba.fescar.config.ConfigFuture   : config operation timeout,cost:5001 ms,op:GET,dataId:service.vgroup_mapping.tx-demo-fescar-account-fescar-service-group
2019-03-13 20:38:24.657 ERROR 20560 --- [imeoutChecker_1] c.a.fescar.core.rpc.netty.RmRpcClient    : no available server to connect.

How to deal with？？？

**Comment by lilongthinker** [comment]
> 2019-03-13 20:38:24.657 ERROR 20560 --- [imeoutChecker_1] com.alibaba.fescar.config.ConfigFuture : config operation timeout,cost:5001 ms,op:GET,dataId:service.vgroup_mapping.tx-demo-fescar-account-fescar-service-group
> 2019-03-13 20:38:24.657 ERROR 20560 --- [imeoutChecker_1] c.a.fescar.core.rpc.netty.RmRpcClient : no available server to connect.
> 
> How to deal with？？？

请问下这个问题怎么解决的？

I have the same problem, how did you fix it , will you share it ?

**Comment by kangxukangxu** [comment]
@lilongthinker The vgroup_mapping attribute name in the file.conf file must match spring.application.name
![image](https://user-images.githubusercontent.com/17905150/56879640-39406d00-6a8c-11e9-914b-d6cbbe6d7573.png)
![image](https://user-images.githubusercontent.com/17905150/56879651-40677b00-6a8c-11e9-9845-2830f182548b.png)
![image](https://user-images.githubusercontent.com/17905150/56879666-507f5a80-6a8c-11e9-9afc-a7a1a7b8e2e3.png)

**Comment by lilongthinker** [comment]
> @lilongthinker The vgroup_mapping attribute name in the file.conf file must match spring.application.name
> ![image](https://user-images.githubusercontent.com/17905150/56879640-39406d00-6a8c-11e9-914b-d6cbbe6d7573.png)
> ![image](https://user-images.githubusercontent.com/17905150/56879651-40677b00-6a8c-11e9-9845-2830f182548b.png)
> ![image](https://user-images.githubusercontent.com/17905150/56879666-507f5a80-6a8c-11e9-9afc-a7a1a7b8e2e3.png)

more than thx,  it worked

**Comment by kangxukangxu** [comment]
@lilongthinker Has the problem been solved?

**Comment by lilongthinker** [comment]
> @lilongthinker Has the problem been solved?

YES!!!
