### ISSUE TITLE
org.springframework.beans.factory.BeanCurrentlyInCreationException: Error creating bean with name 'scopedTarget.app': Requested bean is currently in creation: Is there an unresolvable circular reference?

### ISSUE THREAD

**Issue by quzhixue-Kimi** [spring-cloud-incubator/spring-cloud-alibaba#43]
Hi dear,
When I use the zookeeper as the storage, I follow your comments as below:
1. adding
@SentinelDataSource("spring.cloud.sentinel.datasource")
    private DataSource dataSource;

@Bean
public Converter myParser() {
        return new JsonFlowRuleListParser();
}
in the startup class, JsonFlowRuleListParser class is based on your sample code, also.

2. adding 
spring.cloud.sentinel.transport.dashboard = localhost:8989
spring.cloud.sentinel.transport.port = 8721
spring.cloud.sentinel.datasource.type = zk
spring.cloud.sentinel.datasource.serverAddr = localhost:2181
spring.cloud.sentinel.datasource.path = /Sentinel-Demo/SYSTEM-CODE-DEMO-FLOW
spring.cloud.sentinel.datasource.converter = myParser
in the application.properties file

In the document(https://github.com/spring-cloud-incubator/spring-cloud-alibaba/blob/master/spring-cloud-alibaba-examples/sentinel-example/sentinel-core-example/readme-zh.md).
The sample code is below:
spring.cloud.sentinel.datasource.configParser=myParser
But, it seems that there is no property of FileRefreshableDataSourceFactoryBean class and, I just use the spring.cloud.sentinel.datasource.converter instead of configParser

It is appreciated that you could try to review my issue, any feedback is helpful.

BR
Kimi

**Comment by fangjian0423** [comment]
I startup sentinel-core-example application with your zk configuration, everything is ok. Can you write some more details? 

And I fix `configParser` to `converter` in readme just now. Thanks!

**Comment by quzhixue-Kimi** [comment]
Hi Fangjian
Thanks for your feedback.
In my local zookeeper, there have been some content as below:
[zk: localhost:2181(CONNECTED) 3] get /Sentinel-Demo/SYSTEM-CODE-DEMO-FLOW
[
  {
    "resource": "testresource",
    "controlBehavior": 0,
    "count": 1.0,
    "grade": 1,
    "limitApp": "default",
    "strategy": 0
  }
]
cZxid = 0x255b5
ctime = Mon Oct 15 16:35:10 CST 2018
mZxid = 0x255e0
mtime = Tue Oct 16 13:09:23 CST 2018
pZxid = 0x255b5
cversion = 0
dataVersion = 8
aclVersion = 0
ephemeralOwner = 0x0
dataLength = 148
numChildren = 0

I also, startup the sentinel-core-example application based on the repository(https://github.com/spring-cloud-incubator/spring-cloud-alibaba.git)

And, the application.properties that I have modified as below:
spring.application.name=sentinel-example
server.port=18083
management.endpoints.web.exposure.include=*
spring.cloud.sentinel.transport.dashboard=localhost:8989
spring.cloud.sentinel.transport.port=8721
spring.cloud.sentinel.datasource.type=zk
spring.cloud.sentinel.datasource.serverAddr=localhost:2181
spring.cloud.sentinel.datasource.path=/Sentinel-Demo/SYSTEM-CODE-DEMO-FLOW
spring.cloud.sentinel.datasource.converter=myParser

The endpoint I would like to test is:
@RequestMapping(value = "/hello", method = RequestMethod.GET)
	@SentinelResource("testresource")
	public String hello() {
		return "Hello";
	}

Also, in the ServiceApplication class, 
@SentinelDataSource("spring.cloud.sentinel.datasource")
    private AbstractDataSource dataSource;
I added. I am not sure that AbstractDataSource interface should be used or 
Based on https://github.com/spring-cloud-incubator/spring-cloud-alibaba/blob/master/spring-cloud-alibaba-examples/sentinel-example/sentinel-core-example/readme-zh.md

@SentinelDataSource("spring.cloud.sentinel.datasource")
private DataSource dataSource;    should be used?
Should javax.activation.DataSource be used? But, the application will throw one exception.

Finally, I used private AbstractDataSource dataSource; And, startup perfectly.
But, to visit the http://localhost:18083/actuator/sentinel, there is no flowrules,systemrules or graderules to be shown in the JSON result.

What I set in my local zookeeper is based on the sample code via https://github.com/alibaba/Sentinel.git (ZookeeperConfigSender.java of sentinel-demo-zookeeper-datasource project)

It is appreciated that you could review the above information.
Any feedback is grateful.

BR
Kimi

**Comment by fangjian0423** [comment]
Hi Kimi. 
Thanks for concerning our project.

First Question:

`javax.activation.DataSource` will not be used. You can using `com.alibaba.csp.sentinel.datasource.ReadableDataSource`.

`DataSource` was using in Sentinel 0.1.0 version, but it rename to `ReadableDataSource` in 0.2.0 version. 

So you can using `ReadableDataSource` replace of `AbstractDataSource`.

We now update readme using `ReadableDataSource` replace of `DataSource`.

Second Question:

It is a bug and we fixed it.

Please see the commit 568da97adfd946dce32a44cbdffa70aa6bb3672c.

Now the rules in `ReadableDataSource` will be added when application started.
