### ISSUE TITLE
[Fescar-Sample] when version upgrade 0.3.0+, unique index instead of normal index 

### ISSUE THREAD

**Issue by slievrly** [spring-cloud-incubator/spring-cloud-alibaba#432]
我们鼓励使用英文，如果不能直接使用，可以使用翻译软件，您仍旧可以保留中文原文。
We recommend using English. If you are non-native English speaker, you can use the translation software. 

**Which Component**
Fescar

**Describe the bug**
when version upgrade 0.3.0+, Unique index instead of normal index 。
we use unique index prevent when request GlobalRollback but some branches report not received from doing local Trx。

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**
e.g.  MacOS  、Java8 、 Version 0.2.1.RELEASE

**Comment by flystar32** [comment]
thanks for your contribution, we will review it soon
