### ISSUE TITLE
Unable to register automatically

### ISSUE THREAD

**Issue by leetomlee123** [spring-cloud-incubator/spring-cloud-alibaba#436]
我们鼓励使用英文，如果不能直接使用，可以使用翻译软件，您仍旧可以保留中文原文。
We recommend using English. If you are non-native English speaker, you can use the translation software. 

**Which Component**
eg. Nacos Discovery, Sentinel

**Describe the bug**

**To Reproduce**

**Expected behavior**
when i used `new SpringApplicationBuilder(DispacherApplication.class).web(WebApplicationType.NONE).run(args);` to start springboot2.1.1 ,can not auto register to nacos 

**Screenshots**

**Additional context**
e.g.  nacos、Java8 、 springboot2.1.1

**Comment by leetomlee123** [comment]
use this code `SpringApplication.run(DispacherApplication.class);`,it is work

**Comment by flystar32** [comment]
spring cloud discovery won't register when WebApplicationType.NONE

**Comment by leetomlee123** [comment]
what should i do ,i want it

**Comment by fangjian0423** [comment]
As you said, using `SpringApplication.run(DispacherApplication.class)` to run application.

**Comment by leetomlee123** [comment]
that's too regretful

**Comment by leetomlee123** [comment]
commandline 手动注册 `namingService.registerInstance("service-dispacher","10.0.41.90",8848);`` @NacosInjected
    private NamingService namingService;` NPM
