### ISSUE TITLE
nacos+actuator has a error

### ISSUE THREAD

**Issue by sundong1982** [spring-cloud-incubator/spring-cloud-alibaba#441]
env: nacos0.9.0,  spring-cloud-alibaba 0.2.1.RELEASE ,spring-cloud.Finchley.SR, spring-boot 2.0.8.RELEASE

jdk11

After adding the following reference:
`<dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-actuator</artifactId>
        </dependency>`

Error occurred：
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'nacosRegistration': Invocation of init method failed; nested exception is java.lang.NoClassDefFoundError: org/springframework/boot/actuate/autoconfigure/web/server/ManagementServerProperties

Get right after removing actuator

**Comment by fangjian0423** [comment]
Could you please provide a Minimal, Complete, and Verifiable example?

**Comment by sundong1982** [comment]
https://github.com/sundong1982/spali.demo

**Comment by fangjian0423** [comment]
works fine on my machine with jdk 11.

![image](https://user-images.githubusercontent.com/5254035/54505132-9a473200-4971-11e9-807f-ed39804c3c32.png)

![image](https://user-images.githubusercontent.com/5254035/54505113-8a2f5280-4971-11e9-8060-e53fef47f27f.png)

**Comment by sundong1982** [comment]
@fangjian0423 It was my nacos-server cluster that each node's log was exported to the same place, which caused three nacos-servers to start at the same time. Two of them were not running. I visited nacos-server through nginx before and did not notice this problem. Now I find this problem and have solved it.
thx:)
