### ISSUE TITLE
Http Method should be required on resource name definition

### ISSUE THREAD

**Issue by vipweihua** [spring-cloud-incubator/spring-cloud-alibaba#445]
Component: Sentinel

Http method is missed to define the RestTemplate flow control resource name(http://server/a/b/c), while FeignClient has it, like GET:http://server/a/b/c. GET and POST are different resources. 

It'll be better if FeignClient and RestTemplate can share the same rule.

**Comment by fangjian0423** [comment]
Yes.

The resource strategy of RestTemplate should be same as Open-Feign.
