### ISSUE TITLE
When is the release planned 0.2.2

### ISSUE THREAD

**Issue by hadoop835** [spring-cloud-incubator/spring-cloud-alibaba#448]
When is the release planned 0.2.2

**Comment by fangjian0423** [comment]
We will release when nacos release 1.0 GA version and it is coming soon.

**Comment by mostcool** [comment]
Will you use dubbo-2.7.1?

**Comment by mostcool** [comment]
@fangjian0423 Will 0.2.2 integrate directly with dubbo-2.7.1?

**Comment by fangjian0423** [comment]
Dubbo 2.7.0

**Comment by fangjian0423** [comment]
It has been released.
