### ISSUE TITLE
nacos can't register service  

### ISSUE THREAD

**Issue by yekl** [spring-cloud-incubator/spring-cloud-alibaba#449]
The version used is as follows：
1、Spring cloud alibaba 0.2.1.RELEASE and spring cloud alibaba 0.2.2.BUILD-SNAPSHOT version,
2、nacos-server-0.9.0 and nacos-server-1.0.0-RC1 
3、nacos-client-0.2.1.RELEASE and nacos-client-0.2.2.BUILD-SNAPSHOT

**Comment by flystar32** [comment]
Nacos-Server 1.0.0-RC1 is not compatible with Nacos-Client before 1.0.0-RC1, you need to use the same verison of Nacos-Sever and Nacos-Client.

**Comment by flystar32** [comment]
we recommend to use the latest version , I've update nacos version to 1.0.0-RC1 in this commit.https://github.com/spring-cloud-incubator/spring-cloud-alibaba/commit/fc724a505694a7a7aa5412f6c555fe3027805db6

**Comment by SoyMeng** [comment]
also register failed, client and server is the same version to 1.0.0-RC1
