### ISSUE TITLE
Sentinel bug

### ISSUE THREAD

**Issue by w5185552** [spring-cloud-incubator/spring-cloud-alibaba#450]
Sentinel sentinel-record.log error when docker container uses local network:
Java.net.UnknownHostException XXX Name or service not known

**Comment by fangjian0423** [comment]
Please provide more detailed information.

**Comment by w5185552** [comment]
使用docker 命令 docker run -d --network=host xx.jar 
应用访问Sentinel 控制台。 控制台没有显示应用的任何信息。
容器日志/home/logs/csp/sentinel-record.log显示java.net.UnknownHostException: xxx Name or service not known
使用 docker run -d xx.jar 可以在Sentinel 控制台看到信息

**Comment by fangjian0423** [comment]
I think it's a network problem, not Sentinel's Bug.
