### ISSUE TITLE
 The problem of Nacos Discovery namespace isolation 指定命名空间无效

### ISSUE THREAD

**Issue by yuguhan** [spring-cloud-incubator/spring-cloud-alibaba#452]
Nacos版本 0.9.0 ，
spring-cloud-alibaba-dependencies 版本号0.2.1.RELEASE 
配置文件中设置了namespace，但是没有起作用，还是出现在public中

**Comment by flystar32** [comment]
namespace is support after nacos client 0.8.0,   version 2.0.0.BUILD_SNAPSHOT has  update nacos client version to 1.0.0-RC1, use this version works well.

**Comment by kingslyChen** [comment]
i have same problem,is bug?
