### ISSUE TITLE
NacosConfigListener 不生效

### ISSUE THREAD

**Issue by maojx0630** [spring-cloud-incubator/spring-cloud-alibaba#456]
**Which Component**
Nacos config

**Describe the bug**
@NacosConfigListener 无效

**Screenshots**
![image](https://user-images.githubusercontent.com/37826107/54594447-a7e0e280-4a6b-11e9-86bb-2353ab21a704.png)

**Additional context**
e.g.  MacOS  、Java11 、 Version 0.2.1.RELEASE nacos0.9 springboot 2.1.3 cloud G.sr1不生效

and  MacOS  、Java11 、 Version 0.2.2 nacos1 springboot 2.1.3 cloud G.sr1也不生效

**Comment by flystar32** [comment]
duplicated  #458
