### ISSUE TITLE
nacos registry, register failed..

### ISSUE THREAD

**Issue by maojx0630** [spring-cloud-incubator/spring-cloud-alibaba#457]
nacos registry, kyubi-gateway register failed..
在0.9版本中启动正常，1.0启动出现异常
alibaba cloud 0.2.1 0.2.2均出现该异常

![image](https://user-images.githubusercontent.com/37826107/54594776-52f19c00-4a6c-11e9-97d6-e253ba1c9b84.png)

**Comment by nkorange** [comment]
@maojx0630 Update nacos-client to 1.0

**Comment by maojx0630** [comment]
> @maojx0630 Update nacos-client to 1.0
It's version 1.0 that's the problem, but 0.9 won't.

**Comment by maojx0630** [comment]
It's version 1.0 that's the problem, but 0.9 won't.

**Comment by nkorange** [comment]
![image](https://user-images.githubusercontent.com/4593375/54660409-50954d80-4b11-11e9-8fd5-3cdba20f7fa1.png)

It's your client, brother.

**Comment by maojx0630** [comment]
spring cloud alibaba nacos config and discovery in 0.22 
It will be upgraded to 1.0?

**Comment by flystar32** [comment]
@maojx0630 use 0.2.2.BUILD_SNAPSHOT

**Comment by maojx0630** [comment]
ok
