### ISSUE TITLE
Rules from Ctrip Apollo could not be updated automatically

### ISSUE THREAD

**Issue by quzhixue-Kimi** [spring-cloud-incubator/spring-cloud-alibaba#50]
Hi dear,

The Apollo of Ctrip has been used as the storage and, there have been three rules that I config in Apollo as below:
"FlowRules": [
        {
            "controlBehavior": 0,
            "count": 1.0,
            "grade": 1,
            "limitApp": "default",
            "maxQueueingTimeMs": 500,
            "refResource": null,
            "resource": "/p1",
            "strategy": 0,
            "warmUpPeriodSec": 10
        },
        {
            "controlBehavior": 0,
            "count": 1.0,
            "grade": 1,
            "limitApp": "default",
            "maxQueueingTimeMs": 500,
            "refResource": null,
            "resource": "/p",
            "strategy": 0,
            "warmUpPeriodSec": 10
        },
        {
            "controlBehavior": 0,
            "count": 1.0,
            "grade": 1,
            "limitApp": "default",
            "maxQueueingTimeMs": 500,
            "refResource": null,
            "resource": "testresource",
            "strategy": 0,
            "warmUpPeriodSec": 10
        }
    ]

And, in my local macbook, to visit http://localhost:myport/actuator/sentinel that I could see these three rules.
But, I tried to modify the rules in Apollo, which two rules were removed and, it seems that Sentinel console still fetch these three original rules or, is there any additional command that I need to run or not?
I am not sure that is it an issue or Sentinel does not support fetch latest rules from external data source, such as zookeeper or apollo.
What I read is from https://github.com/alibaba/Sentinel/wiki/FAQ - 规则存储与动态规则数据源（DataSource）

It seems that it does not affect external json file as data storage, also. I added a new rule in Sentinel console but, no change of the json file at all.

Any feedback is appreciated.
BR
Kimi

**Comment by fangjian0423** [comment]
Hi Kimi.

When the rule is changed in Apollo, it will take effect in real time.

I think maybe there is some problems with your apollo.

**Comment by quzhixue-Kimi** [comment]
Hi Fanjian

The Apollo runs ok since, some config have been set as below:

spring.cloud.sentinel.transport.dashboard = localhost:8989
spring.cloud.sentinel.transport.port = 8721
spring.cloud.sentinel.datasource.type = apollo
spring.cloud.sentinel.datasource.namespaceName = application
spring.cloud.sentinel.datasource.flowRulesKey = flowRules
spring.cloud.sentinel.datasource.converter = myParser
spring.cloud.sentinel.datasource.defaultFlowRuleValue = [ {            "resource": "testresource",           "controlBehavior": 0,            "count": 1.0,            "grade": 1,            "limitApp": "default",           "strategy": 0          }       ]
server.port = 5550
management.endpoints.web.exposure.include = *
management.endpoints.web.cors.allowed-origins = *
management.endpoints.web.cors.allowed-methods = *
management.endpoint.health.show-details = ALWAYS

And, my application will use these config when startup. The flowrulevalue could be shown via http://localhost:5550/actuator/sentinel url. Also, my application run ok. But, updating the defaultFlowRuleValue via apollo, these latest rules could not be updated via endpoint of actuator and sentinel console.

In my main class, these below code was added:
@SentinelDataSource("spring.cloud.sentinel.datasource")
    private ReadableDataSource dataSource;

@Bean
    public Converter myParser() {
        return new JsonFlowRuleListParser();
    }


Even, I also, tried to use the spring.cloud.sentinel.datasource.type = file
based on https://github.com/spring-cloud-incubator/spring-cloud-alibaba/blob/master/spring-cloud-alibaba-examples/sentinel-example/sentinel-core-example/readme-zh.md (ReadableDataSource 支持)
spring.cloud.sentinel.datasource.file=my local json file in apollo. To update or add a new rule in sentinel console, my local json file could not be updated as latest.

It is appreciated that you could review my config and, any feedback is helpful.

BR
Kimi

**Comment by quzhixue-Kimi** [comment]
Even, I used the sample code sentinel-demo-apollo-datasource via repository and, in Apollo, there is a sample application sentinel-demo, whose config is below:
spring.cloud.sentinel.transport.dashboard = localhost:8989
spring.cloud.sentinel.transport.port = 8721
spring.cloud.sentinel.datasource.type = apollo
spring.cloud.sentinel.datasource.namespaceName = application
spring.cloud.sentinel.datasource.flowRulesKey = flowRules
spring.cloud.sentinel.datasource.converter = myParser
spring.cloud.sentinel.datasource.defaultFlowRuleValue = [\n          {\n            "resource": "testresource",\n            "controlBehavior": 0,\n            "count": 1.0,\n            "grade": 1,\n            "limitApp": "default",\n            "strategy": 0\n          }\n        ]
It seems that the rule does not affect.

BR
Kimi

**Comment by fangjian0423** [comment]
Hi Kimi.
I try with Apollo just now, everything is ok.

I think you could update key `flowRulesKey ` in Apollo, not `defaultFlowRuleValue `.

You can debug to check Apollo Listener is healthy in ApolloDataSource#initializeConfigChangeListener.

When the data is changed in Apollo, check it can debug into this Listener.

**Comment by quzhixue-Kimi** [comment]
Hi dear, 
Will you please send me your config in Apollo(the screen shot is the best one.). I have tried modify the spring.cloud.sentinel.datasource.flowRulesKey with the value of 
[
    {
        "resource": "testresource",
        "controlBehavior": 0,
        "count": 1,
        "grade": 1,
        "limitApp": "default",
        "strategy": 0
    }
]

And, the spring.cloud.sentinel.datasource.defaultFlowRuleValue must be set also.
But, no affect to modify both the defaultFlowRuleValue or flowRulesKey.
I found that the endpoint of actuator is from defaultFlowRuleValue instead of flowRulesKey.

![image](https://user-images.githubusercontent.com/8235746/47262671-ccb74500-d521-11e8-905b-4b519dc57c8e.png)
![image](https://user-images.githubusercontent.com/8235746/47262690-10aa4a00-d522-11e8-949c-6f218ff459cc.png)
![image](https://user-images.githubusercontent.com/8235746/47262712-70a0f080-d522-11e8-9b6e-d437c4fa5bd8.png)

**Comment by fangjian0423** [comment]
Hi Kimi.

This is my example configuration:

`
spring.cloud.sentinel.datasource.type=apollo
spring.cloud.sentinel.datasource.namespaceName=application
spring.cloud.sentinel.datasource.flowRulesKey=sentinel
spring.cloud.sentinel.datasource.defaultFlowRuleValue=test
spring.cloud.sentinel.datasource.converter=myParser
`

And the config in Apollo(The 3 flow rules in your first reply):

<img width="1189" alt="apollo-detail" src="https://user-images.githubusercontent.com/5254035/47264953-f50b6780-d552-11e8-8bc3-3a578e43d0c0.png">

when I update the rules to 2 flow rules in Apollo, it takes effect.

I think your Apollo is not healthy because it use `defaultFlowRuleValue `. If your apollo is healthy, it will get config from Apollo using `flowRulesKey`.

You can look at `ApolloDataSource#readSource`, it using `com.ctrip.framework.apollo.Config#getProperty`  to get config. The second parameter is using `defaultFlowRuleValue`, it means the default value when key is not found or any error occurred. You can debug into it to make sure Apollo is health or not.

**Comment by quzhixue-Kimi** [comment]
Hi there,
When sentinel-dashboard updated via https://github.com/alibaba/Sentinel/releases/download/1.4.0/sentinel-dashboard-1.4.0.jar.

These components have been updated, some issues occurred, but resolved.
        <dependency>
            <groupId>org.springframework.cloud</groupId>
            <artifactId>spring-cloud-starter-alibaba-sentinel</artifactId>
        </dependency>
        <dependency>
            <groupId>com.alibaba.csp</groupId>
            <artifactId>sentinel-datasource-apollo</artifactId>
            <version>1.5.1</version>
        </dependency>

I followed instructions via
https://github.com/spring-cloud-incubator/spring-cloud-alibaba/wiki/Sentinel 
spring.cloud.sentinel.datasource.ds4.apollo.namespace-name = application
spring.cloud.sentinel.datasource.ds4.apollo.flow-rules-key = sentinel
spring.cloud.sentinel.datasource.ds4.apollo.default-flow-rule-value = test
spring.cloud.sentinel.datasource.ds5.apollo.rule-type=param-flow

But, my apollo config datasource did not affect and, visit http://localhost:5550/actuator/sentinel, there was no rules,
my application config in application.properties is below:

spring.cloud.sentinel.datasource.ds4.apollo.namespace-name = application
spring.cloud.sentinel.datasource.ds4.apollo.data-type=json
spring.cloud.sentinel.datasource.ds4.apollo.converter-class=org.springframework.cloud.alibaba.cloud.examples.JsonFlowRuleListConverter
spring.cloud.sentinel.datasource.ds4.apollo.flow-rules-key = sentinel
spring.cloud.sentinel.datasource.ds4.apollo.default-flow-rule-value = test
spring.cloud.sentinel.datasource.ds4.apollo.rule-type=flow

![image](https://user-images.githubusercontent.com/8235746/56015447-ab465180-5d2b-11e9-9cd9-bfe46e10bf44.png)

It is appreciated that you could provide your new apollo config and, sorry for reopening the issue.

BR
Kimi
