### ISSUE TITLE
can't download "spring-cloud-starter-alibaba-fescar"

### ISSUE THREAD

**Issue by marktubu1993** [spring-cloud-incubator/spring-cloud-alibaba#503]
**Which Component**
spring-cloud-alibaba/spring-cloud-alibaba-examples/fescar-example/

**Describe the bug**
feascar-example cannot download the jar
<dependency>
            <groupId>org.springframework.cloud</groupId>
            <artifactId>spring-cloud-starter-alibaba-fescar</artifactId>
 </dependency>

**Comment by fangjian0423** [comment]
I think there is something wrong with your local maven.

**Comment by flystar32** [comment]
@fangjian0423 I think maybe he is asking when will `spring-cloud-starter-alibaba-fescar` release to central maven.
