### ISSUE TITLE
why this schedule framework must register alicloud account?  

### ISSUE THREAD

**Issue by fenghaidong** [spring-cloud-incubator/spring-cloud-alibaba#508]
Hi all
    i tried to use this new schedule framework right now, but when i try to startup my app, an exception occurred. "access-key" or "secret-key" cannot be empty. Is it necessary to register with alicloud?

**Comment by fangjian0423** [comment]
[SchedulerX](https://help.aliyun.com/document_detail/43136.html) now is a component in EDAS, you need to register alibaba cloud account to try it.

**Comment by fangjian0423** [comment]
You could also refer [Wiki](https://github.com/spring-cloud-incubator/spring-cloud-alibaba/wiki/SchedulerX).
