### ISSUE TITLE
spring-cloud-alibaba-sentinel now main support spring mvc, can divide datasource config responsibility 

### ISSUE THREAD

**Issue by tigerMoon** [spring-cloud-incubator/spring-cloud-alibaba#51]
spring-cloud-alibaba-sentinel now main support spring MVC, and integrate with the common config like data source. 
If spring-cloud-alibaba-sentinel-gateway or others support need it, then they can use data source config module directly.

**Comment by fangjian0423** [comment]
Hi tigerMoon.

A new module `spring-cloud-alibaba-sentinel-datasource` has been created, you can using it directly.
