### ISSUE TITLE
How to specify group name of services for discovery?

### ISSUE THREAD

**Issue by MaoJianwei** [spring-cloud-incubator/spring-cloud-alibaba#518]
Can we specify group name of services in properties files?

I don't find corresponding configuration item on: [more-configuration-items](https://github.com/spring-cloud-incubator/spring-cloud-alibaba/tree/master/spring-cloud-alibaba-examples/nacos-example/nacos-discovery-example#more)

I try to use _spring.cloud.nacos.discovery.group_, but it doesn't work.

![微信截图_20190402112558](https://user-images.githubusercontent.com/12800168/55374386-de722f00-553a-11e9-9ec2-74dd6a099703.png)

**Comment by fangjian0423** [comment]
This feature is supported in nacos-client 0.8.0 but the nacos-client version in Spring Cloud Alibaba Nacos Discovery Starter is 0.6.2. You could use snapshot version in master branch.

Duplicate in #295.
