### ISSUE TITLE
About the problem of unaggregated request routing with parameters

### ISSUE THREAD

**Issue by SevenLM361** [spring-cloud-incubator/spring-cloud-alibaba#52]
## API URL Example: 
/v1/user/info/{userId}

## Request Example: 
/v1/user/info/1 
/v1/user/info/2
/v1/user/info/3

## Expect Statistic Or Suggest：
/v1/user/info/{params}

**Comment by fangjian0423** [comment]
Hi SevenLM361.

Did you mean this feature that sentinel should support? Can you describe it more detail.
