### ISSUE TITLE
How to use Spring Bean in Ali ScheduleX?

### ISSUE THREAD

**Issue by liuninglin** [spring-cloud-incubator/spring-cloud-alibaba#521]
**Which Component**
ScheduleX

**Describe what problem you have encountered**
I cannot use Spring Bean which I injected with annotation in my schedule processor which implements class ScxSimpleJobProcessor.

My code shows below. I cannot use Spring Bean "test2Service".
```
public class Test2Schedule implements ScxSimpleJobProcessor {
    @Resource
    public Test2Service test2Service;

    @Override
    public ProcessResult process(ScxSimpleJobContext scxSimpleJobContext) {
        try {
            String processResult = test2Service.combineTest();
            boolean flag = false;
            if (processResult.contains("success")) {
                flag = true;
            }
            System.out.println(new Date() + "调度执行：" + processResult);
            return new ProcessResult(flag);
        } catch (Exception e) {
            e.printStackTrace();
        }
        System.out.println("cp-test2.combineTest schedule process fail");
        return new ProcessResult(false);
    }
}
```

**Comment by fangjian0423** [comment]
Make sure `Test2Service` was initialized by Spring.

You could refer example: https://github.com/spring-cloud-incubator/spring-cloud-alibaba/tree/master/spring-cloud-alibaba-examples/schedulerx-example/schedulerx-simple-task-example

**Comment by liuninglin** [comment]
I definitely initialized **Test2Service** by Spring.

The Test2Service is just an interface which is a Feign Client. Here is my code below.
```
@FeignClient(value = "cp-test2", fallback = Test2ServiceFailure.class)
public interface Test2Service {
    @GetMapping("/combineTest")
    String combineTest();
}
```
I always got errors with NullPointerException. The error info shows below. This error points to my code above that locates in the line **"String processResult = test2Service.combineTest();"**
```
java.lang.NullPointerException
	at com.amway.acti.cpschedule.schedule.Test2Schedule.process(Test2Schedule.java:25)
	at com.alibaba.dts.client.executor.simple.processor.ScxSimpleTaskProcessor.executeTask(ScxSimpleTaskProcessor.java:160)
	at com.alibaba.dts.client.executor.simple.processor.ScxSimpleTaskProcessor.run(ScxSimpleTaskProcessor.java:101)

```

**Comment by liuninglin** [comment]
And I followed example code, then wrote a simple Service to print "hello world" and initialized this Service by Spring. Running this Service by ScheduleX Processor, then showing result without errors.
So, could I assume that ScheduleX cannot run a Spring Bean which is a Feign Client.

**Comment by fangjian0423** [comment]
It is a bug in 0.2.1.RELEASE version.

You could use 2.1.0.BUILD-SNAPSHOT to try it.

We will release new version soon.

**Comment by fangjian0423** [comment]
Refer #491

**Comment by liuninglin** [comment]
Thks, it works. Waiting for the latest version.
