### ISSUE TITLE
Unable to validate dynamic refresh

### ISSUE THREAD

**Issue by juncheno** [spring-cloud-incubator/spring-cloud-alibaba#529]
**Expected behavior**看了类似的issue,但是总感觉不对
我按照https://github.com/spring-cloud-incubator/spring-cloud-alibaba/blob/master/spring-cloud-alibaba-examples/nacos-example/nacos-config-example/readme-zh.md  验证自动注入
 但是rest接口查询没有更新。
我的操作步骤如下：

先创创建好配置项，然后通过一个rest(http://127.0.0.1:18084/user)接口试了一下，配置项是可以获取的
2.然后修改了一个配置项的值，重新刷新rest  http://127.0.0.1:18084/user接口，配置项没有改又用api做了一下修改：
curl -X POST "http://127.0.0.1:8848/nacos/v1/cs/configs?dataId=nacos-config-example.properties&group=DEFAULT_GROUP&content=user.id=1%0Auser.name=james%0Auser.age=18"重新加载rest接口发现配置项仍没更新，首先声明我的controller有加@RefreshScope注解
代码如下：
配置文件与启动类和nacos-config-example基本一样 只是receiveConfigInfo 方法里面修改了下，发现 String [] configLines = configInfo.split("\r\n"); 当配置修改 监听拿到数据打印日志
Latest username=null, userAge=null  应该是监听获取数据有点问题 所以换成按切分"\n"后
String [] configLines = configInfo.split("\n");日志正常了
启动类:
SpringBootApplication
public class Application {

	public static void main(String[] args) {
		SpringApplication.run(Application.class, args);
	}
}

@Component
class SampleRunner implements ApplicationRunner {

	@Value("${user.name}")
	String userName;

	@Value("${user.age:25}")
	int userAge;

    @Autowired
    private NacosConfigProperties nacosConfigProperties;

	@Override
	public void run(ApplicationArguments args) throws Exception {
		System.out.println(String.format("Initial username=%s, userAge=%d", userName, userAge));

		nacosConfigProperties.configServiceInstance()
                .addListener("nacos-config-example.properties", "DEFAULT_GROUP", new Listener() {

                    /**
                     * Callback with latest config data.
                     *
                     * For example, config data in Nacos is:
                     *
                     *     user.name=Nacos
                     *     user.age=25
                     *
                     * @param configInfo latest config data for specific dataId in Nacos server
                     */
                    @Override
                    public void receiveConfigInfo(String configInfo) {
                        String [] configLines = configInfo.split("\n");
                        Map<String, String> configs = new HashMap<>();
                        for (String c : configLines) {
                            String [] configPair = c.split("=");
                            configs.put(configPair[0], configPair[1]);
                        }

                        System.out.println(String.format("Latest username=%s, userAge=%s",
                                configs.get("user.name"), configs.get("user.age")));
                    }

                    @Override
                    public Executor getExecutor() {
                        return null;
                    }
                });
	}
}

@RestController
@RefreshScope
class SampleController {

	@Value("${user.name}")
	String userName;

	@Value("${user.age:25}")
	int age;

	@RequestMapping("/user")
	public String simple() {
		return "Hello Nacos Config!" + "Hello " + userName + " " + age + "!";
	}
}

maven pom文件有点不一样(由于本地环境导入不了依赖
<parent>
        <groupId>org.springframework.cloud</groupId>
        <artifactId>spring-cloud-alibaba-examples</artifactId>
        <version>2.1.0.BUILD-SNAPSHOT</version>
        <relativePath>../../pom.xml</relativePath>
    </parent>

)所以换成下面的了
首先
<parent>
        <groupId>org.springframework.cloud</groupId>
        <artifactId>spring-cloud-build</artifactId>
        <version>2.1.2.RELEASE</version>
    </parent>
<dependencies>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-web</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.cloud</groupId>
            <artifactId>spring-cloud-starter-alibaba-nacos-config</artifactId>
        </dependency>

        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-actuator</artifactId>
        </dependency>
        <dependency>
            <groupId>org.hibernate</groupId>
            <artifactId>hibernate-validator</artifactId>
             <version>5.2.4.Final</version>
        </dependency>
    </dependencies>
<dependencyManagement>
   <dependencies>
     <dependency>
            <groupId>org.springframework.cloud</groupId>
            <artifactId>spring-cloud-dependencies</artifactId>
            <version>Finchley.SR1</version>
            <type>pom</type>
            <scope>import</scope>
        </dependency>
       <dependency>
            <groupId>org.springframework.cloud</groupId>
            <artifactId>spring-cloud-alibaba-dependencies</artifactId>
            <version>0.2.1.RELEASE</version>
            <type>pom</type>
            <scope>import</scope>
        </dependency>
   </dependencies>
</dependencyManagement>
application.properties配置如下:
server.port=18084
management.endpoints.web.exposure.include=*
bootstrap.properties配置如下:
spring.application.name=nacos-config-example
spring.cloud.nacos.config.server-addr=127.0.0.1:8848
spring.cloud.nacos.config.shared-data-ids=base-common.properties,common.properties
spring.cloud.nacos.config.refreshable-dataids=common.properties
这些配置不太清楚，看看是什么问题哦

**Comment by fangjian0423** [comment]
Could you pls describe it clearly?  It's too messy.
