### ISSUE TITLE
A Question About NacosRibbon

### ISSUE THREAD

**Issue by niechen2012** [spring-cloud-incubator/spring-cloud-alibaba#531]
Read the Nacos-Discovery Code ,  I find that nacosRibbon do not extension `BaseLoadBalancer` , So The `NacosServerList` depend on `ServerListUpdater` update the ServerList , so when I need  when the `SpringBootApplication `  running as well as initialized the serverlist , how can I do 。 I can use only below idea to resolve the problem:
```
 ribbon.ServerListRefreshInterval = 5000
```
so when program started , I immediately visit the server 。it wastes a lot of time。

but  I found `ZookeeperDiscoveryClient` implements this ：
```java
public class DependenciesBasedLoadBalancer extends DynamicServerListLoadBalancer {

	private static final Log log = LogFactory.getLog(DependenciesBasedLoadBalancer.class);

	private final Map<String, IRule> ruleCache = new ConcurrentHashMap<>();

	private final ZookeeperDependencies zookeeperDependencies;

	public DependenciesBasedLoadBalancer(ZookeeperDependencies zookeeperDependencies, ServerList<?> serverList, IClientConfig config, IPing iPing) {
		super(config);
		this.zookeeperDependencies = zookeeperDependencies;
		setServersList(serverList.getInitialListOfServers());
		setPing(iPing);
		setServerListImpl(serverList);
	}
  // .....

``` 
---
请问nacos ribbon启动时 是否没有调用nacosServerList的初始化方法，这样我只能依赖于设置更新时间来缩短获取服务的时间，否则我可能程序启动时，立刻访问会花很长时间，可否考虑实现以下此功能，或者有什么好的建议

**Comment by fangjian0423** [comment]
Thanks for your suggestion.

It sounds reasonable. Could you please help to contribute it ?

**Comment by flystar32** [comment]
ribbon.eager-load.enabled=true
ribbon.eager-load.clients=`your service name`
