### ISSUE TITLE
[ANS] The service always turns down unexpectedly after several minutes locally

### ISSUE THREAD

**Issue by liuninglin** [spring-cloud-incubator/spring-cloud-alibaba#532]
service a:
    spring boot: 2.0.6.RELEASE
    spring cloud: Finchley.SR2
    acm: 2.1.0.BUILD-SNAPSHOT
    ans: 2.1.0.BUILD-SNAPSHOT
service b:
    spring boot: 1.5.10.RELEASE
    spring cloud: Edgware.SR3
    acm: 0.1.1.RELEASE
    ans: 0.1.1.RELEASE
local edas:  edas-lite-configcenter.tar.gz

Two services above which are registered in ANS(local mode), and they always turn down after several minutes unexpectedly. After that, these two services disappeared from EDAS Configuration Center(local mode) when I checked the status on my browser. Besides this, I cannot acquire any detail information for these two dead services.

So, I deeply concern that this unexpected issue will appear again in EDAS after I deploy my services on EDAS Production Environment.

**Comment by liuninglin** [comment]
By the way, I changed the discovery server from ANS to Consul, then this issue didn't appear again.

**Comment by fangjian0423** [comment]
service a build with spring boot 2.0.6.RELEASE and spring cloud Finchley, but ans and acm is 2.1.0.BUILD-SNAPSHOT version.

2.1.0.BUILD-SNAPSHOT is build on spring cloud greenwich and spring boot 2.1.x.

So you could use acm and ans of 0.2.1.RELEASE version when run service a.

Spring Cloud Release Trains:

Release Train | Boot Version
-- | --
Greenwich | 2.1.x
Finchley | 2.0.x
Edgware | 1.5.x
Dalston | 1.5.x

refer: [Spring Cloud ](http://spring.io/projects/spring-cloud#release-trains)

**Comment by fangjian0423** [comment]
ANS Starter will be in maintenance mode in the future and it is recommend to use Nacos to replace it.

Next version ACM is compatible with Nacos.

**Comment by flystar32** [comment]
@liuninglin “they always turn down after several minutes unexpectedly” , You mean your java progress turn down ? or  just can't find service in edas-lite-configcenter dashboard?

**Comment by liuninglin** [comment]
@flystar32 
1.  Accessing my service through my browser and showing **"Error 500, The Host is down"** in my browser. After that, I refreshed that page, then my browser displayed a successful page. But it displayed error page again just after I refreshed again. So the successful page and the error page took turns by clicking the refresh button in my browser. 
2. My services just disappeared when my browser showing an error page. My services just came out after refreshing my dashboard page.

So, all phenomena above are so weird.

**Comment by liuninglin** [comment]
@flystar32 And I really concern about that this kind of annoying issues will turn out in Ali Cloud EDAS(version serverless)

**Comment by flystar32** [comment]
No one who is using EDAS submit this issue that Application turn down automatically, Could you please help to provide an Minimal, Complete, and Verifiable example ?

**Comment by liuninglin** [comment]
1.Browser showing error
https://drive.google.com/file/d/1EEbX2-LeF3LPAkQa_Zy9qk2KXd1nfjkl/view

2.Local edas-lite-configcenter 
https://drive.google.com/file/d/1NA_4-VFuWCy5akBjOoanv8Rc9j161sx9/view

**Comment by flystar32** [comment]
@liuninglin 搜索这个钉钉群号，加钉钉群 23335402
