### ISSUE TITLE
The method in 0.1.1.RELEASE-nacos-discovery refers to Spring-commons method for version 1.3.5 causing an error

### ISSUE THREAD

**Issue by seapeak007** [spring-cloud-incubator/spring-cloud-alibaba#535]
Describe what happened (or what feature you want)
0.1.1.RELEASE nacos-discovery 调用Spring-commons的方法为2.0以上的jar包中的
Caused by: java.lang.NoSuchMethodError: org.springframework.cloud.client.serviceregistry.AbstractAutoServiceRegistration.(Lorg/springframework/cloud/client/serviceregistry/ServiceRegistry;Lorg/springframework/cloud/client/serviceregistry/AutoServiceRegistrationProperties;)V

Describe what you expected to happen
NacosAutoServiceRegistration构造方法中super(serviceRegistry, autoServiceRegistrationProperties);为2.0的commons中的，与Spring cloud的依赖版本冲突

How to reproduce it (as minimally and precisely as possible)
Tell us your environment
Java 1.8 Spring cloud Dalston.SR1

Anything else we need to know?

**Comment by flystar32** [comment]
NacosAutoServiceRegistration  in  version  0.1.1.RELEASE rely on spring-cloud-commons  1.3.5.RELEASE which is compatible with Edgware. see more information in 版本说明 https://github.com/spring-cloud-incubator/spring-cloud-alibaba/wiki/%E7%89%88%E6%9C%AC%E8%AF%B4%E6%98%8E

**Comment by seapeak007** [comment]
升级cloud版本到Edgware.SR5解决该问题
