### ISSUE TITLE
Namespace-based registration service failed to isolate

### ISSUE THREAD

**Issue by libinwalan** [spring-cloud-incubator/spring-cloud-alibaba#544]
我用nacos0.9和springcloud-alibaba做多环境服务注册
配置为 spring.cloud.nacos.discovery.namespace=对应的命名空间ID
但是服务注册上去都还是在public 下。额外说一下多环境配置是正确的。截图如下：
![image](https://user-images.githubusercontent.com/6059942/55923710-2713a180-5c39-11e9-88dd-0752d51d39b0.png)

**Comment by fangjian0423** [comment]
Please refer https://github.com/spring-cloud-incubator/spring-cloud-alibaba/issues/452.

**Comment by dushitaoyuan** [comment]
me,too!but, i change my config ,like tihis: spring.cloud.nacos.discovery.namespace=namespaceId ,it works
nacos discovery does not support group
