### ISSUE TITLE
统一各组件dubbo版本

### ISSUE THREAD

**Issue by mostcool** [spring-cloud-incubator/spring-cloud-alibaba#560]
spring-cloud-alibaba-sentinel 使用的是alibaba-dubbo-2.6.5，但它已经兼容apache-dubbo-2.7.1了。
spring-cloud-alibaba-dubbo用的是apache-dubbo-2.7.1。

**Comment by fangjian0423** [comment]
Yes, see 0e6565b461d619d2b7645f96f8fcc0e1dfd6c297.
