### ISSUE TITLE
有没有spring.cloud.sentinel.heartbeat.client.ip配置项？或者为什么不提供这个配置？

### ISSUE THREAD

**Issue by haoleng** [spring-cloud-incubator/spring-cloud-alibaba#563]
最近在使用springcloud-sentinel做限流相关项目，本地单独跑都没问题。但是打成镜像在docker跑就有比较多的问题。
查询了很多网上的资料，也看了sentinel关于docker相关问题的issue
目前的方案是在启动命令加上-Dcsp.sentinel.heartbeat.client.ip=x.x.x.x
这种方式确定sentinel client端的外网ip否则还是取hostip
看了spring-cloud-alibaba-sentinel的SentinelAutoConfiguration.java源码里面只有针对transport.dashboard和port的配置读取，却没有heartbeat.client.ip的配置读取。
虽然现在启动命令加参数可以解决，但是确实没有相关配置来得方便。
后续是否有加上这个配置的计划？或者已经有了更方便的解决方案？

spring.cloud.sentinel.transport.dashboard = x
spring.cloud.sentinel.transport.port = x
#spring.cloud.sentinel.heartbeat.client.ip = x | 是否有类似这种配置？

**Comment by fangjian0423** [comment]
It has been included in 2.1.0 version and will be released soon.

You could find it in https://github.com/spring-cloud-incubator/spring-cloud-alibaba/wiki/Sentinel#more.

**Comment by haoleng** [comment]
@fangjian0423  thanks

**Comment by zhangdxchn** [comment]
docker + springboot  连接 docker + sentinel 项目，经过验证：
方案一，docker启动jar 中加`JAVA_OPTS=-Dcsp.sentinel.heartbeat.client.ip=XXX`，可行。
方案二，springboot 配置文件加 `spring.cloud.sentinel.transport.client-ip=XXX`，可行。
