### ISSUE TITLE
Sentinel Dashboard ip show 0.0.0.1

### ISSUE THREAD

**Issue by w5185552** [spring-cloud-incubator/spring-cloud-alibaba#566]
两台机器一台部署Sentinel,另外一台部署应用.Sentinel控制台显示应用名称，但是ip为0.0.0.1。Sentinel控制台实时监控也显示为空

One of the two machines deploys Sentinel and the other deploys an application. The Sentinel console displays the application name, but the IP is 0.0.0.1. Real-time monitoring is also shown to be empty

**Comment by fangjian0423** [comment]
You could refer: https://github.com/alibaba/Sentinel/issues/314

**Comment by w5185552** [comment]
thinks
