### ISSUE TITLE
can not register a nacos server

### ISSUE THREAD

**Issue by GreyZeng** [spring-cloud-incubator/spring-cloud-alibaba#567]
我们鼓励使用英文，如果不能直接使用，可以使用翻译软件，您仍旧可以保留中文原文。
We recommend using English. If you are non-native English speaker, you can use the translation software. 

**Which Component**

Nacos Discovery

**Describe the bug**

We Use ：
Spring Cloud Finchley.RELEASE
Spring Cloud Alibaba 0.2.1.RELEASE
Nacos Server 1.0.0 RELEASE

We add dependency

<dependency>
        <groupId>org.springframework.cloud</groupId>
       <artifactId>spring-cloud-starter-alibaba-nacos-discovery</artifactId>
</dependency>

FROM  Spring Cloud Alibaba 0.2.1.RELEASE

but we CAN NOT register a service in nacos server

**Comment by fangjian0423** [comment]
Pls provide your configuration file: application.properties or application.yaml and startup log.

**Comment by GreyZeng** [comment]
sorry ，we found the problem and fixed it， that is not a bug
