### ISSUE TITLE
The json of flow-rule from sentinel-dashboard has extra properties like id, app, port, gmtCreate but these can't parse in sca

### ISSUE THREAD

**Issue by sundong1982** [spring-cloud-incubator/spring-cloud-alibaba#569]
should set `FAIL_ON_UNKNOWN_PROPERTIES` of `ObjectMapper` to false.

**Comment by fangjian0423** [comment]
These properties from `FlowRuleEntity` of Sentinel dashboard.

**Comment by sundong1982** [comment]
暂时的解决方法，FlowRuleEntity类的这几个属性加上@JSONField(serialize = false)
`@JSONField(serialize = false)
    private Long id;
    @JSONField(serialize = false)
    private String app;
    @JSONField(serialize = false)
    private String ip;
    @JSONField(serialize = false)
    private Integer port;
    @JSONField(serialize = false)
    private Date gmtCreate;
    @JSONField(serialize = false)
    private Date gmtModified;`

**Comment by sundong1982** [comment]
感谢洛夜的帮助:)

**Comment by fangjian0423** [comment]
You also could using custom converter in `AbstractDataSourceProperties#converterClass` to replace of defaultConverter like this:

```properties
spring.cloud.sentinel.datasource.ds1.file.file=classpath: flowrule.json
spring.cloud.sentinel.datasource.ds1.file.data-type=json
spring.cloud.sentinel.datasource.ds1.file.rule-type=flow
spring.cloud.sentinel.datasource.ds1.file.converter-class=fullNameOfYourCustomConverterClass
```

**Comment by HeWeiGitHub** [comment]
老大们都很牛逼啊
