### ISSUE TITLE
nacos client 从 0.9.0升级到 1.0.0出错

### ISSUE THREAD

**Issue by WunHwanTseng** [spring-cloud-incubator/spring-cloud-alibaba#571]
java.lang.IllegalStateException: failed to req API:/nacos/v1/ns/service/list after all servers([ip:8848]) tried: failed to req API:http://ip:8848/nacos/v1/ns/service/list. code:503 msg: server is DOWN now, please try again later!

升级到spring cloud alibaba 0.9.0，nacos-client 使用1.0.0发现无法注册的问题

**Comment by ShZhengqin** [comment]
@WunHwanTseng , 后来你这个问题解决了吗?

**Comment by hipopular** [comment]
这问题现在咋还有呢？
