### ISSUE TITLE
The push configuration did not take effect

### ISSUE THREAD

**Issue by 1346735074** [spring-cloud-incubator/spring-cloud-alibaba#573]
nacos spring-cloud-starter-alibaba-nacos-config

According to the official example
The startup configuration is enabled but the modification push configuration is not
![image](https://user-images.githubusercontent.com/36881032/56482158-2b6f7280-64f5-11e9-87ec-08253e675416.png)
![image](https://user-images.githubusercontent.com/36881032/56482176-4a6e0480-64f5-11e9-89ea-d0ba138ca931.png)

Official example website
https://nacos.io/zh-cn/docs/quick-start-spring-cloud.html

**Comment by fangjian0423** [comment]
please refer https://github.com/spring-cloud-incubator/spring-cloud-alibaba/wiki/Nacos-config.

**Comment by 1346735074** [comment]
![image](https://user-images.githubusercontent.com/36881032/56497152-039d0080-652f-11e9-9930-ef85f6bffebb.png)
Write the code as shown in the link
It's still available on startup
Push not available
![image](https://user-images.githubusercontent.com/36881032/56497189-27604680-652f-11e9-81be-34c99643157e.png)

**Comment by 1346735074** [comment]
![image](https://user-images.githubusercontent.com/36881032/56497959-48766680-6532-11e9-8b3e-ca9a13f595b9.png)
![image](https://user-images.githubusercontent.com/36881032/56497963-4ca28400-6532-11e9-9c56-781ba45e6580.png)
Multi-configuration also does not work with push

**Comment by fangjian0423** [comment]
Please provide your configuration properties like `application.properties`, `bootstrap.properties` and your version of nacos starter, springboot version or your pom.

**Comment by 1346735074** [comment]
```
    <parent>
        <groupId>org.springframework.cloud</groupId>
        <artifactId>spring-cloud-build</artifactId>
        <version>2.1.3.RELEASE</version>
        <relativePath/>
    </parent>

    <dependencyManagement>

        <dependencies>

            <dependency>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-dependencies</artifactId>
                <version>${spring-boot.version}</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>

            <dependency>
                <groupId>org.springframework.cloud</groupId>
                <artifactId>spring-cloud-alibaba-dependencies</artifactId>
                <version>0.2.2.RELEASE</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>

            <dependency>
                <groupId>org.springframework.cloud</groupId>
                <artifactId>spring-cloud-alibaba-nacos-config</artifactId>
            </dependency>

        </dependencies>

    </dependencyManagement>
```

**Comment by 1346735074** [comment]
![image](https://user-images.githubusercontent.com/36881032/56498953-b7ee5500-6536-11e9-82a0-68674562ccab.png)
Breakpoint debugging
The update triggers this method
But springboot doesn't appear to have been updated

**Comment by fangjian0423** [comment]
nacos starter 0.2.2 is compatible with Spring Boot 2.0.X, refer https://github.com/spring-cloud-incubator/spring-cloud-alibaba/wiki/%E7%89%88%E6%9C%AC%E8%AF%B4%E6%98%8E.

**Comment by 1346735074** [comment]
good thank you
