### ISSUE TITLE
Why spring cloud gateway Response status 404

### ISSUE THREAD

**Issue by seas521** [spring-cloud-incubator/spring-cloud-alibaba#574]
I updated spring-cloud-alibab to 0.2.2.RELEASE，then requested my gateway service ，
all the requests Response status 404 ，but before updating it worked well.

**Comment by seas521** [comment]
any one?

**Comment by fangjian0423** [comment]
Refer https://github.com/spring-cloud-incubator/spring-cloud-alibaba/tree/master/spring-cloud-alibaba-examples/nacos-example/nacos-gateway-example.

**Comment by seas521** [comment]
> Refer https://github.com/spring-cloud-incubator/spring-cloud-alibaba/tree/master/spring-cloud-alibaba-examples/nacos-example/nacos-gateway-example.

thx，it works by updating related version
