### ISSUE TITLE
sentinel-core-example

### ISSUE THREAD

**Issue by bxhxnon** [spring-cloud-incubator/spring-cloud-alibaba#576]
启动案列的时候总是报
Error:java: Annotation processing is not supported for module cycles. Please ensure that all modules from cycle [spring-cloud-alibaba-sentinel,spring-cloud-starter-alibaba-sentinel] are excluded from annotation processing

**Comment by fangjian0423** [comment]
I think there is something wrong with your IDE. You could refer https://github.com/mplushnikov/lombok-intellij-plugin/issues/161.

**Comment by bxhxnon** [comment]
嗯 谢谢   是idea的问题
