### ISSUE TITLE
Can Supprot Feign ?

### ISSUE THREAD

**Issue by xiejiashuai** [spring-cloud-incubator/spring-cloud-alibaba#6]
RestTemplate 使用起来太不友好了，不如Feign方便。可否考虑支持下Feign。

Spring Framework RestTemplate is not convenient when used , can consider supproting Feign.

**Comment by flystar32** [comment]
Sentinel 目前对于有线程切换的行为处理还不大完善，待 Sentinel 完善支持后会评估支持方案。

Sentinel currently does not have a good deal of behavior for thread switching, we will evaluate it after Sentinel supports this scenario.

**Comment by 410919244** [comment]
心累。。。一群中国人用英文沟通。我们这种菜鸟英文不好看起来真心心累🤨
