### ISSUE TITLE
Why am i use @DubboTransported FeignClient or RestTemplate instead of call @Reference directly?

### ISSUE THREAD

**Issue by moonfruit** [spring-cloud-incubator/spring-cloud-alibaba#602]
**Which Component**
`spring-cloud-alibaba-dubbo`

**Describe what problem you have encountered**
Now `spring-cloud-alibaba` support `dubbo`, that is good.
But I am still have a question about `@DubboTransported`.

If I use both `spring-cloud`and `dubbo` in my project, why should I call a `dubbo` service via `@DubboTransported`'s `@FeignClient` or `RestTemplate`? Why not call the instance with `@Reference` directly?

Can `@DubboTransported`'s client benefit from `spring-cloud-loadbalancer` or `spring-cloud-circuitbreaker` or `spring-cloud-sleuth`?

Does `spring-cloud-alibaba-dubbo` simply add a `spring-cloud` registry for `dubbo`?

**Comment by mercyblitz** [comment]
Using `@Reference` is welcome, however, the legacy applications may use a lot of `@FeignClient`, thus `@DubboTransported` is just used to integrate from Spring Cloud Open Feign to Dubbo in the middle stage.

**Comment by moonfruit** [comment]
So, if I want expose a service to `dubbo` and `spring-cloud`, for a new project it's best to use `@Reference` instead of `@DubboTransported`?

**Comment by moonfruit** [comment]
Is that means for a new project that is without historical burden `spring-cloud-alibaba-dubbo` only provide `spring-cloud` registry for `dubbo`?

**Comment by mercyblitz** [comment]
> So, if I want expose a service to `dubbo` and `spring-cloud`, for a new project it's best to use `@Reference` instead of `@DubboTransported`?

Yes, you are right

**Comment by mercyblitz** [comment]
> Is that means for a new project that is without historical burden `spring-cloud-alibaba-dubbo` only provide `spring-cloud` registry for `dubbo`?

For now, `spring-cloud-alibaba-dubbo` only works Spring Cloud registry, and next one will work both.
However, we recommend the developers to use Spring Cloud registry, the Dubbo legacy registry is used for integration.

**Comment by moonfruit** [comment]
But now the `spring-cloud` registry is a little inconvenient than the `dubbo` native registry, that I must specific `dubbo.cloud.subscribed-services`. Is there any way to go around?

**Comment by mercyblitz** [comment]
> But now the `spring-cloud` registry is a little inconvenient than the `dubbo` native registry,

I will remove this `spring-cloud` property, please refer to https://github.com/spring-cloud-incubator/spring-cloud-alibaba/issues/592

> that I must specific `dubbo.cloud.subscribed-services`. Is there any way to go around?

`dubbo.cloud.subscribed-services` could be blank, whose default value "*", it will subscribe to all services that may be unnecessary.

**Comment by moonfruit** [comment]
> dubbo.cloud.subscribed-services could be blank, whose default value "*", it will subscribe to all services that may be unnecessary.

But `dubbo` native registry will only subscribe to the services it needs without any configuration.
