### ISSUE TITLE
qos-enable = false 无法生效

### ISSUE THREAD

**Issue by TulleyT** [spring-cloud-incubator/spring-cloud-alibaba#604]
我试图配置qos-enable = false 消除 多项目启动时的端口冲突,但是无法生效 无论是在yml还是properties 都不行
I tried to configure qos-enable = false to eliminate port conflicts when multi-project startup, but it didn't work. It doesn't work in yml or properties.

**Comment by sunkx2015** [comment]
Maybe you can try it.  dubbo.application.qos.enable = false

**Comment by mercyblitz** [comment]
It's an issue on Dubbo, please ignore, it does not block running.
