### ISSUE TITLE
如何在springboot 或者spring cloud alibaba 中使用hessian协议 How to use the hessian protocol in springboot or spring cloud alibaba

### ISSUE THREAD

**Issue by TulleyT** [spring-cloud-incubator/spring-cloud-alibaba#605]
找不到一个在springboot或者springcloud alibaba中集成Dubbo 并使用hessian的案例,如果我需要在springboot 或者 spring cloud alibaba 中使用dubbo并且使用hessain协议 我应该注意哪些地方
Can't find a example where Dubbo is integrated in springboot or springcloud alibaba and hessian is used. If I need to use dubbo in springboot or spring cloud alibaba and use hessain protocol, what should I pay attention to?

**Comment by mercyblitz** [comment]
You could set the externalized property `dubbo.protocol.serialization=hessian2` in your application.properties or yaml variant.

**Comment by hzdjulytech** [comment]
+1
