### ISSUE TITLE
端口被占用依然启动成功

### ISSUE THREAD

**Issue by wenfer** [spring-cloud-incubator/spring-cloud-alibaba#612]
address  already use 。 starting should be fail in spring cloud project

**Comment by flystar32** [comment]
I don't think this has anything to do with spring cloud alibaba

**Comment by wenfer** [comment]
i think  dubbo don't need port , so dubbo can started。but service in spring cloud is restservice ，so ,that should be fail

**Comment by wenfer** [comment]
this issue in  spring-cloud-dubbo

**Comment by mercyblitz** [comment]
Do not worry, it's a dubbo issue : https://github.com/apache/incubator-dubbo/issues/3958
