### ISSUE TITLE
spring cloud gateway + zipkin failed to update serviceName

### ISSUE THREAD

**Issue by WunHwanTseng** [spring-cloud-incubator/spring-cloud-alibaba#617]
version：spring cloud alibaba 0.9.0.RELEASE，spring cloud 2.1.0.RELEASE，Spring Boot 2.1.3.RELEASE
logs：
![image](https://user-images.githubusercontent.com/22773392/56878997-50ca2680-6a89-11e9-825a-9f816be39766.png)
![image](https://user-images.githubusercontent.com/22773392/56879016-6dfef500-6a89-11e9-808c-861e5c8d9846.png)

**Comment by flystar32** [comment]
the log says `service not found`

**Comment by WunHwanTseng** [comment]
@flystar32 but when i delete zipkin dependency, it dont happen

**Comment by 2538552544** [comment]
我也是这样的问题  引入zipkin运行没问题 调用Dubbo的RPC接口多次访问时一直刷这个错误

**Comment by flystar32** [comment]
@WunHwanTseng @2538552544 refer to this https://github.com/spring-cloud-incubator/spring-cloud-alibaba/issues/353

**Comment by WunHwanTseng** [comment]
@flystar32 i set spring.zipkin.discovery-client-enabled=false , but nacos error logs again

**Comment by flystar32** [comment]
I don't think this is a issue of spring cloud alibaba or nacos.
the logs means when it try to connect to zipkin server, zipkin treat the IP as a service name that has registered in spring cloud registry server. This is an issue of zipkin, you should submit an issue to zipkin.

**Comment by WunHwanTseng** [comment]
@flystar32 yeap,when i use application name,its successful.thx

**Comment by eacdy** [comment]
这是个Spring Cloud Sleuth的Bug，我这篇文章详细分析了原因以及规避方案：
[解决Spring Cloud Alibaba/Spring Cloud整合Zipkin之后的报错问题](http://www.itmuch.com/spring-cloud-alibaba/spring-cloud-alibaba-zipkin-nacos-exception/)
