### ISSUE TITLE
DubboGenericServiceFactory#cache  ConcurrentMap cache is not used？

### ISSUE THREAD

**Issue by cynicgit** [spring-cloud-incubator/spring-cloud-alibaba#620]
private ReferenceBean<GenericService> build(String interfaceName, String version, String group,
                                                Map<String, Object> dubboTranslatedAttributes) {
        Integer key = Objects.hash(interfaceName, version, group, dubboTranslatedAttributes);
        ReferenceBean<GenericService> referenceBean = cache.get(key);
        if (referenceBean == null) {
            referenceBean = new ReferenceBean<>();
            referenceBean.setGeneric(true);
            referenceBean.setInterface(interfaceName);
            referenceBean.setVersion(version);
            referenceBean.setGroup(group);
            bindReferenceBean(referenceBean, dubboTranslatedAttributes);
        }
        return referenceBean;
    }
cache.get(key)  is always return null，cache.put() not called in this class.

**Comment by mercyblitz** [comment]
Yes, the latest code has fixed this issue. Please see the master code.
