### ISSUE TITLE
How to get all registered services in nacos.

### ISSUE THREAD

**Issue by Ambitie** [spring-cloud-incubator/spring-cloud-alibaba#625]
How to get all registered services in nacos
如何在代码中获取全部的注册服务。

是这样的：
我可能注册了一类服务，比如名称叫 xxxx-login ,yyy-login, zzz-login,
这三个服务分属于不同的系统，随着业务的扩大，以后还有可能产生aaa-login
bbb-login。我怎么获取全部的服务名称？

**Comment by fangjian0423** [comment]
`NamingService#ListView<String> getServicesOfServer(int pageNo, int pageSize) throws NacosException;`

You could get `NamingService` by `NacosDiscoveryProperties#namingServiceInstance`.

**Comment by Ambitie** [comment]
@fangjian0423 thank you very much
