### ISSUE TITLE
Feign with Sentinel in Inheritance interface will throw NPE

### ISSUE THREAD

**Issue by george510257** [spring-cloud-incubator/spring-cloud-alibaba#626]
当spring cloud 中使用 openfeign方式调用时，使用feign的继承特性。在使用Sentinel作为熔断限流时会导致MethodMetadata获取值为null。

详细代码参见：https://gitee.com/george510257/csg-parent.git

![image](https://user-images.githubusercontent.com/4056671/57065877-592a9780-6cfd-11e9-8b9e-96d9a25017ba.png)
![image](https://user-images.githubusercontent.com/4056671/57065889-62b3ff80-6cfd-11e9-95de-56a4efe17962.png)

版本是用的0.9.0.RELEASE

**Comment by george510257** [comment]
![image](https://user-images.githubusercontent.com/4056671/57066115-ecfc6380-6cfd-11e9-8ca2-1d67b91c91e5.png)

**Comment by george510257** [comment]
![image](https://user-images.githubusercontent.com/4056671/57114496-0f34c680-6d7c-11e9-9ead-a5f1994a7094.png)
method 拿到的是接口RefactorDemoClient的信息，不是RefactorDemoService
![image](https://user-images.githubusercontent.com/4056671/57114569-6aff4f80-6d7c-11e9-8182-9e2231802ac8.png)

**Comment by george510257** [comment]
修改方案如下请参考。
![image](https://user-images.githubusercontent.com/4056671/57116029-1f9d6f00-6d85-11e9-943a-55a17e98e212.png)

**Comment by fangjian0423** [comment]
hi @george510257 

Thanks for the suggestion. I tries it and runs well, could you please create a pull request to fix it and add some test cases?

**Comment by george510257** [comment]
@fangjian0423 已提交相关代码。

**Comment by fangjian0423** [comment]
Could you please add some test cases for it in `SentinelFeignTests`?

**Comment by george510257** [comment]
@fangjian0423 好的，我晚上回家加test cases 提交上来，需要新增一个pull requests吗？

**Comment by fangjian0423** [comment]
> @fangjian0423 好的，我晚上回家加test cases 提交上来，需要新增一个pull requests吗？

在原先那个 pr 对应的分支上提交即可，会自动关联到以及创建的 pull request 上。

Submit on the branch corresponding to the original PR and automatically associate it with the pull request created.

**Comment by tuser4198** [comment]
@fangjian0423 您好，这个bug会随着0.9.1版本的发布修复吗？

**Comment by fangjian0423** [comment]
> @fangjian0423 您好，这个bug会随着0.9.1版本的发布修复吗？

Yes, we will try to release new version at the end of this month.

--------

是的，我们会尽量在月底发布新的版本。

**Comment by tuser4198** [comment]
So dear, When to release 0.9.1 ? Will it support sentinel 1.6.0?

**Comment by fangjian0423** [comment]
@tuser4198 0.9.1 will be released these two weeks and sentinel version is 1.6.0. You could try it with 0.9.1.BUILD-SNAPSHOT.

**Comment by fangjian0423** [comment]
sorry, sentinel version is 1.6.1
