### ISSUE TITLE
File and nacos always Failed when I bind properties to sentinel rule-type

### ISSUE THREAD

**Issue by xiaweiasd** [spring-cloud-incubator/spring-cloud-alibaba#627]
#File
spring.cloud.sentinel.datasource.ds2.file.file=classpath: flowrule.json
spring.cloud.sentinel.datasource.ds2.file.data-type=json
spring.cloud.sentinel.datasource.ds2.file.rule-type=flow

#Nacos
spring.cloud.sentinel.datasource.ds2.nacos.file=classpath: flowrule.json
spring.cloud.sentinel.datasource.ds2.nacos.dataId=sentinel
spring.cloud.sentinel.datasource.ds2.nacos.groupId=DEFAULT_GROUP
spring.cloud.sentinel.datasource.ds2.nacos.data-type=json
spring.cloud.sentinel.datasource.ds2.nacos.rule-type=flow

Failed to bind properties under 'spring.cloud.sentinel.datasource.ds2.file.rule-type' to org.springframework.cloud.alibaba.sentinel.datasource.RuleType:

    Property: spring.cloud.sentinel.datasource.ds2.file.rule-type
    Value: flow
    Origin: class path resource [application.properties]:5:53
    Reason: 2

I was troubled with this for a long time. God help me!!!

**Comment by xiaweiasd** [comment]
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>
	<groupId>com.example.sc</groupId>
	<artifactId>sctest1</artifactId>
	<version>0.0.1-SNAPSHOT</version>
	<name>sctest1</name>
	<description>Demo project for Spring Boot</description>
	<packaging>pom</packaging>

	<properties>
		<spring-boot.version>2.0.9.RELEASE</spring-boot.version>
		<spring-cloud.version>Finchley.RELEASE</spring-cloud.version>
		<spring-clousd-alibaba-dependencies.version>0.2.2.RELEASE</spring-clousd-alibaba-dependencies.version>
		<maven.compiler.source>1.8</maven.compiler.source>
		<maven.compiler.target>1.8</maven.compiler.target>
	</properties>

	<dependencyManagement>
		<dependencies>
			<dependency>
				<groupId>org.springframework.boot</groupId>
				<artifactId>spring-boot-dependencies</artifactId>
				<version>${spring-boot.version}</version>
				<type>pom</type>
				<scope>import</scope>
			</dependency>
			<dependency>
				<groupId>org.springframework.cloud</groupId>
				<artifactId>spring-cloud-dependencies</artifactId>
				<version>${spring-cloud.version}</version>
				<type>pom</type>
				<scope>import</scope>
			</dependency>



		</dependencies>
	</dependencyManagement>

	<dependencies>

		<dependency>
			<groupId>org.springframework.cloud</groupId>
			<artifactId>spring-cloud-starter-alibaba-sentinel</artifactId>
			<version>0.2.2.RELEASE</version>
		</dependency>

		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-actuator</artifactId>
		</dependency>

		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-web</artifactId>
		</dependency>

	</dependencies>
	


</project>

**Comment by fangjian0423** [comment]
There can't be exist additional properties in file or nacos with the sentinel rules.

Refer [example](https://github.com/spring-cloud-incubator/spring-cloud-alibaba/tree/master/spring-cloud-alibaba-examples/sentinel-example/sentinel-core-example) and other issue https://github.com/spring-cloud-incubator/spring-cloud-alibaba/issues/569.

It can be exist additional properties in next version.
