### ISSUE TITLE
使用Spring Clout Gateway 时 RibbonLoadBalancerClient无法获取scheme导至https服务无法转发,请问怎么破

### ISSUE THREAD

**Issue by 948290** [spring-cloud-incubator/spring-cloud-alibaba#634]
使用
```
spring boot 2.1.4.RELEASE
spring cloud Greenwich.RELEASE(2.1.0.RELEASE)
spring-cloud-alibaba 0.9.0.RELEASE
NACOS 1.0
```
服务注册正常
在NACOS的服务详情中元数据有
```
reserved.register.source=SPRING_CLOUD
secure=true
```
但是spring cloud gateway运行后,调试跟踪到
```
RibbonLoadBalancerClient
的
public Mono<Void> filter(ServerWebExchange exchange, GatewayFilterChain chain)
方法的
final ServiceInstance instance = choose(exchange);
```
instance中Secure为false所以只会以http型式转发.......不知道为什么 choose(exchange);方法获取的服务信息没有scheme并且Secure也为false

**Comment by fangjian0423** [comment]
I think this is a spring cloud gateway issue or spring cloud issue(about secure service registry).

**Comment by flystar32** [comment]
sorry, It's my mistake, I should impl  Ribbon ServerIntrospector in nacos discovery.

**Comment by fangjian0423** [comment]
refer #650
