### ISSUE TITLE
Does it support setting default FallBackFactory or FallBack ?

### ISSUE THREAD

**Issue by lw5946** [spring-cloud-incubator/spring-cloud-alibaba#639]
我们鼓励使用英文，如果不能直接使用，可以使用翻译软件，您仍旧可以保留中文原文。
We recommend using English. If you are non-native English speaker, you can use the translation software. 

**Which Component**
eg. Sentinel

**Is your feature request related to a problem? Please describe.**
I want to set a default FallBackFactory or FallBack instead of having to set fallback for every sentinel process.

**Describe the solution you'd like**
some features are contained in HystrixFeign.java of feign-hystrix.jar
```java

    public <T> T target(Target<T> target, T fallback) {
      return build(fallback != null ? new FallbackFactory.Default<T>(fallback) : null)
          .newInstance(target);
    }

    public <T> T target(Target<T> target, FallbackFactory<? extends T> fallbackFactory) {
      return build(fallbackFactory).newInstance(target);
    }
```

**Comment by fangjian0423** [comment]
Hi .

What do you mean about the default FallBackFactory or FallBack? 

The code snippet like this won't use custom `FallbackFactory`.

```
@FeignClient(name = "echo-service")
public interface EchoService {
	...
}

@Bean
public FallbackFactory fallbackFactory() {
	return new feign.hystrix.FallbackFactory() {

		@Override
		public Object create(Throwable cause) {
			return null;
		}
	};
}
```

**Comment by fangjian0423** [comment]
Could you please provide some code snippets to describe setting hystrix default FallBackFactory or FallBack?

**Comment by lw5946** [comment]
I want to user a custom FallBackFactory instead of the default FallBackFactory provided by FeignClientFactoryBean. In this way, I can return information in a specific format for each Sentinel resource.

In this way, I can return information in a specific format for each Sentinel application.

In SentinelFeign.java file, the code is as follows:
```java
if (void.class != fallback) {
	fallbackInstance = getFromContext(name, "fallback", fallback,
			target.type());
	return new SentinelInvocationHandler(target, dispatch,
			new FallbackFactory.Default(fallbackInstance));
}
if (void.class != fallbackFactory) {
	fallbackFactoryInstance = (FallbackFactory) getFromContext(name,
			"fallbackFactory", fallbackFactory,
			FallbackFactory.class);
	return new SentinelInvocationHandler(target, dispatch,
			fallbackFactoryInstance);
}
```
How do I operate to make here used a custom FallbackFactory instead of void. class?

**Comment by fangjian0423** [comment]
Just like this:

```java
@FeignClient(name = "service-provider", fallbackFactory = YourFallbackFactory.class, configuration = YourConfiguration.class)
public interface EchoService {
	...
}
```

**Comment by lw5946** [comment]
Could i config a default FallBackFactory in one File? 

I mean that I want to use a custom FallBackFactory, but I don't need to specify the fallBackFactory attribute in every FeignClient.

I hope my meaning is clear enough for you to understand.

**Comment by lw5946** [comment]
Hystrix can support the functions I need.  The code snippet like this:
```java
// HystrixFeign.java
    /**
     * @see #target(Class, String, Object)
     */
    public <T> T target(Target<T> target, T fallback) {
      return build(fallback != null ? new FallbackFactory.Default<T>(fallback) : null)
          .newInstance(target);
    }

    /**
     * @see #target(Class, String, FallbackFactory)
     */
    public <T> T target(Target<T> target, FallbackFactory<? extends T> fallbackFactory) {
      return build(fallbackFactory).newInstance(target);
    }
```

Is Sentinel not planning to support this feature?

**Comment by fangjian0423** [comment]
@lw5946 

Could you please provide a project to show how hystrix support default FallBackFactory?

**Comment by lw5946** [comment]
Oh, sorry, Hystrix doesn't seem to support this feature, I just saw it implemented in pigx in a fantastic way using Hystrix.

**Comment by fangjian0423** [comment]
Thanks for you suggestion. 

If you find some features that sentinel do not support, just create issue and we will handle it soon.
