### ISSUE TITLE
dubbo-registry-nacos‘s dependency

### ISSUE THREAD

**Issue by wzlee** [spring-cloud-incubator/spring-cloud-alibaba#645]
**Which Component**
The dubbo-registry-nacos's groupId still is 'com.alibaba' in 'spring-cloud-alibaba-dependencies' module, please add the groupId 'org.apache.dubbo' for it.

**Comment by fangjian0423** [comment]
Could you please create a pull request to modify it?

**Comment by wzlee** [comment]
PR is done
