### ISSUE TITLE
Startup project occurred error when using spring-cloud-starter-stream-rocketmq. How to break it?

### ISSUE THREAD

**Issue by bydongxing** [spring-cloud-incubator/spring-cloud-alibaba#648]
引入依赖:
        <spring-cloud.version>Greenwich.RELEASE</spring-cloud.version>
        <spring-boot.version>2.1.4.RELEASE</spring-boot.version>
        <spring-cloud-alibaba.version>0.9.0.RELEASE</spring-cloud-alibaba.version>
配置文件：
spring.cloud.stream.rocketmq.binder.name-server=127.0.0.1:9876

spring.cloud.stream.bindings.output1.destination=sms-topic
spring.cloud.stream.bindings.output1.content-type=application/json
spring.cloud.stream.rocketmq.bindings.output1.producer.group=sms-producer-group
spring.cloud.stream.rocketmq.bindings.output1.producer.sync=true

spring.cloud.stream.bindings.output2.destination=email-topic
spring.cloud.stream.bindings.output2.content-type=application/json
spring.cloud.stream.rocketmq.bindings.output2.producer.sync=true
spring.cloud.stream.rocketmq.bindings.output2.producer.group=email-producer-group

source文件：
public interface ProducerSource {

    @Output("output1")
    MessageChannel output1();

    @Output("output2")
    MessageChannel output2();
}

启动的时候报如下的错误：
org.springframework.beans.factory.BeanCurrentlyInCreationException: Error creating bean with name 'BindingHandlerAdvise': Requested bean is currently in creation: Is there an unresolvable circular reference?

**Comment by fangjian0423** [comment]
Hi.

Could you run successful with [rocketmq-produce-example](https://github.com/spring-cloud-incubator/spring-cloud-alibaba/tree/master/spring-cloud-alibaba-examples/rocketmq-example/rocketmq-produce-example).

**Comment by fangjian0423** [comment]
Could you show any other dependencies? It runs well in my local.

**Comment by bydongxing** [comment]
完整的依赖：
<dependencies>
        <dependency>
            <groupId>org.springframework.cloud</groupId>
            <artifactId>spring-cloud-starter-stream-rocketmq</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.cloud</groupId>
            <artifactId>spring-cloud-starter-alicloud-sms</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-validation</artifactId>
        </dependency>
        <dependency>
            <groupId>org.antframework.idcenter</groupId>
            <artifactId>idcenter-spring-boot-starter</artifactId>
            <version>1.4.1.RELEASE</version>
        </dependency>
        
        <dependency>
            <groupId>io.springfox</groupId>
            <artifactId>springfox-swagger-ui</artifactId>
            <version>${swagger2.version}</version>
        </dependency>
        <dependency>
            <groupId>io.springfox</groupId>
            <artifactId>springfox-swagger2</artifactId>
            <version>${swagger2.version}</version>
        </dependency>
        <dependency>
            <groupId>org.freemarker</groupId>
            <artifactId>freemarker</artifactId>
            <version>2.3.28</version>
        </dependency>
        <dependency>
            <groupId>mysql</groupId>
            <artifactId>mysql-connector-java</artifactId>
            <scope>runtime</scope>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-jdbc</artifactId>
        </dependency>
        <dependency>
            <groupId>com.baomidou</groupId>
            <artifactId>mybatis-plus-boot-starter</artifactId>
            <version>${mybatis-plus.version}</version>
        </dependency>
        <dependency>
            <groupId>com.baomidou</groupId>
            <artifactId>mybatis-plus-generator</artifactId>
            <version>${mybatis-plus.version}</version>
        </dependency>

        <dependency>
            <groupId>com.alibaba</groupId>
            <artifactId>druid-spring-boot-starter</artifactId>
            <version>${druid.version}</version>
        </dependency>
        
        <dependency>
            <groupId>log4j</groupId>
            <artifactId>log4j</artifactId>
            <version>${druid-log4j.version}</version>
            <scope>compile</scope>
        </dependency>

        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-web</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-test</artifactId>
        </dependency>
    </dependencies>

**Comment by fangjian0423** [comment]
Hi, did you solve it? I received your comment on email, but you deleted it.

**Comment by bydongxing** [comment]
> Could you show any other dependencies? It runs well in my local.

其他的依赖：
`<properties>`
        `<druid-log4j.version>1.2.17</druid-log4j.version>`
        `<druid.version>1.1.10</druid.version>`
        `<mybatis-plus.version>3.1.0</mybatis-plus.version>`
        `<swagger2.version>2.8.0</swagger2.version>`
`</properties>`
`<dependencies>`
        `<dependency>`
            `<groupId>org.springframework.cloud</groupId>`
            `<artifactId>spring-cloud-starter-stream-rocketmq</artifactId>`
        `</dependency>`
        `<dependency>`
            `<groupId>org.springframework.cloud</groupId>`
            `<artifactId>spring-cloud-starter-alicloud-sms</artifactId>`
        `</dependency>`
        `<dependency>`
            `<groupId>org.springframework.boot</groupId>`
            `<artifactId>spring-boot-starter-validation</artifactId>`
        `</dependency>`
        `<dependency>`
            `<groupId>org.antframework.idcenter</groupId>`
            `<artifactId>idcenter-spring-boot-starter</artifactId>`
            `<version>1.4.1.RELEASE</version>`
        `</dependency>`
        
        `<dependency>`
            `<groupId>io.springfox</groupId>`
            `<artifactId>springfox-swagger-ui</artifactId>`
            `<version>${swagger2.version}</version>`
        `</dependency>`
        `<dependency>`
            `<groupId>io.springfox</groupId>`
            `<artifactId>springfox-swagger2</artifactId>`
            `<version>${swagger2.version}</version>`
        `</dependency>`
        `<dependency>`
            `<groupId>org.freemarker</groupId>`
            `<artifactId>freemarker</artifactId>`
            `<version>2.3.28</version>`
        `</dependency>`
        `<dependency>`
            `<groupId>mysql</groupId>`
            `<artifactId>mysql-connector-java</artifactId>`
            `<scope>runtime</scope>`
        `</dependency>`
        `<dependency>`
            `<groupId>org.springframework.boot</groupId>`
            `<artifactId>spring-boot-starter-jdbc</artifactId>`
        `</dependency>`
        `<dependency>`
            `<groupId>com.baomidou</groupId>`
            `<artifactId>mybatis-plus-boot-starter</artifactId>`
            `<version>${mybatis-plus.version}</version>`
        `</dependency>`
        `<dependency>`
            `<groupId>com.baomidou</groupId>`
            `<artifactId>mybatis-plus-generator</artifactId>`
            `<version>${mybatis-plus.version}</version>`
        `</dependency>`
        `<dependency>`
            `<groupId>com.alibaba</groupId>`
            `<artifactId>druid-spring-boot-starter</artifactId>`
            `<version>${druid.version}</version>`
        `</dependency>`
        
        `<dependency>`
           `<groupId>log4j</groupId>`
            `<artifactId>log4j</artifactId>`
            `<version>${druid-log4j.version}</version>`
            `<scope>compile</scope>`
        `</dependency>`
        `<dependency>`
            `<groupId>org.springframework.boot</groupId>`
            `<artifactId>spring-boot-starter-web</artifactId>`
        `</dependency>`
        `<dependency>`
            `<groupId>org.springframework.boot</groupId>`
            `<artifactId>spring-boot-starter-test</artifactId>`
        `</dependency>`
  `</dependencies>`

**Comment by fangjian0423** [comment]
Could you put the configurations here(remove sensitive information) or provide a project that reproduces the issue?

**Comment by bydongxing** [comment]
> Could you put the configurations here(remove sensitive information) or provide a project that reproduces the issue?

I have pushed to github，url：https://github.com/bydongxing/ncs.git   
Thanks

**Comment by fangjian0423** [comment]
@bydongxing The `javax.validation.Validator` you build on `WebMvcConfigure` will cause unresolvable circular reference problem no matter which binder you are using. Kafka Binder will also throw same exception.

**Comment by fangjian0423** [comment]
refer https://github.com/spring-cloud/spring-cloud-stream/issues/1716.
