### ISSUE TITLE
Thread-unsafe may happen in spring-cloud-alibaba-nacos-config module.

### ISSUE THREAD

**Issue by wangzhanxu** [spring-cloud-incubator/spring-cloud-alibaba#652]
**Nacos Config Module**

DateFormat instance is not thread-safe in NacosRefreshHistory class.

**Comment by fangjian0423** [comment]
Could you please help to contribute to modify it?

**Comment by pyhblacksky** [comment]
@fangjian0423 Hello, I solve it problem. Please check it. If there is any problem, please let me know in time
