### ISSUE TITLE
dubbo metadata information

### ISSUE THREAD

**Issue by halower** [spring-cloud-incubator/spring-cloud-alibaba#655]
**Which Component**
Dubbo or Nacos

**Describe the bug**
when I upgraded the `spring-cloud-alibaba-dubbo` version to 0.9.0, I found that even if I retreated the `spring-cloud-alibaba-dubbo` version back to the previous old version, and I cleared the local cache, the metadata information obtained in Nacos was always` 0.9.0` version of the format, so I'm not sure if this is a `spring-cloud-alibaba-dubbo` problem or a `nacos` problem or  my self problem..

**To Reproduce**
1. upgrade the Spring-cloud-alibaba-dubbo version to 0.9.0.RELEASE
2. roll back to the old version

**Comment by fangjian0423** [comment]
Now the metadata info like this in 0.9.0.RELEASE version:

dubbo.metadata-service.urls=[ "dubbo://youip:youport/org.springframework.cloud.alibaba.dubbo.service.DubboMetadataService?anyhost=true&application=dubbo-provider&bind.ip=yourip&bind.port=youip:youport&default.deprecated=false&default.dynamic=false&default.register=true&deprecated=false&dubbo=2.0.2&dynamic=false&generic=false&group=dubbo-provider&interface=org.springframework.cloud.alibaba.dubbo.service.DubboMetadataService&methods=getAllServiceKeys,getServiceRestMetadata,getExportedURLs,getAllExportedURLs&pid=95710&register=true&release=2.7.1&revision=0.9.0.RELEASE&side=provider&timestamp=1558833702093&version=1.0.0" ]

dubbo.protocols.yourprotocol.port=20880

**Comment by fangjian0423** [comment]
The interface info saves in service side, registration center only export `org.springframework.cloud.alibaba.dubbo.service.DubboMetadataService`.
