### ISSUE TITLE
SpringCloudAlibabba（SCA）sentinel组件和EDAS AHAS的兼容性

### ISSUE THREAD

**Issue by tuser4198** [spring-cloud-incubator/spring-cloud-alibaba#664]
**Which Component**
eg. sentinel，AHAS

**Describe what problem you have encountered**
目前我们测试环境用的SCA sentinel，如果正式环境用EDAS的AHAS的话，需要做哪些工作？
**Describe what information you have read**
https://github.com/spring-cloud-incubator/spring-cloud-alibaba/wiki/ANSl
https://github.com/spring-cloud-incubator/spring-cloud-alibaba/wiki/ACM
EDAS的相关文档
https://help.aliyun.com/document_detail/94708.html?spm=5176.10695662.1996646101.searchclickresult.718c1454NKCcrh
https://help.aliyun.com/document_detail/102571.html?spm=a2c4g.11174283.6.576.7c113342oyf9C4

**Comment by fangjian0423** [comment]
我们下周在阿里云上会有一篇文档专门讲解 EDAS & AHAS 的使用，现在还有一点问题。

We will have a document on Alibaba Cloud next week dedicated to the use of EDAS & AHAS.

**Comment by tuser4198** [comment]
ok

**Comment by fangjian0423** [comment]
@tuser4198 refer https://help.aliyun.com/document_detail/119515.html
