### ISSUE TITLE
Nacos1.0权重依旧不生效

### ISSUE THREAD

**Issue by chenhongbinjs** [spring-cloud-incubator/spring-cloud-alibaba#669]
使用的组件版本：
Nacos1.0
SpringCloud:Greenwich.RELEASE
SpringCloudAlibaba:0.9.0.RELEASE
![1](https://user-images.githubusercontent.com/2688281/58363399-288de600-7ed6-11e9-9e83-edb33634e6a4.jpg)
Nacos权重设置：
![2](https://user-images.githubusercontent.com/2688281/58363405-32afe480-7ed6-11e9-91fd-9c29ce5d6e2b.jpg)
测试结果：
![3](https://user-images.githubusercontent.com/2688281/58363412-43f8f100-7ed6-11e9-980a-35e5c9456eb9.jpg)
看这结果是平均分配的，如果将其中一个权重设置为0，结果只会访问另外一个，这个倒是有效的。
我的Consumer代码如下：
`@RestController
public class DemoController {

	@Autowired
	private RestTemplate restTemplate;

	@GetMapping("test")
	public String test(String name) {
		String result = restTemplate.getForObject("http://nacos-discovery-provider/demo?name="+name, String.class);
		return result;
	}
}`

`@EnableDiscoveryClient
@SpringBootApplication
public class NacosDiscoveryConsumerApplication {

	public static void main(String[] args) {
		SpringApplication.run(NacosDiscoveryConsumerApplication.class, args);
	}

	@Bean
	@LoadBalanced
	public RestTemplate restTemplate() {
		return new RestTemplate();
	}

}
`

**Comment by fangjian0423** [comment]
Ribbon is not support weight algorithm.

You could implement your own `IRule` to support this, get weight from `NacosServer#metadata`.

**Comment by chenhongbinjs** [comment]
> Ribbon is not support weight algorithm.
> 
> You could implement your own `IRule` to support this, get weight from `NacosServer#metadata`.

Ok, Thank you.

**Comment by fangjian0423** [comment]
refer https://github.com/alibaba/spring-cloud-alibaba/blob/master/spring-cloud-alibaba-nacos-discovery/src/main/java/com/alibaba/cloud/nacos/ribbon/NacosRule.java.

`NacosRule` us weight algorithm.
