### ISSUE TITLE
[spring-cloud-stream-binder-rocketmq]   Can't get configuration from nacos

### ISSUE THREAD

**Issue by NanakiMei** [spring-cloud-incubator/spring-cloud-alibaba#675]
**Which Component**
spring-cloud-stream-binder-rocketmq

**Describe the bug**
 Can't get configuration from nacos
`Could not resolve placeholder 'spring.cloud.stream.bindings.input1.destination' in value "${spring.cloud.stream.bindings.input1.destination}`

**Additional context**
MacOS  、Java8 、 Version 0.2.2.RELEASE、naocs 1.0.0-GA

**Comment by fangjian0423** [comment]
Hi, it works well in my local. So how did you use nacos config and provide your configurations about it.
