### ISSUE TITLE
spring-cloud-alibaba-nacos-discovery AutoServiceRegistion do not run the start method

### ISSUE THREAD

**Issue by TenzeTseng** [spring-cloud-incubator/spring-cloud-alibaba#68]
AutoServiceRegistion do not run the start method  when SpringCloud's version base on 2.0.0+ in module spring-cloud-alibaba-nacos-discovery.

**Comment by flystar32** [comment]
could you give a Minimal, Complete, and Verifiable example to give more detail about this issue?

**Comment by flystar32** [comment]
by the way, you can refer this example. https://github.com/spring-cloud-incubator/spring-cloud-alibaba/tree/master/spring-cloud-alibaba-examples/nacos-example/nacos-discovery-example

**Comment by flystar32** [comment]
corresponding version of spring cloud Edgware  is 0.1.0-BUILDSNASHOT,  corresponding version of spring cloud Finchley is 0.2.0-BUILDSNASHOT.

**Comment by TenzeTseng** [comment]
Thank you for your reply. The example you gave can run normally. I've integrated it into my project, and it's possible that a conflicting problem caused the registration to become unavailable . I've tested it out. Thanks a lot.
