### ISSUE TITLE
Nacos群集修改相同的服务配置文件，但只修改了一个服务

### ISSUE THREAD

**Issue by mybug99** [spring-cloud-incubator/spring-cloud-alibaba#681]
![image](https://user-images.githubusercontent.com/43434812/58538446-c27fc680-8227-11e9-803b-17dd4a656e99.png)
![image](https://user-images.githubusercontent.com/43434812/58538456-c7447a80-8227-11e9-8f08-32caac4c49cb.png)
![image](https://user-images.githubusercontent.com/43434812/58538468-cd3a5b80-8227-11e9-967d-d92eac0e7c52.png)
![image](https://user-images.githubusercontent.com/43434812/58538504-dcb9a480-8227-11e9-8781-5b30ff39232b.png)

这是三张图nacos也做了集群，但是只有一个服务刷新了，这是怎么回事？？？spring cloud alibaba是0.2.1的，nacosclient是0.9.0

**Comment by mybug99** [comment]
我的spring cloud版本是G1的

**Comment by mybug99** [comment]
之前在nacos上问过，让我在这里说一下，有人能解决吗

**Comment by mybug99** [comment]
在控制我也看到只有一个服务读取了刷新配置，另一个控制台只有心跳日志，这是bug还是少什么还是要升级版本？？

**Comment by fangjian0423** [comment]
G 版请使用 spring cloud alibaba 0.9.0

参考: https://github.com/spring-cloud-incubator/spring-cloud-alibaba/wiki/%E7%89%88%E6%9C%AC%E8%AF%B4%E6%98%8E
