### ISSUE TITLE
nacos官网接入springcloud示例运行失败

### ISSUE THREAD

**Issue by liucyu** [spring-cloud-incubator/spring-cloud-alibaba#682]
## 步骤
- 版本 springboot 2.1.4.RELEASE  springcloud Greenwich.SR1
- 本地按照官网教程搭建好nacos
- 新建springcloud项目，pom文件来自[nacos-spring-cloud-example/](https://github.com/nacos-group/nacos-examples/blob/master/nacos-spring-cloud-example/nacos-spring-cloud-config-example/pom.xml)
- 按照官网给的步骤依次配置[Nacos-config](https://github.com/spring-cloud-incubator/spring-cloud-alibaba/wiki/Nacos-config)
# 结果
拿不到配置，但是如果按照纯Java方式却能获取到配置

`bootstrap.properties`:

`spring.application.name=nacos-config`
`spring.cloud.nacos.config.server-addr=127.0.0.1:8848`

![image](https://user-images.githubusercontent.com/13191643/58543814-bfd69e80-8232-11e9-9937-e876befd1cb0.png)
日志
`2019-05-29 16:44:12.704  INFO 65456 --- [           main] b.c.PropertySourceBootstrapConfiguration : Located property source: CompositePropertySource {name='NACOS', propertySources=[NacosPropertySource {name='nacos-config.properties'}]}`

代码
![image](https://user-images.githubusercontent.com/13191643/58544175-5b680f00-8233-11e9-8158-ca34e341524c.png)

结果
![image](https://user-images.githubusercontent.com/13191643/58544055-252a8f80-8233-11e9-834c-9f7627b0fac4.png)
__

**Comment by fangjian0423** [comment]
Which version of spring cloud alibaba and nacos server are you using?

**Comment by liucyu** [comment]
版本 springboot 2.1.4.RELEASE springcloud Greenwich.SR1  spring-cloud-starter-alibaba-nacos-config 
0.2.1.RELEASE   @fangjian0423

**Comment by fangjian0423** [comment]
Spring Cloud Greenwich should use spring-cloud-starter-alibaba-nacos-config 0.9.0.RELEASE, refer https://github.com/spring-cloud-incubator/spring-cloud-alibaba/wiki/%E7%89%88%E6%9C%AC%E8%AF%B4%E6%98%8E.

**Comment by liucyu** [comment]
![image](https://user-images.githubusercontent.com/13191643/58604450-f78f2600-82c6-11e9-86db-b45531ce1808.png)
@fangjian0423 still not work....

**Comment by fangjian0423** [comment]
hi, did you solve it?

I think you can debug in `NacosPropertySourceLocator` to see what happened if didn't solve it.

**Comment by tale2009** [comment]
NacosPropertySourceLocator.loadApplicationConfiguration当使用loadNacosDataIfPresent你会发现我们的dataid会被修改成dataid.file-extension,所以用nacos新建配置的时候命名要是nacos-config.properties
