### ISSUE TITLE
The Nacos only has "preserved.register.source=SPRING_CLOUD" metadata

### ISSUE THREAD

**Issue by wadezyj** [spring-cloud-incubator/spring-cloud-alibaba#691]
This application is a spring boot application. Now, I changed a spring cloud alibaba application.
When this app register to nacos, The metadata only :

![image](https://user-images.githubusercontent.com/3404985/58709492-df192b80-83ec-11e9-8fb6-eb07069dd2a9.png)

**Comment by fangjian0423** [comment]
yes, this is a normal site. 

You could refer [wiki](https://github.com/spring-cloud-incubator/spring-cloud-alibaba/wiki/Nacos-discovery#%E5%85%B3%E4%BA%8E-nacos-starter-%E6%9B%B4%E5%A4%9A%E7%9A%84%E9%85%8D%E7%BD%AE%E9%A1%B9%E4%BF%A1%E6%81%AF), `NacosDiscoveryProperties#metadata` to customize your metadata.

**Comment by wadezyj** [comment]
> yes, this is a normal site.
> 
> You could refer [wiki](https://github.com/spring-cloud-incubator/spring-cloud-alibaba/wiki/Nacos-discovery#%E5%85%B3%E4%BA%8E-nacos-starter-%E6%9B%B4%E5%A4%9A%E7%9A%84%E9%85%8D%E7%BD%AE%E9%A1%B9%E4%BF%A1%E6%81%AF), `NacosDiscoveryProperties#metadata` to customize your metadata.

The application has not `dubbo.metadata-service.urls` and `dubbo.protocols.dubbo.port` metadata, So other service can not find this provider.

**Comment by wadezyj** [comment]
解决了，过程如下：
首先，这是一个Spring boot web应用，集成了Spring cloud aliababa时，启动时报如下错误：
`Error creating bean with name 'feignTargeter' defined in class path resource [org/springframework/cloud/openfeign/FeignAutoConfiguration$DefaultFeignTargeterConfiguration.class]: Initialization of bean failed; nested exception is java.lang.IllegalAccessError: class org.springframework.cloud.openfeign.$Proxy149 cannot access its superinterface org.springframework.cloud.openfeign.Targeter`。
于是我在pom排除掉`spring-cloud-openfeign-core`，可以正常启动，但是在nacos注册中心看不到该服务的dubbo元数据，只有`preserved.register.source=SPRING_CLOUD`。
最后我在`SpringBootApplication`中增加`exclude = {FeignAutoConfiguration.class}`，正常启动，并且在注册中心看到了dubbo元数据.
