### ISSUE TITLE
Whether to support the startup phase injection configuration, such as the scenario using @ConditionalOnProperty or some configuration that spring-boot-starter needs to read during the startup phase.

### ISSUE THREAD

**Issue by joewee** [spring-cloud-incubator/spring-cloud-alibaba#701]
**Which Component**
 Nacos Config

**Describe what problem you have encountered**
Whether to support the startup phase injection configuration, such as the scenario using @ConditionalOnProperty or some configuration that spring-boot-starter needs to read during the startup phase.

**Describe what information you have read**

**Comment by fangjian0423** [comment]
Could you describe it clearly, i can't understand what you said. Thanks.

**Comment by joewee** [comment]
@fangjian0423 Thanks for you reply ,
@ConditionalOnProperty will be handled in the refresh process of ApplicationContext,
 but at that time nacos has not been initialized yet, I am not sure whether I understand it correctly.So, my question is how to read  the configuration  like  @ConditionalOnProperty(value = "xxx.xxxx.xxx",) from nacos config center during the boot phase.

**Comment by fangjian0423** [comment]
just configure them in nacos.

Spring Cloud Application has two ApplicationContexts, one is bootstrap context, the other is application context.

Nacos configuration items will be loaded in bootstrap context, so @ConditionalOnProperty(value = "xxx.xxxx.xxx",) will be effected in application context.

**Comment by joewee** [comment]
@fangjian0423 Thanks a lot, i got it.
