### ISSUE TITLE
Provide some configuration items about Nacos logging

### ISSUE THREAD

**Issue by eacdy** [spring-cloud-incubator/spring-cloud-alibaba#702]
Nacos的日志级别怎么自定义，目录怎么自定义，文件名称怎么自定义哈？
spring cloud alibaba能否提供配置适配，为配置提供方便。

**Comment by fangjian0423** [comment]
related to https://github.com/alibaba/nacos/issues/1276

**Comment by flystar32** [comment]
I will handle this, support log file and log name configuration via Nacos property api.

I wonder whether Nacos would support to modify log level from code. if the answer is no,maybe you should submit an issue to nacos first.

**Comment by eacdy** [comment]
@flystar32 Thanks a lot.
I've sumited it. <https://github.com/alibaba/nacos/issues/1349>
