### ISSUE TITLE
Config client has too many logs. How can I turn it off

### ISSUE THREAD

**Issue by Nemo1986** [spring-cloud-incubator/spring-cloud-alibaba#704]
**Which Component**
spring-cloud-starter-alibaba-nacos-config

**Describe what problem you have encountered**

00:00:15.481 logback [com.alibaba.nacos.naming.beat.sender] INFO  com.alibaba.nacos.client.naming - [BEAT] public sending beat to server: 

There are too many logs on the client. How can I turn it off.

**Comment by fangjian0423** [comment]
try this:

```properties
logging.level.com.alibaba.nacos=ERROR
```

**Comment by Nemo1986** [comment]
it's working!thk u
