### ISSUE TITLE
spring-cloud-alibaba-nacos-discovery 不兼容spring5.1版本问题。

### ISSUE THREAD

**Issue by codeDW** [spring-cloud-incubator/spring-cloud-alibaba#705]
spring 5.1 版本后 EventListenerMethodProcessor 新增如下图方法，
![图片](https://user-images.githubusercontent.com/24667685/59322679-e6540980-8d09-11e9-8133-bb986a688fdb.png)

导致NacosAutoServiceRegistration，无法作为applicationListener注入到容器中，最后导致服务注册失败。

**Comment by fangjian0423** [comment]
refer https://github.com/spring-cloud-incubator/spring-cloud-alibaba/wiki/%E7%89%88%E6%9C%AC%E8%AF%B4%E6%98%8E

**Comment by umi-soft** [comment]
我也是这样的问题，nacos版本按照wiki中的进行替换，无法解决问题
