### ISSUE TITLE
Sentinel Datasource Checking Problem(Currently under ZooKeeper Data Source)

### ISSUE THREAD

**Issue by jasonjoo2010** [spring-cloud-incubator/spring-cloud-alibaba#707]
**Which Component**
spring-cloud-alibaba-sentinel

**Describe the bug**
The issued checking is locate `SentinelDataSourceHandler.logAndCheckRuleType`

**To Reproduce**
Using ZookeeperDataSource

**Expected behavior**
Initialize datasource properly.

### Curator Framework
Curator connects to zookeeper in asynchronous way but SCA will do the rules check immediately after initialize the data source bean. This will cause the check fails before the connection had been made.

### Check or Not to Check
And sentinel's various data sources are considered to cover both synchronized and asynchronous ways so maybe the check should be removed until we find a better way to do the check.

### Log Stream Merging
I suggest that why there exists a check is that sentinel has its own separated logging so we won't see anything output in the project logging. But we are working on the optional console logging(Currently) and SPI support of logging (Maybe in Future if it's necessary) this problem could be improved. There will be related logging informations like "[ZookeeperDataSource] New property value received for ......".

Please correct me if i make any mistake.

**Comment by fangjian0423** [comment]
Agree with you, i will remove the check log of Sentinel DataSource :smile:
