### ISSUE TITLE
 spring-cloud-alibaba-sentinel-gateway

### ISSUE THREAD

**Issue by chenqincheng** [spring-cloud-incubator/spring-cloud-alibaba#715]
我们鼓励使用英文，如果不能直接使用，可以使用翻译软件，您仍旧可以保留中文原文。
We recommend using English. If you are non-native English speaker, you can use the translation software. 

**Which Component**
eg. spring-cloud-alibaba-sentinel-gateway

**Describe the bug**
1.**rename**  spring-cloud-alibaba-sentinel-zuul to  spring-cloud-alibaba-sentinel-gateway（https://github.com/spring-cloud-incubator/spring-cloud-alibaba/commit/ef415f87ad7bd42edd135e7834cba7b1b25d70ff）

2. **we can't get spring-cloud-alibaba-sentinel-gateway from maven repository**, but we can get  spring-cloud-alibaba-sentinel-zuul from maven repository 
(https://mvnrepository.com/artifact/org.springframework.cloud/spring-cloud-alibaba-sentinel-zuul)

**Expected behavior**
we can get spring-cloud-alibaba-sentinel-gateway from maven repository

**Additional context**
windows  、Java8 、 Version 0.9.0.RELEASE

**Comment by fangjian0423** [comment]
spring-cloud-alibaba-sentinel-gateway module has been not release now.

Refer https://github.com/spring-cloud-incubator/spring-cloud-alibaba/wiki/%E7%89%88%E6%9C%AC%E8%AF%B4%E6%98%8E if you want to use snapshot version.
