### ISSUE TITLE
nacos-config 1.0.0

### ISSUE THREAD

**Issue by WunHwanTseng** [spring-cloud-incubator/spring-cloud-alibaba#718]
nacos-config
spring.cloud.nacos.config.shared-dataids cannot update application environment of redis config

properties:
spring.cloud.nacos.config.shared-dataids=auth-common.properties,redis-common.properties spring.cloud.nacos.config.refreshable-dataids=auth-common.properties,redis-common.properties

error:
Unable to connect to Redis; nested exception is io.lettuce.core.RedisConnectionException: Unable to connect to {ip}:6379

**Comment by fangjian0423** [comment]
refer nacos config wiki: https://github.com/spring-cloud-incubator/spring-cloud-alibaba/wiki/Nacos-config

make sure configuration item is right in bootstrap.yml or bootstrap.properties.

**Comment by WunHwanTseng** [comment]
@fangjian0423 bootstrap.properties。。`spring.cloud.nacos.config.shared-dataids=auth-common.properties,redis-common.properties ` ，`common.properties` can refresh environment ，but `redis-common.properties` didn't work

**Comment by fangjian0423** [comment]
1. provide your dependency
2. provide your configuration. `bootstrap.properties` and `application.properties`

**Comment by WunHwanTseng** [comment]
spring.cloud.version=Greenwich.RELEASE
