### ISSUE TITLE
中文readme图不全

### ISSUE THREAD

**Issue by oatiz** [spring-cloud-incubator/spring-cloud-alibaba#8]
![image](https://user-images.githubusercontent.com/24953151/45200188-347f3c80-b2a2-11e8-90b9-6847e7dd1e28.png)

**Comment by fangjian0423** [comment]
你好。 可以尝试清理下浏览器缓存。 如果还不行，可以访问 https://cdn.nlark.com/lark/0/2018/png/64647/1535108150178-409a1689-437f-495b-8dcb-b667ccb32f85.png   查看二维码。

**Comment by oatiz** [comment]
好棒 :purple_heart:
