### ISSUE TITLE
Sentinel starter datasource is difficult to use and should be refactored

### ISSUE THREAD

**Issue by fangjian0423** [spring-cloud-incubator/spring-cloud-alibaba#91]
Now the usage of sentinel datasource needs 3 steps.

1. Define the configuration of `ReadableDataSource` in `application.properties`:

// for example, file ReadableDataSource
spring.cloud.sentinel.datasource.type=file
spring.cloud.sentinel.datasource.recommendRefreshMs=3000
spring.cloud.sentinel.datasource.bufSize=4056196
spring.cloud.sentinel.datasource.charset=utf-8
spring.cloud.sentinel.datasource.converter=flowConverter
spring.cloud.sentinel.datasource.file=/Users/you/yourrule.json

2. Create a converter that implement `com.alibaba.csp.sentinel.datasource.Converter` interface. It should constructed  by spring and exist in `ApplicationContext`.

```
@Component("flowConverter")
public class JsonFlowRuleListParser implements Converter<String, List<FlowRule>> {
	@Override
	public List<FlowRule> convert(String source) {
		return JSON.parseObject(source, new TypeReference<List<FlowRule>>() {
		});
	}
}
```

The converter bean name should be the same in `application.properties`.

3. Define a `ReadableDataSource` filed in a Spring bean that annotated by `@SentinelDataSource`.

```
@SentinelDataSource("spring.cloud.sentinel.datasource")
private ReadableDataSource dataSource;
```

The value of `@SentinelDataSource` means the prefix of  `ReadableDataSource` in `application.properties`. In this issue, the prefix is 'spring.cloud.sentinel.datasource' .

If there are more than 1 ReadableDataSource in `ApplicationContext`, none of them will be loaded, it will be effected when only one ReadableDataSource in `ApplicationContext`.

If the rules is loaded successfully. Some logs will be printed like this(this log means flow rules loaded):

[Sentinel Starter] load 3 flow rules

**Comment by CarpenterLee** [comment]
Thanks for you suggestion. 
[Sentinel DataSource](https://github.com/alibaba/Sentinel/wiki/%E5%8A%A8%E6%80%81%E8%A7%84%E5%88%99%E6%89%A9%E5%B1%95)  has been well considered for kinds of different data source, such as [Nacos](https://github.com/alibaba/nacos), ZK, apollo, etc. And file based data source is just among one of them. 

In production environment, we recommend to use a dynamic configuration center to allow change Sentinel rules dynamically.

While the rule configuration here is a little bit complex, you can try [Sentinel Dashboard](https://github.com/alibaba/Sentinel/wiki/%E6%8E%A7%E5%88%B6%E5%8F%B0) to simplify it.

**Comment by fangjian0423** [comment]
#99

**Comment by fangjian0423** [comment]
The better way of using Sentinel `ReadableDataSource` only need 1 step.

application.properties
```
spring.cloud.sentinel.datasource.ds1.file.file=classpath: flowrule.json
spring.cloud.sentinel.datasource.ds1.file.data-type=json

spring.cloud.sentinel.datasource.ds2.file.file=classpath: degraderule.xml
spring.cloud.sentinel.datasource.ds2.file.data-type=xml

spring.cloud.sentinel.datasource.ds3.nacos.server-addr=localhost:8848
spring.cloud.sentinel.datasource.ds3.nacos.dataId=sentinel
spring.cloud.sentinel.datasource.ds3.nacos.groupId=DEFAULT_GROUP
spring.cloud.sentinel.datasource.ds3.nacos.data-type=json
```

This way is a little same like the bindings configuration of Spring Cloud Stream Binder.

`spring.cloud.sentinel.datasource` is the prefix of `ReadableDataSource` configuration.

`ds1`, `ds2`, `ds3` means the name of `ReadableDataSource`. We use `TreeMap` to store this.

The 'file' after ds1 means the type of `ReadableDataSource` is `FileDataSourceProperties` and the configurations after 'file' like 'file' means the properties of `FileDataSourceProperties`.

The 'nacos' after ds3 means the type of `ReadableDataSource` is `NacosDataSourceProperties` and the configurations after 'nacos' like 'server-addr' means the properties of `NacosDataSourceProperties`.

Now we support 4 types of `ReadableDataSource`:  `file`, `nacos`, `apollo` and `zk`.

'data-type' now support 2 types: 'json' and 'xml', default value is 'json'. It means we will use `JsonConverter` or `XmlConverter` to convert source data to sentinel rule. 

`JsonConverter` or `XmlConverter` will try to convert each json object to 4 rules: FlowRule, DegradeRule, SystemRule and AuthorityRule. If one and only one of the rules convert successfully, it will added to the RuleList. 

There will be some warning logs printed when when json or xml object match multi rules or match none of rules, logs like this:

```
// json or xmlobject match multi rules
Sentinel JsonConverter convert {"resource":"resource"} and match multi rules, ignore
// json or xml object match no rule
Sentinel JsonConverter can not convert {"test":1,"resource":"resource"} to any rules, ignore
```

Note: `JsonConverter` or `XmlConverter` use `ObjectMapper` or `XmlMapper` of Jackson and the default `DeserializationFeature` configuration of these using `FAIL_ON_UNKNOWN_PROPERTIES(true)`. So there can not exist unknown properties on json or xml. There exist a unknown property 'test' in the warning logs, so it can not convert to any rules.


If you want to use your custom `Converter`, 'data-type' should be 'custom' and add a new `converter-class` configuration. The value of `converter-class` is full class name, like this:

```
spring.cloud.sentinel.datasource.ds1.file.converter-class=org.springframework.cloud.alibaba.cloud.examples.JsonFlowRuleListConverter
```

The Console will print logs when `ReadableDataSource` takes effect:

```
...
[Sentinel Starter] DataSource ds1-sentinel-file-datasource load 1 FlowRule
...
[Sentinel Starter] DataSource ds2-sentinel-file-datasource load 2 DegradeRule
...
[Sentinel Starter] DataSource ds3-sentinel-nacos-datasource load 3 FlowRule
```

**Comment by tony-Ma-yami** [comment]
can sentinel datasource of file support " classpath:" now ?

**Comment by tony-Ma-yami** [comment]
expect for you
