### ISSUE TITLE
Sentinel NacosDataSource config

### ISSUE THREAD

**Issue by huangll99** [spring-cloud-incubator/spring-cloud-alibaba#99]
I want use Sentinel NacosDataSource,but I can not find a config demo.
Try a lot,still not work.
Here is my config.
`
spring.cloud.sentinel.datasource.type=nacos
spring.cloud.sentinel.datasource.server-addr=http://10.3.10.131:8848
spring.cloud.sentinel.datasource.group-id=demo
spring.cloud.sentinel.datasource.data-id=demo
spring.cloud.sentinel.datasource.convert=myParser
`

How shoud I config the "spring.cloud.sentinel.datasource.convert" parameter?

**Comment by fangjian0423** [comment]
We will refactor this and provide a better way to using Sentinel `ReadableDataSource`. Please pay attention to issue #91
